<?php
/**
 * ReOS is a vertical software for real estates.
 * Copyright 2010 IT ELAZOS S.L.
 *
 * This file is part of ReOS v2.x.x.
 *
 * ReOS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ReOS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with ReOS.  If not, see <http://www.gnu.org/licenses/>.
 **/


//File generated from a txt file at : Thu, 18 Feb 2010 12:02:07 +0100

define("_0","No");
define("_1","Si");
define("_ABOUTUS","Qui Som");
define("_ACCOUNTS","Clients");
define("_ACONSULTAR","A consultar");
define("_ACTIVE","Activo");
define("_ACTIVE_ALL","TO_TRANSLATE");
define("_ACTIVITIES_LIST","Llista de valors activitats vacances");
define("_ADD","Afegir");
define("_ADDIMG","Añadir Foto");
define("_ADDIMGNOT","Fotos Noticia");
define("_ADDPOINT","Google Maps");
define("_ADDPRICELST","Afegir Llista de Preus");
define("_ADDPRICEPRD","Afegir Producte/Preu");
define("_ADDT_FILES","FITXERS ADICIONALS");
define("_ADD_ACCOUNT","Añadir Cliente");
define("_ADD_CITY","Afegir Població");
define("_ADD_COMDAD","Afegir Comunitat");
define("_ADD_CONTACT","TO_TRANSLATE");
define("_ADD_COUNTRY","Afegir País");
define("_ADD_CTG","Añadir familia");
define("_ADD_DEPT","Añadir Departamento");
define("_ADD_GAL","Añadir Galeria");
define("_ADD_IMG_GAL","Añadir imagen a la galería");
define("_ADD_IMMO","Añadir Inmueble");
define("_ADD_MAILING","Afegir mailing");
define("_ADD_NEW","Afegir Noticia");
define("_ADD_PERFIL","Añadir Perfil de Compra");
define("_ADD_PERM","Afegir Rol / Perfil");
define("_ADD_PICTURE","Añadir foto");
define("_ADD_POSITION","Añadir Empleado");
define("_ADD_PROD","Añadir producto");
define("_ADD_PROV","Afegir Comarca");
define("_ADD_SCR","Afegir Pantalla");
define("_ADD_SDAY","Afegir nous dies");
define("_ADD_SEASON","Afegir temporada");
define("_ADD_TICKET","Afegir Ticket");
define("_ADD_TK_CTG","afegir Categoria");
define("_ADD_USER","Afegir usuari");
define("_ADD_VAL","Afegir Valor");
define("_ADD_VIEW","Afegir Vista");
define("_ADD_ZONA","Nova Zona");
define("_ADMIN","Administració");
define("_ALL_ACCOUNTS","Tots els Clients");
define("_ALL_IMMOS","Tots els Immobles");
define("_ALL_NEWS","Todas las Noticias");
define("_ALL_TICKETS","TO_TRANSLATE");
define("_ANY","Indiferent");
define("_APP_FILE","Fitxer Aplicació");
define("_APRIL","Abril");
define("_ASIGN_POB","Seleccionar Poblaciones preferidas");
define("_AUGUST","Agost");
define("_AVG_DAY_HITS","Mitjana Pàgines Vistes Diaries");
define("_AVG_DAY_ROBOTS","Mitjana Buscadors Diaris");
define("_AVG_DAY_VISITS","Mitjana Visites Diaries");
define("_BACK","Enrera");
define("_BACKUP","Copies de seguretat");
define("_BOOK","Llibre de visites");
define("_BOOKINGS","Reserves ");
define("_BOOKING_VALID","La seva reserva ha sigut enviada. Rebrà un email de validació.");
define("_BOOKVALID","Validació Reserva");
define("_BOOK_ISVALID","La seva reserva ha sigut validad. Ens posarem en contacte amb vostè per a confirmar la seva reserva.");
define("_BOOK_TXT","Pot deixar la seva opinió omplint el formulari del final. Moltes gràcies por la seva participació.");
define("_BORRAR","Borrar");
define("_BUGGET","Pressupost "._CURRENCY."");
define("_BUSY","Ocupat");
define("_BUSYBOOKING","L'immoble es ocupat per a les dates seleccionades");
define("_BUYERS_ACCOUNTS","Buscar Compradores");
define("_BUY_GUIDE","Guia de compra");
define("_CALC","Calcular");
define("_CALC_INM","Càlcul de quotes hipoteca");
define("_CALC_LOAN_PAYMENTS","Càlcul de cuotes hipoteca");
define("_CALENDAR","Agenda");
define("_CAPTCHA","Texte de verificació");
define("_CATALOG","Catálogo");
define("_CHANGE_PASS","Cambiar la contrasenya");
define("_CHARSET","UTF-8");
define("_CMT_CSSFILE","Fitxer CSS - Cascading Style Sheets");
define("_CMT_IMAG","Gestió de imatges de diseny y fitxers flash");
define("_CMT_XMLNAV","Fitxer XML que defineix l'estructura de cada pàgina.");
define("_CMT_XMLOUTPUT","Fitxer generat per l'aplicació com entrada del fitxer XSL Transformation");
define("_CMT_XMLPRT","Fitxer XML que defineix l'estructura de cada pàgina per a imprimir");
define("_CMT_XSLFILE","Fitxer XSL de Transformació - Pren com entrada el fitxer XML Output de l'aplicació.");
define("_CMT_XSLPRT","Fichero XSL de transformación. Toma como entrada el fichero XML Output de la aplicación.");
define("_COD","Codi");
define("_COD_CATEGORY","Codi de Familia");
define("_COD_LANG","Idioma");
define("_COD_PRODUCT","Codi de Producte");
define("_COMDAD_NAME","Comunitat Autónoma");
define("_COMO","Ens vas conèixer per...");
define("_COM_APER","Comissió d'obertura");
define("_CONFIRM","Confirmació del registre");
define("_CONNECTED_AS","Conectat com");
define("_CONTACTAR","Contactar");
define("_CONTACTS","Contactes");
define("_CONTENTS","Continguts");
define("_CPASS","Contraseña");
define("_CSSCONFIG","Fitxers CSS");
define("_CSSFILE","CSS File");
define("_CSS_DELETED","Fichero CSS eliminat");
define("_CTG","Familia");
define("_CTGS","Familias");
define("_CTG_BELONGS","Familia a la que pertenece");
define("_CTG_HAS_PROD","Error al eliminar familia. La familia tiene productos, elimine primero los productos");
define("_CTG_NO_EXIST","Familia no existe");
define("_CTG_NO_NAME","El nombre de familia es obligatorio");
define("_CURRENT_PASS","Contrasenya Actual");
define("_CUSTOMER","Client");
define("_CUSTZONE","Àrea Clients");
define("_DATE","Data");
define("_DATEMP","Dades Empresa");
define("_DATETIME_SQL","'%d/%m/%Y - %H:%i'");
define("_DATE_FORMAT","d/m/Y");
define("_DATE_FT","Data");
define("_DATE_SQL","'%d/%m/%Y'");
define("_DATOS_PERS","Dades Personals");
define("_DATPERS","Dades Personals");
define("_DAY","Día");
define("_DEACTIVE_ALL","TO_TRANSLATE");
define("_DECEMBER","Desembre");
define("_DEC_POINT",",");
define("_DELETE","Eliminar");
define("_DELETED","Element eliminat correctament");
define("_DEPT","Departament");
define("_DEPTS","Departaments");
define("_DESC_CATEGORY","Descripció");
define("_DESC_PROD","Descripció");
define("_DO_CALC","Càlcul Hipoteca");
define("_DTL","Detall");
define("_DTL_ACCOUNT","Datos Cliente");
define("_DTL_ACCPERFIL","Datos Perfil de Compra");
define("_DTL_PROP","Datos Inmueble");
define("_DT_CREATE","Data d'alta");
define("_DT_END","Data fi");
define("_DT_SENT","Data d'enviament");
define("_DT_START","Data Inici");
define("_DT_VAL","Data de Validesa");
define("_DT_VALID","Valid fins");
define("_EDIT","Editar");
define("_EDTACC","Cliente");
define("_EDTCOMDAD","Editar Provincia");
define("_EDTCONTACT","TO_TRANSLATE");
define("_EDTCOUNTRY","País");
define("_EDTCTG","Familia");
define("_EDTGAL","Galeria");
define("_EDTHIMMO","Propietats Allotjament Vacances");
define("_EDTHTML","editar pàgina");
define("_EDTIMMO","Inmueble");
define("_EDTIMMOGAL","Fotos immoble");
define("_EDTLABEL","Editar Literal");
define("_EDTLST","Valor");
define("_EDTMAILING","Detall del mailing");
define("_EDTMSG","TO_TRANSLATE");
define("_EDTORG","Departamento");
define("_EDTPERFIL","Perfil de Compra");
define("_EDTPERM","Perfil");
define("_EDTPOB","TO_TRANSLATE");
define("_EDTPOSITION","Detalle Empleado");
define("_EDTPRD","Producte");
define("_EDTPRDGAL","Fotos Producte");
define("_EDTPREF","TO_TRANSLATE");
define("_EDTPRICELST","Editar Llista de preus");
define("_EDTPRICEPRD","Editar Preu");
define("_EDTPROV","Editar Comarca");
define("_EDTSCR","Pantalla");
define("_EDTSDAY","Dies i preus");
define("_EDTSEASON","Detall Temporada");
define("_EDTTICKET","Editar Ticket");
define("_EDTTKCTG","TO_TRANSLATE");
define("_EDTTKEMAIL","TO_TRANSLATE");
define("_EDTUSER","Usuario");
define("_EDTVIEW","Vista");
define("_EDT_ACCOUNT","Editar cliente");
define("_EDT_CONTACT","TO_TRANSLATE");
define("_EDT_CTG","Editar Familia");
define("_EDT_DEPT","Editar Departamento");
define("_EDT_EMPL","Editar Empleado");
define("_EDT_GAL","Editar Galeria");
define("_EDT_IMMO","Editar Inmueble");
define("_EDT_MAILING","Editar mailing");
define("_EDT_NEW","Editar Noticia");
define("_EDT_PERM","Editar Rol / Perfil");
define("_EDT_PROD","Editar producto");
define("_EDT_SCR","Editar Pantalla");
define("_EDT_USER","Editar Usuari");
define("_EDT_VAL","Editar Valor");
define("_EDT_VIEW","Editar Vista");
define("_EMPL","Empleado");
define("_EMPLES","TO_TRANSLATE");
define("_ENVIAR","Enviar");
define("_EQUIP_LIST","Llista de valors equipaments lloguers vacances");
define("_ERROR_CAPTCHA","Introdueixi el texte de verificació.");
define("_ERROR_CHECK_PSW","Error al comprobar contraseña");
define("_ERROR_CONTENT_MAILING","Introdueixi el contingut del mail");
define("_ERROR_CURRENT_PSW","Contrasenya actual incorrecta");
define("_ERROR_DATS","Error al accedir a les dades");
define("_ERROR_DELETE","Error en l'elimnació");
define("_ERROR_DIR_GAL","Error al crear directoris galeria");
define("_ERROR_EMAIL_USER","Debe introducir el email");
define("_ERROR_ES_IN","Es te d'introduir un valor en Espanyol");
define("_ERROR_IN","Error");
define("_ERROR_INSERT","Error al afegir");
define("_ERROR_LAST_USER","No se puede eliminar el último usuario de la organización");
define("_ERROR_NAME_MAILING","Introdueixi el nom del mailing");
define("_ERROR_NAME_USER","El nombre completo es obligatorio");
define("_ERROR_NM","Cal introduir el nom");
define("_ERROR_NM_PROFILE","El nom ha de tenir més de 5 caràcters");
define("_ERROR_NOPOB","No se han encontrado poblaciones para la provincia");
define("_ERROR_NUM_DOM","Introduzca el número de habitaciones");
define("_ERROR_NUM_PARKING","Introduzca el numero de plazas de parking");
define("_ERROR_NUM_WC","Introduzca el número de baños");
define("_ERROR_OBSRV","Cal introduir la descripció");
define("_ERROR_OPEN_DIR","No se puede abrir el directorio");
define("_ERROR_OPEN_FILE","Error al obrir fitxer");
define("_ERROR_PASSUSR_NULL","EL usuario y la contraseña debe estar en blanco o tener valos ambos");
define("_ERROR_PROCESS","El process ha generat errors");
define("_ERROR_PSW_ERROR","Ha introducido la contraseña incorrectamente, reescriba la contraseña en los dos campos");
define("_ERROR_PSW_NOSTR","La contraseña solo puede contener letras y numeros, espacios no");
define("_ERROR_PSW_SHORT","La contraseña debe tener más de 5 carácteres");
define("_ERROR_PSW_USERNAME","La contraseña no puede ser igual al nombre de usuario");
define("_ERROR_SUBJ_MAILING","Introdueixi el asumpte del mail");
define("_ERROR_SUPERF","Introduzca la superficie del terreno/parcela en M2, sino tiene ponga 0");
define("_ERROR_SUPERF_CONST","Introduzca la superficie en M2, sino tiene ponga 0");
define("_ERROR_SUPERT","Introdueixi la superficie de terrassa  o posi 0");
define("_ERROR_TELF1_USER","Debe introducir el teléfono");
define("_ERROR_TXT_CONTENT","Cal introduir algun missatge.");
define("_ERROR_UPDATE","Error en la modificació");
define("_ERROR_USNAME_EXIST","El nombre de usuario ya existe, elija otro");
define("_ERROR_USRNAME_EXISTS","El usuari ja existeix !");
define("_ERROR_USRNAME_NOSTR","El usuario solo puede contener letras y numeros, espacios no");
define("_ERROR_USRNAME_SHORT","El nombre de usuario debe tener más de 5 carácteres");
define("_ER_SELET_TBL","Error en SELECT taula");
define("_FDAY","Dv");
define("_FEBRUARY","Febrero");
define("_FECHA_FT","Data");
define("_FG_HIDDEN","TO_TRANSLATE");
define("_FG_PRIVATE","TO_TRANSLATE");
define("_FIND","Cercar");
define("_FIND_BY_CITIES","Cercar per població");
define("_FIND_BY_CRITERIA","Cercar per criteris");
define("_FIND_BY_TPPROP","Cercar per tipus d'immoble");
define("_FINPAGINA","");
define("_FOLDER","Directori");
define("_FOUND","Total trobats");
define("_FRIDAY","Divendres");
define("_FRONT","Portada");
define("_FULL_NAME","Nom Complert");
define("_GALLERIES","Galeries de Fotos");
define("_GALLERY","Galeria");
define("_GALS","Galeries de fotos");
define("_GAL_LST","Llista de Galeries");
define("_GAST_GEST","Despeses Gestoria, Notaria, Registre. <br/> (Depèn del Gestor) Mínim :");
define("_GENERAL_LAYOUT","ESTRUCTURA PAG.GENERALS");
define("_GEN_LANG","Instalar canvis a idiomas");
define("_GESTLANGS","Gestió d'idiomas");
define("_GST_COMPRA","Despeses compa de la vivenda");
define("_GST_HIPOT","Despeses hipoteca");
define("_GUIA","Guía");
define("_HELP","Ajuda");
define("_HOME","Inici");
define("_HOMEPG","Inici");
define("_HOUR","Hora");
define("_IDIOMA","ca");
define("_ID_CATEGORY","id Familia");
define("_ID_POSITION","Asignado a");
define("_ID_TICKET","TO_TRANSLATE");
define("_IMAG","Imatges y fitxers flash");
define("_IMG","Foto");
define("_IMGCONFIG","Imagtes Plantilla");
define("_IMGHOME","head.jpg");
define("_IMGS_NOT","Imatges de la noticia");
define("_IMG_FILE_ERROR","te un format incorrecte (Accents, espais, etc..) o es més grande de");
define("_IMG_FRONT","Imagen Portada");
define("_IMG_INT_1","Imagen Interior 1");
define("_IMG_INT_2","Imagen Interior 2");
define("_IMG_INT_3","Imagen Interior 3");
define("_IMG_PORT","Imagen Portada");
define("_IMMO","Dades immoble");
define("_IMMOS","Immobles");
define("_IMP_ACTOS","Impostos dactes jurídics documentats");
define("_IMP_COMPRA","Imp. Tran. Patrimonials (Segona mà) o IVA (Nova) :");
define("_IMP_ENTR","Import de l'entrada");
define("_IMP_SOL","Import Hipoteca");
define("_IND_ACTIVE","Actiiu");
define("_IND_MAILING","Mailing");
define("_IND_OFERTA","Oferta");
define("_IND_PISCINA","Piscina");
define("_INFOLEGAL","Informació Legal");
define("_INSERTED","Element afegit correctament");
define("_INSIDE","Interior");
define("_INTROS_LIST","Llista de valors de Intro d'una oferta");
define("_INT_BANC","Interès bancari");
define("_INT_CAPACITY","Capacitat pers.");
define("_INT_PERS","Nombre de persones");
define("_INT_SUPERFICIE","Terreny M2");
define("_INT_SUPERFICIE_CONST","Superficie M2");
define("_INT_TERRACE","Terrassa M2");
define("_IN_NAME_ACCOUNT","El nombre de cliente es obligatorio");
define("_IN_NAME_GAL","El nombre de la galeria es obligatorio");
define("_IN_NAME_IMMO","La referencia de la Inmueble es obligatoria");
define("_IN_NAME_ORG","TO_TRANSLATE");
define("_IN_NOT_RESUM","El resum de la noticia es obligatori");
define("_IN_NOT_TITLE","El títol de la noticia es obligatori");
define("_IN_POB_IMMO","Debe seleccionar una población. Si no esta en la lista de poblaciones pongase en contacto con el administrador");
define("_IN_POB_ORG","Debe seleccionar una población para el departamento");
define("_IN_SUBJECT","Introduzca un asunto");
define("_JANUARY","Gener");
define("_JULY","Juliol");
define("_JUNE","Juny");
define("_KEYWORDS_ADM","TO_TRANSLATE");
define("_LABELS_LIST","Llista de literals del programa");
define("_LANGS","Idiomes");
define("_LANGUAGE","Idioma");
define("_LATTITUD","TO_TRANSLATE");
define("_LBL_SEASONS","Temporada");
define("_LOGIN_FAILED","El seu usuari o paraula de pas son incorrectes !");
define("_LOGIN_NOW","Entrar");
define("_LOGOUT","Desconectar");
define("_LONGITUD","TO_TRANSLATE");
define("_LOVS","Llistes de valors");
define("_LSTMAILING","Llista de mailings");
define("_LSTUSER","Lliste d'usuaris");
define("_M2","M2");
define("_M2_TERRACE","M2 de terrassa");
define("_M2_TERRENO","M2 de terreny");
define("_MAILING","Campanyes de Mailing");
define("_MAIL_BKVALID","Validació reserva");
define("_MAIL_BKVALID_TXT","Sr., 

Per a validar el seu registre te que accedir al següent enllaç :");
define("_MAIL_CONFIRM","La seva petició de registre ha sigut processada, en breus instants rebrà un correu per a validar el seu registre.");
define("_MAIL_FORMAT","El format del email es incorrecte");
define("_MAIL_HRECEV","Hem rebut la seva petició");
define("_MAIL_NMSG","L'atendrem el mes aviat possible");
define("_MAIL_NOTI","Notificació de recepció");
define("_MAIL_REM","Datos de Acceso");
define("_MAIL_REM_TXT","Sr., 

Les seves dades d'accés son :");
define("_MAIL_SUBS","Confirmació de registre");
define("_MAIL_SUBS_TXT","Sr., 

Per a validar el seu registre te que accedir al següent enllaç :

");
define("_MAIN_IMG","Imagen principal");
define("_MANDATORY","TO_TRANSLATE");
define("_MAPINIT","Vista Inicial Google Maps");
define("_MARCH","Març");
define("_MAY","Maig");
define("_MDAY","Dl");
define("_MKT","Mailings");
define("_MNU_ADM","Menu");
define("_MONDAY","Dilluns");
define("_MONTH","Mes");
define("_MSG","Missatge");
define("_MY_ACCOUNTS","Els Meus Clients");
define("_MY_IMMOS","Els meus immobles");
define("_MY_NEWS","Les Meves Noticies");
define("_MY_PROFILE","El Meu Perfil");
define("_MY_TICKETS","TO_TRANSLATE");
define("_MY_TK_STATS","TO_TRANSLATE");
define("_NAME","TO_TRANSLATE");
define("_NAME_ACCOUNT","Nombre de Cliente");
define("_NAME_CATEGORY","Familia");
define("_NAME_GAL","Nombre Galeria");
define("_NAME_MAILING","Nom del mailing");
define("_NAME_ORG","Oficina");
define("_NAME_POB","Població");
define("_NAME_POSITION","Carreg");
define("_NAME_PRICE_LST","Nom llista");
define("_NAME_PRODUCT","Nombre Producto");
define("_NAME_SEASONS","Nom temporada");
define("_NAME_USER","Nom Empleat / Usuari");
define("_NESPECIAL","La Nostra Oferta Especial");
define("_NEW","Noticia");
define("_NEWS","Noticies");
define("_NEWSLST","Llista de Noticies");
define("_NEWS_EVENTS","Noticies i events");
define("_NEWUSER","Nou usuari");
define("_NEW_PASSWORD","Nova contrasenya");
define("_NEW_POS","Posició");
define("_NEW_PROP","Vivenda Nova");
define("_NEW_RESUM","Resum");
define("_NEW_TITLE","Títol");
define("_NEW_TXT","Texte");
define("_NEXT","Següent");
define("_NM_CONTACT","TO_TRANSLATE");
define("_NM_PROFILE","Nom");
define("_NM_SCREEN","Pantalla");
define("_NM_TK_CTG","TO_TRANSLATE");
define("_NM_VIEW","Vista");
define("_NOREGUSERS","No hi ha clients registrats a el bulleti de noticies");
define("_NOSELECTED","No Seleccionat");
define("_NOTFOUND","TO_TRANSLATE");
define("_NOTI","Noticia");
define("_NOTICIA","Visualitzar Noticia");
define("_NOVED","Novetats");
define("_NOVED_TXT","Últims immobles en cartera");
define("_NOVEMBER","Noviembre");
define("_NO_ACCOUNT","No hi ha clients");
define("_NO_AV_LG","Aquest contingut no està disponible en el idioma actual.");
define("_NO_COD","Codi es obligatori");
define("_NO_CONTACT","TO_TRANSLATE");
define("_NO_CTG","No hay familias");
define("_NO_EMPL","No hay empleados");
define("_NO_GALS","No hay galerias para la selección");
define("_NO_IMG_FRONT","La Galeria de imagenes no tiene establecida una imagen principal. La publicación de anuncios necesita la imagen principal.");
define("_NO_IMG_INT_1","No hay Imagen Interior 1");
define("_NO_IMG_INT_2","No hay Imagen Interior 2");
define("_NO_IMG_INT_3","No hay Imagen Interior 3");
define("_NO_IMG_PORT","No hay Imagen portada");
define("_NO_IMMO","No hi ha Immobles");
define("_NO_MAILING","No hi ha mailings");
define("_NO_MEMBERS","No tiene miembros en su equipo");
define("_NO_NOTS","No hi ha noticies");
define("_NO_ORGS","No hay organizaciones");
define("_NO_PRICE_LST","No hi ha llistes de preus");
define("_NO_PROD","No hay productos");
define("_NO_PSTS","No positions");
define("_NO_SEASONS","No hi ha temporades");
define("_NO_TICKET","TO_TRANSLATE");
define("_NUMORDER","Ordre");
define("_NUM_DORMITORIO","dormitori");
define("_NUM_DORMITORIOS","dormitoris");
define("_NUM_HITS","Pàgines Vistes");
define("_NUM_ORDER","Ordre Aparició");
define("_NUM_PARKING","plaça de parking");
define("_NUM_PARKINGS","plaçes de parking");
define("_NUM_ROBOTS","Buscadors");
define("_NUM_SENT","Enviaments realitzats");
define("_NUM_VISITS","Visites");
define("_NUM_WC","bany");
define("_NUM_WCS","Banys");
define("_OBSERV_LIST","Llista de valors observaciones lloguer vacances");
define("_OCTOBER","Octubre");
define("_OF","de");
define("_OFICINAS","Oficines");
define("_ONLOAD","TO_TRANSLATE");
define("_OPINION","Opinió d'aquesta web");
define("_OPTIONAL","(Opcional)");
define("_ORDER","Ordre");
define("_ORDERBY","Ordenar per");
define("_ORG","Organizació");
define("_ORG_HAS_SUBORG","El departamento tiene sub-departamento, elimine los sub-departamentos");
define("_ORG_LST","Estructura de la Organizació");
define("_OUTAPP","SORTIDA DE L'APLICACIÓ");
define("_PAGE","Pàgina");
define("_PAGO_MEN","Pagament mensual hipoteca");
define("_PAGS","Pàgines");
define("_PARAMS","Paràmetres");
define("_PARENTCTG_DCHILDREN","Error al eliminar familia. La familia tiene subfamilias, elimine primero las subfamilias");
define("_PASSWORD","Contrasenya");
define("_PATH_IMAGE","Imatge");
define("_PERMS","Role");
define("_PERMS_HAS_SCR","El perfil té pantalles assignades.");
define("_PICTURES","Fotos");
define("_PIEPAGINA","Powered by <a href=\"http://reos.elazos.com\">ReOS "._VERSION."</a> and released under the <a href=\"http://www.fsf.org/licensing/licenses/agpl-3.0.html\">GNU/AGPLv3 License.</a>");
define("_PLEASE_LOGIN","Si us plau, identifiquis amb el seu usuari i contrasenya");
define("_POBLACIONES","Activar Poblacions");
define("_POBS","Recerca per poblacions");
define("_POPHOST","TO_TRANSLATE");
define("_POPPASS","TO_TRANSLATE");
define("_POPUSER","TO_TRANSLATE");
define("_POSITION","Carreg");
define("_POS_IMG_PORT","Posición de la imagen en portada");
define("_PRECIO","Preu");
define("_PRECIO_ALQUILER","Preu Lloguer "._CURRENCY."");
define("_PRECIO_COMPRA","Preu Compra "._CURRENCY."");
define("_PREFERE","Preferencies");
define("_PREF_POBS","Poblacions Preferides");
define("_PREVIOUS","Anterior");
define("_PRE_VIVIE","Preu de la vivenda");
define("_PRICE_FROM","Preu desde");
define("_PRICE_MAX","Preu Màx. "._CURRENCY."");
define("_PRICE_MIN","Preu Mín. "._CURRENCY."");
define("_PRIORITY","TO_TRANSLATE");
define("_PROCESS_OK","Process executat correctamente");
define("_PRODS","Productos");
define("_PROFS","Rols / Perfils");
define("_PROP_ACCOUNT","Immobles del Client");
define("_PROV_NAME","Provincia");
define("_PRT_LAYOUT","ESTRUCTURA PAG. IMPRIMIR");
define("_PST_ELEMTS","El cargo tiene asignados elementos, elimine primero los elementos");
define("_PUBLI_YOUR","Publica la teva propietat");
define("_READMORE","Llegir més...");
define("_RECOM","Recomenats");
define("_REFERERS","Remitents");
define("_REF_IMMO","Referencia");
define("_REF_TICKET","TO_TRANSLATE");
define("_REGS_TXT","Para evitar que altres usuaris poguin registrar-lo,  rebrà un correu de confirmació amb les instruccions per a validar els seu registre. Mediante el envio de este formulario, vostè es registra a la zona de clients. Su correo electrónico será su identificador de usuario.");
define("_REGUSERS","Clients registrats a el bulleti de noticies");
define("_REM_CONFIRM","Comprova el teu correu electronic.");
define("_REM_TXT","T'enviarem les teves dades d'access (usuari i Password) al teu correu electronic.");
define("_REM_USR","No recordes les dades de accés ?");
define("_RESERVATION","Reserva");
define("_RESERV_CONFIRM","La seva reserva ha sigut confirmada.");
define("_RESTORE","Recuperar copia");
define("_RESULTS","Resultats de la recerca");
define("_RE_NEW_PASS","Reescriu la nova contrasenya");
define("_RE_PASSWORD","Reescriu la contrasenya");
define("_ROOT_DEPT","Departament Inicial");
define("_ROWS","Registres");
define("_SADAY","Ds");
define("_SATURDAY","Dissabte");
define("_SAT_DEPT","Atenció a Clients");
define("_SAVE","Guardar");
define("_SCREEN","Pantalla");
define("_SCREENS","Pantalles");
define("_SCREEN_HAS_VIEW","La pantalla té vistes assignades.");
define("_SDAY","Diu");
define("_SEARCH_TITLE","Recerca");
define("_SEASONS","Temporades per a lloguers de vacances");
define("_SEE2PRINT","Veure per a imprimir");
define("_SEE_CYRILIC","Veure idiomes cirilics");
define("_SEE_LATIN1","Veure idiomes Occidentals");
define("_SEGUROS","Seguros");
define("_SELECT","Seleccionar");
define("_SELECTED","Seleccionat");
define("_SELECTLANGUAGE","Idiomes disponibles");
define("_SEND_OUTLOOK","Enviar a Outlook");
define("_SEPTEMBER","Septiembre");
define("_SERVICES_LIST","LLista de valors serveis vacances");
define("_SET_ACTIVITIES","Activitats");
define("_SET_EQUIP","Equipament");
define("_SET_IMG_FRONT","Fer principal");
define("_SET_INTRO","Introducció");
define("_SET_OBSERV","Observacions");
define("_SET_PROPERTIES","Característiques");
define("_SET_SERVICES","Serveis");
define("_SHOW_GAL","Mostrar Galeria");
define("_SINFO","Solicitut d'Informació");
define("_SINFO_ADVERT","A través de la pàgina web no es recull cap dada personal sense el seu coneixement, ni se cedeixen a tercers.");
define("_SINFO_CONFIRM","Formulari de contacte enviat correctament.");
define("_SINFO_TXT","Enviï'ns les seves dades i ens posarem en contacte amb vostè");
define("_SLOGAN","Gestió Inmobiliaria");
define("_START","Inici");
define("_STATE","Estat");
define("_STATISTICS","Estadistiques d'access");
define("_SUBJECT","TO_TRANSLATE");
define("_SUBS","Registrat");
define("_SUBS_PHRASE","Reb les nostres novetats");
define("_SUBS_TXT","Para evitar que altres usuaris poguin registrar-lo,  rebrà un correu de confirmació amb les instruccions per a validar els seu registre. Mitjançant l'envio d'aquest formulari, vostè es registra al  servei de bolleti de noticies.");
define("_SUNDAY","Diumenge");
define("_SUPPORT","TO_TRANSLATE");
define("_TDAY","Dm");
define("_TEAM_ACCOUNTS","Clients del meu equip");
define("_TEAM_IMMOS","Immobles del meu equip");
define("_TEAM_TICKETS","TO_TRANSLATE");
define("_THDAY","Dj");
define("_THEMES","Themes");
define("_THOUSANDS_SEP",".");
define("_THUMB","Fotos");
define("_THURSDAY","Dijous");
define("_TICKETS","TO_TRANSLATE");
define("_TITLE_LOGIN","Area d'administració");
define("_TK_CTG_LST","TO_TRANSLATE");
define("_TOCLOSE","TO_TRANSLATE");
define("_TODO","Acción");
define("_TOEND","Acabar");
define("_TOTAL","Total");
define("_TOT_GST","Total despeses :");
define("_TOY_INTERES","Contactar aquest Immoble");
define("_TP_PRICE","Tipus Preu");
define("_TP_PROPIEDAD","Tipus d'immoble");
define("_TP_SDAYS","Tipus");
define("_TP_SEND","Tipus d'enviament");
define("_TP_SEND_TO","Enviar a");
define("_TP_SERVICIO","Operació");
define("_TP_STATE","Estat");
define("_TP_VAT","Tipus IVA %");
define("_TUESDAY","Dimarts");
define("_TXT_ADDRESS1","Direcció");
define("_TXT_AGE","Edat");
define("_TXT_ASUNT","Assumpte");
define("_TXT_COMMENT","Comentaris");
define("_TXT_COMO","Com ens vas conèixer?");
define("_TXT_CONTENT","Contingut");
define("_TXT_COUNTRY","País");
define("_TXT_CP","Codi postal");
define("_TXT_DESC","Descripció");
define("_TXT_EMAIL","Correu");
define("_TXT_EMAIL1","Correu");
define("_TXT_ES","Valors");
define("_TXT_FAX","Fax");
define("_TXT_MAILING","Mitjançant les campanyess de eMailing Vostè pot enviar masivament informació als seus clients registrats.");
define("_TXT_OBSRV","Descripció");
define("_TXT_POBLACION","Població");
define("_TXT_SEARCH","Textes de recerca");
define("_TXT_SIGN","TO_TRANSLATE");
define("_TXT_SUBJECT","Asumpte");
define("_TXT_TELF1","Telèfon");
define("_TXT_TELF2","Telèfono 2");
define("_TXT_TITLE","Títol");
define("_TXT_UNREG","Ha rebut aquest correu com a resultat de la seva inscripció voluntària a la nostra llista de distribució. Si no vol rebre més correus :");
define("_TXT_URL","Direcció Web");
define("_TXT_WEB","Web");
define("_TXT_ZONA","Zona");
define("_UMONTH","Mes");
define("_UNREG","Donar de baixa");
define("_UNTITLED","No definit");
define("_UPDATE","Actualizar");
define("_UPDATED","Modificació realizada correctament");
define("_USED_PROP","Immoble de segona mà");
define("_USER","Usuari");
define("_USERNAME","Usuario");
define("_USER_DELETED","Usuario eliminado correctamente");
define("_USER_HAS_PST","El usuario tiene un cargo asignado. Elimine primero el cargo en organizaciones");
define("_USER_INSERTED","Usuario añadido correctamente");
define("_USER_TYPE","Tipus");
define("_USR_BOOK_NOVALID","No hem pogut validar la seva reserva. ");
define("_USR_CONFIRM","S'ha confirmat el seu registre.");
define("_USR_NOCONFIRM","S'ha detectat un error en la seva confirmació de registre.");
define("_USR_NOUNREG","La seva inscripció no ha pogut ser validada per a donar-se de baixa. Posis en contacte amb Atenció a clients en cas de rebre més correus.");
define("_USR_UNREG","Ha sigut donat de baixa de la llista de distribucio de correos.");
define("_VALUE","TO_TRANSLATE");
define("_VERACCS","Cercar Clients");
define("_VERBOOKINGS","Cerca per disponibilitat ");
define("_VERCONFIG","Configuració de la plantilla");
define("_VERCOUNTRIES","Llistat Paisos/Ciutats ");
define("_VERGAL","Galeries de Fotos");
define("_VERHTML","Veure pagines");
define("_VERIMMO","Recerca d'immobles");
define("_VERINTROS","Valors intro de Oferta");
define("_VERLABELS","Textes de l'aplicació");
define("_VERMAILINGS","Campanyes de Mailing");
define("_VERNOT","Noticies i Events");
define("_VERORGS","Organizació");
define("_VERPERMS","Llista de Rols / Perfils");
define("_VERPOBS","Activar Poblacions");
define("_VERPRD","Productes");
define("_VERPREFS","App. Variables");
define("_VERPRICELST","Llistes de Preus");
define("_VERPRICEPRD","Productes i Preus");
define("_VERPROPER","Valors caracteristcas de Oferta");
define("_VERSCR","Llista de Pantalles");
define("_VERSEASONS","Llista de Temporades");
define("_VERTICKETS","TO_TRANSLATE");
define("_VERTKCTGS","TO_TRANSLATE");
define("_VERTKEMAILS","TO_TRANSLATE");
define("_VERUSERS","Llista d'Usuaris");
define("_VERVIEWS","TO_TRANSLATE");
define("_VER_PERFIL","Perfil de Compra");
define("_VIEW","Vista");
define("_VIEWED","Visualizats");
define("_VIEWS","Vistes");
define("_VIEWS_LST","Llista de Vistes");
define("_VIEW_FRONT_IN","Noticia");
define("_WANT_SELL","Vull Vendre");
define("_WANT_SELL_TXT","Consegeix per el seu habitatge el que realment val !");
define("_WDAY","Dim");
define("_WEDNESDAY","Miercoles");
define("_WORDS_TO_FIND","Cerca paraules");
define("_XMLNAV","XML Layout File");
define("_XMLOUTPUT","XML Output File");
define("_XMLPRT","XML Printing Layout File");
define("_XSLFILE"," XSL Transformation File");
define("_XSLPRT","XSL Printing Transformation File");
define("_YEAR","Any");
define("_YEARS","Anys");
define("_YOUR_LOAN","Calcula la teva hipoteca");
define("_ZIP_FILE","Fitxer ZIP");
?>