<?php
/**
 * ReOS is a vertical software for real estates.
 * Copyright 2010 IT ELAZOS S.L.
 *
 * This file is part of ReOS v2.x.x.
 *
 * ReOS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ReOS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with ReOS.  If not, see <http://www.gnu.org/licenses/>.
 **/


//File generated from a txt file at : Thu, 18 Feb 2010 12:02:08 +0100

define("_0","Нет");
define("_1","Да");
define("_ABOUTUS","О нас");
define("_ACCOUNTS","Счета");
define("_ACONSULTAR","  В соответствии с просьбой  ");
define("_ACTIVE","Активная");
define("_ACTIVE_ALL","Активный Все");
define("_ACTIVITIES_LIST","  Мероприятия Этикетки Список  ");
define("_ADD","Добавить");
define("_ADDIMG","Добавить изображение");
define("_ADDIMGNOT","Новости фото");
define("_ADDPOINT","Карты Google");
define("_ADDPRICELST","Добавить прайс-лист");
define("_ADDPRICEPRD","  Добавить продукции / Цена  ");
define("_ADDT_FILES","Дополнительные файлы");
define("_ADD_ACCOUNT","Добавить аккаунт");
define("_ADD_CITY","Добавить город");
define("_ADD_COMDAD","Добавить государство");
define("_ADD_CONTACT","  Добавить новые контакты  ");
define("_ADD_COUNTRY","Добавить Страна");
define("_ADD_CTG","Добавить категорию");
define("_ADD_DEPT","Добавить Департамента");
define("_ADD_GAL","Добавить в галерее");
define("_ADD_IMG_GAL","  Добавить изображение в галерею  ");
define("_ADD_IMMO","Добавить собственности");
define("_ADD_MAILING","Добавить Почтовый");
define("_ADD_NEW","Создать");
define("_ADD_PERFIL","  Добавить Покупка профиль  ");
define("_ADD_PERM","Добавить Роль / Анкета");
define("_ADD_PICTURE","Добавить изображение");
define("_ADD_POSITION","Добавить работник");
define("_ADD_PROD","Добавить продукт");
define("_ADD_PROV","Добавить Уезд");
define("_ADD_SCR","Добавить экрана");
define("_ADD_SDAY","Добавить Новые дни");
define("_ADD_SEASON","Добавить новый сезон");
define("_ADD_TICKET","Добавить билетов");
define("_ADD_TK_CTG","Добавить категорию");
define("_ADD_USER","Добавить пользователя");
define("_ADD_VAL","Добавить Значение");
define("_ADD_VIEW","Добавить Vista");
define("_ADD_ZONA","Новые зоны");
define("_ADMIN","Администрация");
define("_ALL_ACCOUNTS","Все аккаунты");
define("_ALL_IMMOS","Все свойства");
define("_ALL_NEWS","Все новости");
define("_ALL_TICKETS","Все билеты");
define("_ANY","Любой");
define("_APP_FILE","Fichero Aplicación");
define("_APRIL","Апрель");
define("_ASIGN_POB","Выберите нужный город");
define("_AUGUST","Август");
define("_AVG_DAY_HITS","  Среднесуточное Page Просмотров  ");
define("_AVG_DAY_ROBOTS","  Среднесуточное Поисковики  ");
define("_AVG_DAY_VISITS","  Среднесуточное Посещений  ");
define("_BACK","Назад");
define("_BACKUP","Резервное копирование");
define("_BOOK","Либро де Посещений");
define("_BOOKINGS","  Праздничная Аренда Бронирование  ");
define("_BOOKING_VALID","  Ваш заказ был отправлен. Вы получите подтверждение по  электронной почте.  ");
define("_BOOKVALID","Бронирование валидации");
define("_BOOK_ISVALID","  Ваш заказ был одобрен. Мы свяжемся с Вами для  подтверждения бронирования вам.  ");
define("_BOOK_TXT","  PUEDE dejar вс Опиньон rellenando эль formulario деле  окончательным. Muchas Gracias POR SU Участие.  ");
define("_BORRAR","Удалить");
define("_BUGGET","Bugget "._CURRENCY."");
define("_BUSY","Занятый");
define("_BUSYBOOKING","  Недвижимость резервируется для выбранных дат  ");
define("_BUYERS_ACCOUNTS","Поиск покупателей");
define("_BUY_GUIDE","Покупка руководства");
define("_CALC","Рассчитать");
define("_CALC_INM","Ипотечный расчет");
define("_CALC_LOAN_PAYMENTS","  Ипотечный Расчет платежей  ");
define("_CALENDAR","Повестка дня");
define("_CAPTCHA","Проверка слова");
define("_CATALOG","Рубрики");
define("_CHANGE_PASS","Сменить пароль");
define("_CHARSET","UTF-8");
define("_CMT_CSSFILE","Cascading Style Sheets");
define("_CMT_IMAG","  Фото И флэш менеджер файлов  ");
define("_CMT_XMLNAV","  XML файл, который определяет формат каждой странице.  ");
define("_CMT_XMLOUTPUT","  Файл порожденных применением в качестве вклада  Transfromation XSL файлов  ");
define("_CMT_XMLPRT","  XML файл, который определяет формат печати каждой  страницы.  ");
define("_CMT_XSLFILE","  XSL преобразование файлов - Материалы применение XML  выходного файла.  ");
define("_CMT_XSLPRT","  XSL преобразование файлов. Принимает в качестве вклада в  XML Применение выходного файла.  ");
define("_COD","Id");
define("_COD_CATEGORY","Категория кодекс");
define("_COD_LANG","Язык");
define("_COD_PRODUCT","Код продукта");
define("_COMDAD_NAME","TO_TRANSLATE");
define("_COMO","Нос conociste POR ...");
define("_COM_APER","Настройка комиссии");
define("_CONFIRM","  Подтверждение регистрации  ");
define("_CONNECTED_AS","  Зарегистрированный в качестве  ");
define("_CONTACTAR","Контактная информация");
define("_CONTACTS","Контакты");
define("_CONTENTS","Содержание");
define("_CPASS","Пароль");
define("_CSSCONFIG","CSS файлов");
define("_CSSFILE","CSS файлов");
define("_CSS_DELETED","CSS файл удален");
define("_CTG","Категория");
define("_CTGS","Семья");
define("_CTG_BELONGS","  Семья, которая принадлежит  ");
define("_CTG_HAS_PROD","  Категории продуктов, удаление продуктов до  ");
define("_CTG_NO_EXIST","Семья не существует");
define("_CTG_NO_NAME","  Категория название является обязательным  ");
define("_CURRENT_PASS","Текущий пароль");
define("_CUSTOMER","Учетная запись");
define("_CUSTZONE","Клиенты область");
define("_DATE","Свидание");
define("_DATEMP","Организация данных");
define("_DATETIME_SQL","'%m/%d/%Y - %H:%i'");
define("_DATE_FORMAT","d/m/Y");
define("_DATE_FT","Свидание");
define("_DATE_SQL","'%d/%m/%Y'");
define("_DATOS_PERS","Личные данные");
define("_DATPERS","Личные данные");
define("_DAY","День");
define("_DEACTIVE_ALL","Все Deactive");
define("_DECEMBER","Декабрь");
define("_DEC_POINT",",");
define("_DELETE","Удалить");
define("_DELETED","Удалено успешно");
define("_DEPT","Департамент");
define("_DEPTS","Департамент");
define("_DESC_CATEGORY","Описание");
define("_DESC_PROD","Описание");
define("_DO_CALC","Расчет Mortatge");
define("_DTL","Подробнее");
define("_DTL_ACCOUNT","  Информация об учетной записи  ");
define("_DTL_ACCPERFIL","  Покупатель информационного профиля  ");
define("_DTL_PROP","Недвижимость данных");
define("_DT_CREATE","Создано Дата");
define("_DT_END","Дата окончания");
define("_DT_SENT","Отправлено Дата");
define("_DT_START","Дата начала");
define("_DT_VAL","Срок действия");
define("_DT_VALID","Действителен до");
define("_EDIT","Изменить");
define("_EDTACC","Учетная запись");
define("_EDTCOMDAD","Изменить государство");
define("_EDTCONTACT","Контактная информация");
define("_EDTCOUNTRY","Страна");
define("_EDTCTG","Категория продуктов");
define("_EDTGAL","Галерея");
define("_EDTHIMMO","  Праздничная азмещение Свойства  ");
define("_EDTHTML","Редактировать страницу");
define("_EDTIMMO","Недвижимость");
define("_EDTIMMOGAL","  Недвижимость изображений  ");
define("_EDTLABEL","Редактировать метки");
define("_EDTLST","Значение");
define("_EDTMAILING","Почтовый Подробности");
define("_EDTMSG","Изменить сообщение");
define("_EDTORG","Департамент");
define("_EDTPERFIL","Покупатель профиль");
define("_EDTPERM","Анкета");
define("_EDTPOB","Изменить город");
define("_EDTPOSITION","Сотрудник Подробности");
define("_EDTPRD","Продукт");
define("_EDTPRDGAL","Изображения продуктов");
define("_EDTPREF","Изменить");
define("_EDTPRICELST","  Редактировать прайс-лист  ");
define("_EDTPRICEPRD","Изменение цен");
define("_EDTPROV","Изменить Уезд");
define("_EDTSCR","Экран");
define("_EDTSDAY","Дни И цены");
define("_EDTSEASON","Сезон Подробности");
define("_EDTTICKET","Редактировать билетов");
define("_EDTTKCTG","  Редактирование Категория  ");
define("_EDTTKEMAIL","  Шаблон электронного сообщения  ");
define("_EDTUSER","Пользователь");
define("_EDTVIEW","Vista");
define("_EDT_ACCOUNT","  Изменить учетную запись  ");
define("_EDT_CONTACT","Изменить контакт");
define("_EDT_CTG","Edir семьи");
define("_EDT_DEPT","Изменить Департамента");
define("_EDT_EMPL","Изменить работник");
define("_EDT_GAL","Изменить Галерея");
define("_EDT_IMMO","Изменить собственности");
define("_EDT_MAILING","Изменить Почтовый");
define("_EDT_NEW","Новые изменения");
define("_EDT_PERM","  Редактировать роль / Анкета  ");
define("_EDT_PROD","Изменить продукт");
define("_EDT_SCR","Редактировать экрана");
define("_EDT_USER","Изменить пользователя");
define("_EDT_VAL","Изменение стоимости");
define("_EDT_VIEW","Редактировать Vista");
define("_EMPL","Работник");
define("_EMPLES","Сотрудники");
define("_ENVIAR","Отправлять");
define("_EQUIP_LIST","  Оборудование праздника наем Список ярлыков  ");
define("_ERROR_CAPTCHA","Проверка слова проверки.  ");
define("_ERROR_CHECK_PSW","Ошибка проверки пароля");
define("_ERROR_CONTENT_MAILING","  Содержание является обязательным  ");
define("_ERROR_CURRENT_PSW","  Текущий пароль неправильный  ");
define("_ERROR_DATS","Ошибка accesing данных");
define("_ERROR_DELETE","Ошибка при удалении");
define("_ERROR_DIR_GAL","  Ошибка при создании Galerie в папках  ");
define("_ERROR_EMAIL_USER","  Электронная почта является обязательным  ");
define("_ERROR_ES_IN","  Необходимо ввести значение Испанский  ");
define("_ERROR_IN","Ошибка");
define("_ERROR_INSERT","Ошибка при вставке");
define("_ERROR_LAST_USER","  Вы не можете удалить последний пользователь организации  ");
define("_ERROR_NAME_MAILING","  Почтовый название является обязательным  ");
define("_ERROR_NAME_USER","  Полное наименование является обязательным  ");
define("_ERROR_NM","  Дебе introducir эль число  ");
define("_ERROR_NM_PROFILE","  Эль число Дебе TENER MÁS DE 5 carácteres  ");
define("_ERROR_NOPOB","Город не найден");
define("_ERROR_NUM_DOM","  Количество номеров является обязательным  ");
define("_ERROR_NUM_PARKING","  Введите число автостоянок  ");
define("_ERROR_NUM_WC","  Количество санузлов является обязательным  ");
define("_ERROR_OBSRV","  Дебе introducir ла Описание  ");
define("_ERROR_OPEN_DIR","  Папка не может быть открыта  ");
define("_ERROR_OPEN_FILE","  Ошибка при открытии файла  ");
define("_ERROR_PASSUSR_NULL","  Имя пользователя и пароль может быть пустым или иметь  значение  ");
define("_ERROR_PROCESS","Процесс вызвал ошибки");
define("_ERROR_PSW_ERROR","  Неправильный пароль! Введите пароль в оба поля  ");
define("_ERROR_PSW_NOSTR","  Пароль может содержать только Альфа Персонажи  ");
define("_ERROR_PSW_SHORT","  Пароль должен быть более 5 символов длиной  ");
define("_ERROR_PSW_USERNAME","  Пароль не может быть iqual по имени пользователя  ");
define("_ERROR_SUBJ_MAILING","  Тема является обязательным  ");
define("_ERROR_SUPERF","  Площадь участка в М2 или нулевым  ");
define("_ERROR_SUPERF_CONST","  Площадь в М2 или нулевым  ");
define("_ERROR_SUPERT","  Введите терраса площади или 0, если не существует  ");
define("_ERROR_TELF1_USER","Телефон обязателен");
define("_ERROR_TXT_CONTENT","  Дебе introducir El Mensaje.  ");
define("_ERROR_UPDATE","Ошибка при обновлении");
define("_ERROR_USNAME_EXIST","  Имя пользователя уже существует! Выбрать другого.  ");
define("_ERROR_USRNAME_EXISTS","  Пользователь уже существует!  ");
define("_ERROR_USRNAME_NOSTR","  Имя пользователя может содержать только Альфа Персонажи  ");
define("_ERROR_USRNAME_SHORT","  Имя пользователя должно быть более 5 символов длиной  ");
define("_ER_SELET_TBL","  Ошибка в таблице SELECT  ");
define("_FDAY","F");
define("_FEBRUARY","Февраль");
define("_FECHA_FT","Свидание");
define("_FG_HIDDEN","Скрыт");
define("_FG_PRIVATE","Личное сообщение");
define("_FIND","Поиск");
define("_FIND_BY_CITIES","Поиск по городу");
define("_FIND_BY_CRITERIA","Поиск по критериям");
define("_FIND_BY_TPPROP","Поиск недвижимости Тип");
define("_FINPAGINA","");
define("_FOLDER","Папка");
define("_FOUND","Всего найдено");
define("_FRIDAY","Пятница");
define("_FRONT","Главная");
define("_FULL_NAME","Фамилия, имя, отчество");
define("_GALLERIES","Фото галереи");
define("_GALLERY","Галерея");
define("_GALS","Фотогалереи");
define("_GAL_LST","Список галерей");
define("_GAST_GEST","  Расходы Агентства, нотариата, регистрации. <br/>  (Это зависит от менеджера) Минимум:  ");
define("_GENERAL_LAYOUT","ГЛАВНАЯ ФОРМА СТРАНИЦЫ");
define("_GEN_LANG","  Установка языка изменения  ");
define("_GESTLANGS","Языки Инструменты");
define("_GST_COMPRA","  Недвижимость покупка расходы  ");
define("_GST_HIPOT","Ипотечный расходы");
define("_GUIA","Руководство");
define("_HELP","Помощь");
define("_HOME","Дом");
define("_HOMEPG","Дом");
define("_HOUR","Время");
define("_IDIOMA","ru");
define("_ID_CATEGORY","  Идентификатор категории  ");
define("_ID_POSITION","Присвоить");
define("_ID_TICKET","Номер билета");
define("_IMAG","Фото И Flash файлов");
define("_IMG","Image");
define("_IMGCONFIG","Шаблон фото");
define("_IMGHOME","head.jpg");
define("_IMGS_NOT","Новые изображения");
define("_IMG_FILE_ERROR","  Имеет неправильный формат (Акценты, пробелов и т.д. ..)  или больше  ");
define("_IMG_FRONT","Главная Фото");
define("_IMG_INT_1","Внутри Image 1");
define("_IMG_INT_2","Внутри Image 2");
define("_IMG_INT_3","Внутри Image 3");
define("_IMG_PORT","Главная Фото");
define("_IMMO","Недвижимость данных");
define("_IMMOS","Свойства");
define("_IMP_ACTOS","  Налоговые зарегистрированных юридических сделок:  ");
define("_IMP_COMPRA","  Налоговые трансмишнз родовой или НДС  ");
define("_IMP_ENTR","Учитывая размер");
define("_IMP_SOL","Ипотечный Сумма");
define("_IND_ACTIVE","Активная");
define("_IND_MAILING","Почтовый");
define("_IND_OFERTA","Предложение");
define("_IND_PISCINA","Плавательный бассейн");
define("_INFOLEGAL","Правовая информация");
define("_INSERTED","Включить успешно");
define("_INSIDE","Внутри");
define("_INTROS_LIST","  Список Введение этикеток  ");
define("_INT_BANC","Банковские проценты");
define("_INT_CAPACITY","Вместимость чел");
define("_INT_PERS","Количество человек");
define("_INT_SUPERFICIE","Сюжет M2");
define("_INT_SUPERFICIE_CONST","Площадь M2");
define("_INT_TERRACE","Терраса M2");
define("_IN_NAME_ACCOUNT","  Название счета является обязательным  ");
define("_IN_NAME_GAL","  Галерея имя является обязательным  ");
define("_IN_NAME_IMMO","  Справка является обязательным  ");
define("_IN_NAME_ORG","  Организация / Департамент название является обязательным  ");
define("_IN_NOT_RESUM","Резюме обязательно");
define("_IN_NOT_TITLE","  Название является обязательным  ");
define("_IN_POB_IMMO","  Вы должны выбрать один город. Если нет в списке контакт  администратора  ");
define("_IN_POB_ORG","  Вы должны выбрать город  ");
define("_IN_SUBJECT","Введите тему");
define("_JANUARY","Январь");
define("_JULY","Июль");
define("_JUNE","Июнь");
define("_KEYWORDS_ADM","TO_TRANSLATE");
define("_LABELS_LIST","  Программа Этикетки Список  ");
define("_LANGS","Языки");
define("_LANGUAGE","Язык");
define("_LATTITUD","Lattitude");
define("_LBL_SEASONS","Сезон");
define("_LOGIN_FAILED","  Неправильное имя пользователя или пароль  ");
define("_LOGIN_NOW","Войти");
define("_LOGOUT","Выход");
define("_LONGITUD","Долгота");
define("_LOVS","Список значений");
define("_LSTMAILING","Списки");
define("_LSTUSER","Пользователь список");
define("_M2","M2");
define("_M2_TERRACE","М2 терраса");
define("_M2_TERRENO","Участок M2");
define("_MAILING","Почтовый кампании");
define("_MAIL_BKVALID","Проверка бронирования");
define("_MAIL_BKVALID_TXT","  Здравствуйте, Проверить ваш заказ по следующему адресу:  ");
define("_MAIL_CONFIRM","  Для подтверждения Вашей регистрации вы получите по  электронной почте.  ");
define("_MAIL_FORMAT","  Письмо в неверном формате;  ");
define("_MAIL_HRECEV","Мы получили ваш запрос");
define("_MAIL_NMSG","  Мы обработаем ваш запрос как можно скорее  ");
define("_MAIL_NOTI","Уведомления");
define("_MAIL_REM","Логин информации");
define("_MAIL_REM_TXT","  Здравствуйте, Ваш логин информации являются:  Подтверждение регистрации Здравствуйте,  ");
define("_MAIL_SUBS","  Registration confirmation  ");
define("_MAIL_SUBS_TXT","  Проверить вашу регистрацию по адресу: \"  ");
define("_MAIN_IMG","Главная Фото");
define("_MANDATORY","  Есть несколько обязательных полей  ");
define("_MAPINIT","  Первый Google Map Посмотреть  ");
define("_MARCH","Март");
define("_MAY","Мочь");
define("_MDAY","М");
define("_MKT","Рассылки");
define("_MNU_ADM","Меню");
define("_MONDAY","Понедельник");
define("_MONTH","Месяц");
define("_MSG","Сообщение");
define("_MY_ACCOUNTS","Мои счета");
define("_MY_IMMOS","Моя Свойства");
define("_MY_NEWS","Мои новости");
define("_MY_PROFILE","Мой профиль");
define("_MY_TICKETS","Мой билет");
define("_MY_TK_STATS","Моя статистика");
define("_NAME","Имя");
define("_NAME_ACCOUNT","Имя учетной записи");
define("_NAME_CATEGORY","Категория");
define("_NAME_GAL","Название галереи");
define("_NAME_MAILING","Почтовый Имя");
define("_NAME_ORG","Управление");
define("_NAME_POB","Город");
define("_NAME_POSITION","Должность");
define("_NAME_PRICE_LST","Название списка");
define("_NAME_PRODUCT","Название продукта");
define("_NAME_SEASONS","Сезон Имя");
define("_NAME_USER","  Работник / Имя пользователя  ");
define("_NESPECIAL","  Наше специальное предложение  ");
define("_NEW","Новый");
define("_NEWS","Новости");
define("_NEWSLST","Лента новостей");
define("_NEWS_EVENTS","Новости И События");
define("_NEWUSER","Новый пользователь");
define("_NEW_PASSWORD","Новый пароль");
define("_NEW_POS","Должность");
define("_NEW_PROP","  Brand New собственности  ");
define("_NEW_RESUM","Brieffing");
define("_NEW_TITLE","Название");
define("_NEW_TXT","Текст");
define("_NEXT","Следующий");
define("_NM_CONTACT","Контактное лицо");
define("_NM_PROFILE","Имя");
define("_NM_SCREEN","Экрана");
define("_NM_TK_CTG","Категория");
define("_NM_VIEW","Vista");
define("_NOREGUSERS","  Там нет счетов, зарегистрированных на рассылку  ");
define("_NOSELECTED","Невыбранные");
define("_NOTFOUND","Не найдено");
define("_NOTI","Новый");
define("_NOTICIA","Посмотреть новые");
define("_NOVED","Новые свойства");
define("_NOVED_TXT","Последний ....");
define("_NOVEMBER","Ноябрь");
define("_NO_ACCOUNT","  Учетные записи не найдено  ");
define("_NO_AV_LG","  Это содержание не avalaible в текущем языке  ");
define("_NO_COD","  Кодекс является обязательным  ");
define("_NO_CONTACT","Контакты не найдены");
define("_NO_CTG","Категории не найдены");
define("_NO_EMPL","Сотрудников не найдено");
define("_NO_GALS","Галереи не найдены");
define("_NO_IMG_FRONT","  Галерея не в основное изображение. Чтобы опубликовать  предлагает Вам нужно выбрать основное изображение.  ");
define("_NO_IMG_INT_1","Там нет Внутри Image 1");
define("_NO_IMG_INT_2","Там нет Image Внутри 2");
define("_NO_IMG_INT_3","Там нет Внутри Image 3");
define("_NO_IMG_PORT","  Там нет изображений Главная  ");
define("_NO_IMMO","Свойства не найден");
define("_NO_MAILING","Отправка не найден");
define("_NO_MEMBERS","  Вы не имеете членов вашей команды  ");
define("_NO_NOTS","Новости не найдены");
define("_NO_ORGS","Организаций не найдено");
define("_NO_PRICE_LST","Там нет прайс-листы");
define("_NO_PROD","Продукция не найдена");
define("_NO_PSTS","Нет позиции");
define("_NO_SEASONS","Нет сезонов");
define("_NO_TICKET","  NO SE хан encontrado билеты пункт ла выбор  ");
define("_NUMORDER","Ордена");
define("_NUM_DORMITORIO","Спальня");
define("_NUM_DORMITORIOS","спальни");
define("_NUM_HITS","Просмотры страниц");
define("_NUM_ORDER","Показать заказ");
define("_NUM_PARKING","Автомобильный парк");
define("_NUM_PARKINGS","Автомобильный парк");
define("_NUM_ROBOTS","Поисковики");
define("_NUM_SENT","Число родов");
define("_NUM_VISITS","Посещений");
define("_NUM_WC","ванная комната");
define("_NUM_WCS","Ванные");
define("_OBSERV_LIST","  Этикетки Список замечаний в отпуск на аренду  ");
define("_OCTOBER","Октябрь");
define("_OF","из");
define("_OFICINAS","Офисы");
define("_ONLOAD","Загрузить");
define("_OPINION","Опиньон интернет  ");
define("_OPTIONAL","(Необязательно)");
define("_ORDER","Заказ");
define("_ORDERBY","Сортировать по");
define("_ORG","Организация");
define("_ORG_HAS_SUBORG","  Департамент суб-департаментов, исключить подпункт  департаментов до  ");
define("_ORG_LST","Структура организации");
define("_OUTAPP","ПРИМЕНЕНИЕ OUTPUT");
define("_PAGE","Страница");
define("_PAGO_MEN","  Ежемесячный ипотечный платеж  ");
define("_PAGS","Страницы");
define("_PARAMS","Parámetros");
define("_PARENTCTG_DCHILDREN","  Категория имеет подкатегории исключить подкатегории до  ");
define("_PASSWORD","Пароль");
define("_PATH_IMAGE","Image");
define("_PERMS","Роль");
define("_PERMS_HAS_SCR","  Эль Perfil TIENE pantallas asignadas.  ");
define("_PICTURES","Фото");
define("_PIEPAGINA","Powered by <a href=\"http://reos.elazos.com\">ReOS "._VERSION."</a> and released under the <a href=\"http://www.fsf.org/licensing/licenses/agpl-3.0.html\">GNU/AGPLv3 License.</a>");
define("_PLEASE_LOGIN","  Введите имя пользователя и пароль  ");
define("_POBLACIONES","Активный Города");
define("_POBS","Поиск по городу");
define("_POPHOST","Почта пребывания");
define("_POPPASS","Pop3 Пароль");
define("_POPUSER","Pop3 пользователя");
define("_POSITION","Должность");
define("_POS_IMG_PORT","Первая позиция");
define("_PRECIO","Цена");
define("_PRECIO_ALQUILER","Аренда Цена "._CURRENCY."");
define("_PRECIO_COMPRA","Продажа Цена "._CURRENCY."");
define("_PREFERE","Предпочтения");
define("_PREF_POBS","Preffered Города");
define("_PREVIOUS","Предыдущая");
define("_PRE_VIVIE","Цена недвижимости");
define("_PRICE_FROM","Цена от");
define("_PRICE_MAX","Макс. Цена "._CURRENCY."");
define("_PRICE_MIN","Мин. Цена "._CURRENCY."");
define("_PRIORITY","Очередность");
define("_PROCESS_OK","  Процесс выполняется успешно  ");
define("_PRODS","Продукция");
define("_PROFS","Роли / Perfiles");
define("_PROP_ACCOUNT","Счета Свойства");
define("_PROV_NAME","Провинция");
define("_PRT_LAYOUT","  ПЕЧАТАНИЕ СХЕМА СТРАНИЦЫ  ");
define("_PST_ELEMTS","  Должность выделил элементы. Пожалуйста, прежде чем  удалить элементы  ");
define("_PUBLI_YOUR","  Опубликуйте вашу собственность  ");
define("_READMORE","Читать дальше ...");
define("_RECOM","Рекомендованная");
define("_REFERERS","Реферрала");
define("_REF_IMMO","Справка");
define("_REF_TICKET","Справка");
define("_REGS_TXT","  Чтобы избежать другие пользователи могут  зарегистрироваться, Вы будете получать по электронной  почте, чтобы подтвердить регистрацию. Через эту форму вы  регистрируетесь для клиента области. Ваше сообщение  будет вам имя пользователя.  ");
define("_REGUSERS","  Зарегистрирован счетов на рассылку  ");
define("_REM_CONFIRM","  Проверить электронную почту.  ");
define("_REM_TXT","  Мы вышлем вам регистрационную информацию на свой  электронный адрес.  ");
define("_REM_USR","Забыли пароль?");
define("_RESERVATION","Бронирование");
define("_RESERV_CONFIRM","  Ваш заказ был подтвержден.  ");
define("_RESTORE","Восстановить Backup");
define("_RESULTS","Результаты поиска");
define("_RE_NEW_PASS","Введите новый пароль");
define("_RE_PASSWORD","Введите пароль");
define("_ROOT_DEPT","  Первоначальный Департамента  ");
define("_ROWS","пунктов");
define("_SADAY","S");
define("_SATURDAY","Суббота");
define("_SAT_DEPT","Обслуживание клиентов");
define("_SAVE","Сохранить");
define("_SCREEN","Экрана");
define("_SCREENS","Pantallas");
define("_SCREEN_HAS_VIEW","  La экрана TIENE перспективы asignadas.  ");
define("_SDAY","S");
define("_SEARCH_TITLE","Поиск");
define("_SEASONS","  Сезон для отдыха аренда  ");
define("_SEE2PRINT","Версия для печати");
define("_SEE_CYRILIC","Показать Cyrilic Языки");
define("_SEE_LATIN1","  Показать Оксидентал Языки  ");
define("_SEGUROS","Страхование");
define("_SELECT","Выберите");
define("_SELECTED","выбранные");
define("_SELECTLANGUAGE","Изменить язык!");
define("_SEND_OUTLOOK","Отправить Outlook");
define("_SEPTEMBER","Сентябрь");
define("_SERVICES_LIST","Услуги Этикетки Список");
define("_SET_ACTIVITIES","Мероприятия");
define("_SET_EQUIP","Оборудование");
define("_SET_IMG_FRONT","Выберите основной");
define("_SET_INTRO","Введение");
define("_SET_OBSERV","Примечания");
define("_SET_PROPERTIES","Свойства");
define("_SET_SERVICES","Услуги");
define("_SHOW_GAL","Галерея");
define("_SINFO","Запрос информации");
define("_SINFO_ADVERT","  В общем, любой информации, которую Вы предоставляете,  будет использоваться только внутри этого участка. Он  никогда не будет поставляться никому за пределами этого  сайта без предварительного получения согласия  пользователя.  ");
define("_SINFO_CONFIRM","  Контактная форма отправлено успешно.  ");
define("_SINFO_TXT","  Просьба предоставить свои личные данные для связи с вами  как можно скорее.  ");
define("_SLOGAN","государственного управления  ");
define("_START","Дом");
define("_STATE","Статус");
define("_STATISTICS","Доступ к статистике");
define("_SUBJECT","Asunto");
define("_SUBS","Регистрация");
define("_SUBS_PHRASE","Получать наши новости");
define("_SUBS_TXT","  Чтобы избежать другие пользователи могут  зарегистрироваться, Вы будете получать по электронной  почте, чтобы подтвердить регистрацию. Через эту форму вы  регистрируетесь на информационный бюллетень.  ");
define("_SUNDAY","Воскресенье");
define("_SUPPORT","Поддержка");
define("_TDAY","Т");
define("_TEAM_ACCOUNTS","Наша команда счетам");
define("_TEAM_IMMOS","Наша команда Свойства");
define("_TEAM_TICKETS","  Билеты DE MI оборудование  ");
define("_THDAY","TH");
define("_THEMES","Темы");
define("_THOUSANDS_SEP",".");
define("_THUMB","Картинки");
define("_THURSDAY","Четверг");
define("_TICKETS","Билеты");
define("_TITLE_LOGIN","Администрация Района");
define("_TK_CTG_LST","Категория Список");
define("_TOCLOSE","Закрыть");
define("_TODO","Действий");
define("_TOEND","Готово");
define("_TOTAL","Всего");
define("_TOT_GST","Итого расходы:");
define("_TOY_INTERES","  Связаться с этим имуществом  ");
define("_TP_PRICE","Цена Тип");
define("_TP_PROPIEDAD","Тип недвижимости");
define("_TP_SDAYS","Печатать");
define("_TP_SEND","Отправка Тип");
define("_TP_SEND_TO","Отправить");
define("_TP_SERVICIO","Транзакция");
define("_TP_STATE","Статус");
define("_TP_VAT","НДС%");
define("_TUESDAY","Вторник");
define("_TXT_ADDRESS1","Адрес");
define("_TXT_AGE","Возраст");
define("_TXT_ASUNT","Тема");
define("_TXT_COMMENT","Комментарии");
define("_TXT_COMO","Как н.у.к. conociste?");
define("_TXT_CONTENT","Содержание");
define("_TXT_COUNTRY","Страна");
define("_TXT_CP","Почтовый индекс");
define("_TXT_DESC","Описание");
define("_TXT_EMAIL","Электронная почта");
define("_TXT_EMAIL1","Электронная почта");
define("_TXT_ES","Значения");
define("_TXT_FAX","Факс");
define("_TXT_MAILING","  Отправка всей кампании вы можете отправлять массовые  рассылки своим клиентам  ");
define("_TXT_OBSRV","Описание");
define("_TXT_POBLACION","Город");
define("_TXT_SEARCH","Поиск Струны");
define("_TXT_SIGN","Подпись");
define("_TXT_SUBJECT","Тема");
define("_TXT_TELF1","Номер телефона");
define("_TXT_TELF2","Телефон # 2");
define("_TXT_TITLE","Название");
define("_TXT_UNREG","  Вы получаете это сообщение, потому что вы добровольно  подписались на наши новости. Если вы не хотите получать  больше писем:  ");
define("_TXT_URL","Url");
define("_TXT_WEB","Веб");
define("_TXT_ZONA","Зона");
define("_UMONTH","Месяц");
define("_UNREG","Отписаться");
define("_UNTITLED","Untitled");
define("_UPDATE","Обновление");
define("_UPDATED","Обновлено успешно");
define("_USED_PROP","Б собственности");
define("_USER","Пользователь");
define("_USERNAME","Пользователь");
define("_USER_DELETED","  Пользователь успешно удален  ");
define("_USER_HAS_PST","  Пользователь может назначить. Исключить позиции до  ");
define("_USER_INSERTED","  Пользователь успешно добавлен  ");
define("_USER_TYPE","Печатать");
define("_USR_BOOK_NOVALID","  Мы не можем подтвердить ваш заказ.  ");
define("_USR_CONFIRM","  Ваша регистрация действительна.  ");
define("_USR_NOCONFIRM","  Ошибки, найденные при регистрации.  ");
define("_USR_NOUNREG","  Ваш отмену подписки не была подтверждена. Обратная связь  с клиентами, если вы получите больше писем.  ");
define("_USR_UNREG","  Ваш отмену подписки были обработаны.  ");
define("_VALUE","Значение");
define("_VERACCS","Счета Поиск");
define("_VERBOOKINGS","Наличие Поиск");
define("_VERCONFIG","Шаблон Конфигурация");
define("_VERCOUNTRIES","Страна / Город Список");
define("_VERGAL","Фотогалерея");
define("_VERHTML","Содержание");
define("_VERIMMO","Поиск недвижимости");
define("_VERINTROS","  Этикетка предложения Введение  ");
define("_VERLABELS","Применение Этикетки");
define("_VERMAILINGS","Почтовый кампании");
define("_VERNOT","Новости И События");
define("_VERORGS","Организация");
define("_VERPERMS","Список Роли / Perfiles");
define("_VERPOBS","Активный Города");
define("_VERPRD","Продукция");
define("_VERPREFS","Загруз. Переменные");
define("_VERPRICELST","Прайс-листы");
define("_VERPRICEPRD","Продукция И Цены");
define("_VERPROPER","  Этикетки предложения свойства  ");
define("_VERSCR","Список Pantallas");
define("_VERSEASONS","Сезон Список");
define("_VERTICKETS","Билеты");
define("_VERTKCTGS","Поддержка Категории");
define("_VERTKEMAILS","Email Шаблоны");
define("_VERUSERS","Список пользователей");
define("_VERVIEWS","Просмотров Список");
define("_VER_PERFIL","Покупатель профиль");
define("_VIEW","View");
define("_VIEWED","Просмотры");
define("_VIEWS","Vistas");
define("_VIEWS_LST","Список Vistas");
define("_VIEW_FRONT_IN","Новый");
define("_WANT_SELL","Я хочу продать");
define("_WANT_SELL_TXT","  Получите для вашего дома, какие затраты действительно  ");
define("_WDAY","W");
define("_WEDNESDAY","Среда");
define("_WORDS_TO_FIND","Поиск слов");
define("_XMLNAV","Макет XML файлов");
define("_XMLOUTPUT","Выходной файл XML");
define("_XMLPRT","  Печать макета XML файлов  ");
define("_XSLFILE","  XSL преобразование файлов  ");
define("_XSLPRT","  XSL преобразование Печать файлов  ");
define("_YEAR","Год");
define("_YEARS","Годы");
define("_YOUR_LOAN","Ваш кредит");
define("_ZIP_FILE","ZIP Файл");
?>