<?php
/**
 * ReOS is a vertical software for real estates.
 * Copyright 2010 IT ELAZOS S.L.
 *
 * This file is part of ReOS v2.x.x.
 *
 * ReOS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ReOS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with ReOS.  If not, see <http://www.gnu.org/licenses/>.
 **/


//File generated from a txt file at : Thu, 18 Feb 2010 12:02:08 +0100

define("_0","否");
define("_1","是");
define("_ABOUTUS","关于我们");
define("_ACCOUNTS","账户");
define("_ACONSULTAR","在要求中");
define("_ACTIVE","使用中");
define("_ACTIVE_ALL","TO_TRANSLATE");
define("_ACTIVITIES_LIST","活动标签列表");
define("_ADD","加入");
define("_ADDIMG","加入图像");
define("_ADDIMGNOT","新图像");
define("_ADDPOINT","Google Maps");
define("_ADDPRICELST","加添价格表");
define("_ADDPRICEPRD","加添产品和价格");
define("_ADDT_FILES","附加档案");
define("_ADD_ACCOUNT","加入账户");
define("_ADD_CITY","TO_TRANSLATE");
define("_ADD_COMDAD","TO_TRANSLATE");
define("_ADD_CONTACT","TO_TRANSLATE");
define("_ADD_COUNTRY","TO_TRANSLATE");
define("_ADD_CTG","加入目录");
define("_ADD_DEPT","加入部门");
define("_ADD_GAL","加入图库");
define("_ADD_IMG_GAL","加入图像到图库");
define("_ADD_IMMO","加入物业");
define("_ADD_MAILING","加上邮件");
define("_ADD_NEW","加入新闻");
define("_ADD_PERFIL","加入买家简介");
define("_ADD_PERM","加入角式 / 简介");
define("_ADD_PICTURE","加入图像");
define("_ADD_POSITION","加入雇员");
define("_ADD_PROD","加入产品");
define("_ADD_PROV","TO_TRANSLATE");
define("_ADD_SCR","加入Screen");
define("_ADD_SDAY","加入新日期");
define("_ADD_SEASON","加入新季节");
define("_ADD_TICKET","加入票据");
define("_ADD_TK_CTG","TO_TRANSLATE");
define("_ADD_USER","加入用户");
define("_ADD_VAL","加入价值");
define("_ADD_VIEW","加入View");
define("_ADD_ZONA","新地区");
define("_ADMIN","管理");
define("_ALL_ACCOUNTS","全部账户");
define("_ALL_IMMOS","全部物业");
define("_ALL_NEWS","全部新闻");
define("_ALL_TICKETS","全部票据");
define("_ANY","任何");
define("_APP_FILE","应用程序档案");
define("_APRIL","四月");
define("_ASIGN_POB","选择期望的城市");
define("_AUGUST","八月");
define("_AVG_DAY_HITS","平均每天访问次数");
define("_AVG_DAY_ROBOTS","平均每天用搜索器次数");
define("_AVG_DAY_VISITS","平均每天访问次数");
define("_BACK","返回");
define("_BACKUP","备份");
define("_BOOK","访问册子");
define("_BOOKINGS","TO_TRANSLATE");
define("_BOOKING_VALID","TO_TRANSLATE");
define("_BOOKVALID","TO_TRANSLATE");
define("_BOOK_ISVALID","TO_TRANSLATE");
define("_BOOK_TXT","用页尾部足标表格分享你的意见. 多谢你的提供.");
define("_BORRAR","删除");
define("_BUGGET","预算支出金额 "._CURRENCY."");
define("_BUSY","烦忙");
define("_BUSYBOOKING","TO_TRANSLATE");
define("_BUYERS_ACCOUNTS","搜寻买家");
define("_BUY_GUIDE","购物指南");
define("_CALC","计算");
define("_CALC_INM","按揭贷款计算");
define("_CALC_LOAN_PAYMENTS","按揭贷款付账计算");
define("_CALENDAR","日常事务");
define("_CAPTCHA","TO_TRANSLATE");
define("_CATALOG","目录");
define("_CHANGE_PASS","更改密码");
define("_CHARSET","UTF-8");
define("_CMT_CSSFILE","层迭样式表");
define("_CMT_IMAG","图像及闪客档案处理程序");
define("_CMT_XMLNAV","XML 档案用于规定各页的布局.");
define("_CMT_XMLOUTPUT","应用程序产生出来的档案,用作输入 XSL 转变档案");
define("_CMT_XMLPRT","XML 档案用于规定各打印页的布局.");
define("_CMT_XSLFILE","XSL 转变档案 - 输入应XML用程序的输出档案 .");
define("_CMT_XSLPRT","XSL 转变档案. 用于输入XML应用程序的输出档案.");
define("_COD","TO_TRANSLATE");
define("_COD_CATEGORY","目录编码");
define("_COD_LANG","语文");
define("_COD_PRODUCT","产品编码");
define("_COMDAD_NAME","TO_TRANSLATE");
define("_COMO","我会见你...");
define("_COM_APER","设定佣金");
define("_CONFIRM","验证登记");
define("_CONNECTED_AS","登录");
define("_CONTACTAR","接洽");
define("_CONTACTS","TO_TRANSLATE");
define("_CONTENTS","内容");
define("_CPASS","密码");
define("_CSSCONFIG","CSS 档案");
define("_CSSFILE","CSS 档案");
define("_CSS_DELETED","已删去CSS档案");
define("_CTG","目录");
define("_CTGS","家庭");
define("_CTG_BELONGS","所属家庭");
define("_CTG_HAS_PROD","目录内有产品,先删去 产品");
define("_CTG_NO_EXIST","不存在任何家庭");
define("_CTG_NO_NAME","目录是强制性必须提供的");
define("_CURRENT_PASS","目前使用的密码");
define("_CUSTOMER","账户");
define("_CUSTZONE","客户区");
define("_DATE","日期");
define("_DATEMP","机构资料");
define("_DATETIME_SQL","'%d/%m/%Y - %H:%i'");
define("_DATE_FORMAT","d/m/Y");
define("_DATE_FT","日期");
define("_DATE_SQL","'%d/%m/%Y'");
define("_DATOS_PERS","个人资料");
define("_DATPERS","个人资料");
define("_DAY","日");
define("_DEACTIVE_ALL","TO_TRANSLATE");
define("_DECEMBER","十二月");
define("_DEC_POINT",".");
define("_DELETE","删除");
define("_DELETED","已成功删除");
define("_DEPT","部门");
define("_DEPTS","部门");
define("_DESC_CATEGORY","说明");
define("_DESC_PROD","说明");
define("_DO_CALC","按揭贷款计算");
define("_DTL","TO_TRANSLATE");
define("_DTL_ACCOUNT","账户资料");
define("_DTL_ACCPERFIL","买家简介资料");
define("_DTL_PROP","物业资料");
define("_DT_CREATE","创建日期");
define("_DT_END","结束日期");
define("_DT_SENT","送出日期");
define("_DT_START","开始日期");
define("_DT_VAL","过期日子");
define("_DT_VALID","有效");
define("_EDIT","编改");
define("_EDTACC","账户");
define("_EDTCOMDAD","TO_TRANSLATE");
define("_EDTCONTACT","TO_TRANSLATE");
define("_EDTCOUNTRY","TO_TRANSLATE");
define("_EDTCTG","产品目录");
define("_EDTGAL","画廊");
define("_EDTHIMMO","假日寓所物业");
define("_EDTHTML","编改页");
define("_EDTIMMO","物业");
define("_EDTIMMOGAL","物业图像");
define("_EDTLABEL","TO_TRANSLATE");
define("_EDTLST","价值");
define("_EDTMAILING","邮件详述");
define("_EDTMSG","TO_TRANSLATE");
define("_EDTORG","部门");
define("_EDTPERFIL","买家简介");
define("_EDTPERM","简介");
define("_EDTPOB","TO_TRANSLATE");
define("_EDTPOSITION","雇员详细资料");
define("_EDTPRD","产品");
define("_EDTPRDGAL","物业图像");
define("_EDTPREF","TO_TRANSLATE");
define("_EDTPRICELST","编改价格表");
define("_EDTPRICEPRD","编改价格");
define("_EDTPROV","TO_TRANSLATE");
define("_EDTSCR","Screen");
define("_EDTSDAY","日子及价格");
define("_EDTSEASON","季节详情");
define("_EDTTICKET","编改票据");
define("_EDTTKCTG","TO_TRANSLATE");
define("_EDTTKEMAIL","TO_TRANSLATE");
define("_EDTUSER","用户");
define("_EDTVIEW","View");
define("_EDT_ACCOUNT","编改账户");
define("_EDT_CONTACT","TO_TRANSLATE");
define("_EDT_CTG","编改家庭");
define("_EDT_DEPT","编改部门");
define("_EDT_EMPL","编改雇员资料");
define("_EDT_GAL","编改图库");
define("_EDT_IMMO","编改物业");
define("_EDT_MAILING","编改邮件");
define("_EDT_NEW","编改新闻");
define("_EDT_PERM","编改角式 / 简介");
define("_EDT_PROD","编改产品");
define("_EDT_SCR","编改Screen");
define("_EDT_USER","编改用户");
define("_EDT_VAL","编改价值");
define("_EDT_VIEW","编改View");
define("_EMPL","雇员");
define("_EMPLES","TO_TRANSLATE");
define("_ENVIAR","发送");
define("_EQUIP_LIST","假日租赁器材用品卷标列表");
define("_ERROR_CAPTCHA","检查字词验证");
define("_ERROR_CHECK_PSW","密码错误");
define("_ERROR_CONTENT_MAILING","内容是强制性必须提供的");
define("_ERROR_CURRENT_PSW","目前密码是错误的");
define("_ERROR_DATS","取存数据错误");
define("_ERROR_DELETE","删除过程中出错");
define("_ERROR_DIR_GAL","创建图库目录过程中出错");
define("_ERROR_EMAIL_USER","邮电是强制性必须提供的");
define("_ERROR_ES_IN","你必须输入西班牙的值");
define("_ERROR_IN","错误了");
define("_ERROR_INSERT","加插数据过程中出错");
define("_ERROR_LAST_USER","你是不容许删除组织内最后一位用户的");
define("_ERROR_NAME_MAILING","邮件名称是强制性必须提供的");
define("_ERROR_NAME_USER","完整名称是强制性必须提供的");
define("_ERROR_NM","你必须输入名称");
define("_ERROR_NM_PROFILE","名称必须最少是六个字");
define("_ERROR_NOPOB","找不到任何城市");
define("_ERROR_NUM_DOM","房间数目是强制性必须提供的");
define("_ERROR_NUM_PARKING","输入停车位数量");
define("_ERROR_NUM_WC","沐浴室数目是强制性必须提供的");
define("_ERROR_OBSRV","你必须输入说明");
define("_ERROR_OPEN_DIR","打不开目录夹,");
define("_ERROR_OPEN_FILE","开启档案有错误");
define("_ERROR_PASSUSR_NULL","用户名称和密码可以是空白的或两者皆有值");
define("_ERROR_PROCESS","处理出现错误");
define("_ERROR_PSW_ERROR","密码错误 ! 在两空白字段内重新输入密码");
define("_ERROR_PSW_NOSTR","密码只可用英文字母");
define("_ERROR_PSW_SHORT","密码长度最少要六个字");
define("_ERROR_PSW_USERNAME","密码和用户名称不可以一致");
define("_ERROR_SUBJ_MAILING","主题是强制性必须提供的");
define("_ERROR_SUPERF","土地面绩 平米 或 零");
define("_ERROR_SUPERF_CONST","面绩 平米 或 零");
define("_ERROR_SUPERT","输入阳台面绩或 '0' ,如果没有阳台");
define("_ERROR_TELF1_USER","电话号码是强制性必须提供的");
define("_ERROR_TXT_CONTENT","你必须输入讯息.");
define("_ERROR_UPDATE","更新过程中出错");
define("_ERROR_USNAME_EXIST","用户名称己存在 ! 请另外再选其它用户名称.");
define("_ERROR_USRNAME_EXISTS","用户名称已存在 !");
define("_ERROR_USRNAME_NOSTR","用户名称只可用英文字母");
define("_ERROR_USRNAME_SHORT","使用者户名称长度最少要六个字");
define("_ER_SELET_TBL","选择数据表有错误");
define("_FDAY","F");
define("_FEBRUARY","二月");
define("_FECHA_FT","日期");
define("_FG_HIDDEN","TO_TRANSLATE");
define("_FG_PRIVATE","TO_TRANSLATE");
define("_FIND","搜寻");
define("_FIND_BY_CITIES","用城市名称搜索");
define("_FIND_BY_CRITERIA","标准搜索");
define("_FIND_BY_TPPROP","用物业类型搜索");
define("_FINPAGINA","");
define("_FOLDER","活页夹");
define("_FOUND","找寻到");
define("_FRIDAY","星期五");
define("_FRONT","首页");
define("_FULL_NAME","完整名称");
define("_GALLERIES","图像图库");
define("_GALLERY","图库");
define("_GALS","图库");
define("_GAL_LST","图库清单");
define("_GAST_GEST","代理支出, 公证行费用, 登记费用.<br/>(由经理人而定) 最低:");
define("_GENERAL_LAYOUT","主布局页");
define("_GEN_LANG","安装的语文已经改变");
define("_GESTLANGS","语文工具");
define("_GST_COMPRA","购买物业开支");
define("_GST_HIPOT","按揭贷款开支");
define("_GUIA","指南");
define("_HELP","说明");
define("_HOME","首页");
define("_HOMEPG","主页");
define("_HOUR","时间");
define("_IDIOMA","zh-cn");
define("_ID_CATEGORY","目录标记");
define("_ID_POSITION","指派给");
define("_ID_TICKET","票据卷标");
define("_IMAG","图像及闪支客档案");
define("_IMG","图像");
define("_IMGCONFIG","卷标图像");
define("_IMGHOME","head.jpg");
define("_IMGS_NOT","新的图像");
define("_IMG_FILE_ERROR","错误的格式 (重音符号, 空白, 等等...)  或大于");
define("_IMG_FRONT","首页图像");
define("_IMG_INT_1","内含图像 1");
define("_IMG_INT_2","内含图像 2");
define("_IMG_INT_3","内含图像 3");
define("_IMG_PORT","主题图像");
define("_IMMO","物业资料");
define("_IMMOS","物业");
define("_IMP_ACTOS","税务交易法定文件:");
define("_IMP_COMPRA","Tax Patrimonial Transmissions 或 加值税");
define("_IMP_ENTR","给出总额");
define("_IMP_SOL","按揭贷款账户");
define("_IND_ACTIVE","活跃");
define("_IND_MAILING","邮件");
define("_IND_OFERTA","提供");
define("_IND_PISCINA","泳池");
define("_INFOLEGAL","法律资料");
define("_INSERTED","加插资料成功");
define("_INSIDE","内含");
define("_INTROS_LIST","介绍标签列表");
define("_INT_BANC","银行利率");
define("_INT_CAPACITY","Capacity Pers");
define("_INT_PERS","TO_TRANSLATE");
define("_INT_SUPERFICIE","平米土地 ");
define("_INT_SUPERFICIE_CONST","面绩 平米");
define("_INT_TERRACE","平米阳台");
define("_IN_NAME_ACCOUNT","账户名称是强制性必须提供的");
define("_IN_NAME_GAL","图库名称是强制性必须提供的");
define("_IN_NAME_IMMO","参考是强制性必须提供的");
define("_IN_NAME_ORG","TO_TRANSLATE");
define("_IN_NOT_RESUM","摘要是强制性必须提供的");
define("_IN_NOT_TITLE","标题是强制性必须提供的");
define("_IN_POB_IMMO","你必须选择一城市. 如没有列出,请接洽管理员");
define("_IN_POB_ORG","你必须选择一城市");
define("_IN_SUBJECT","输入主题");
define("_JANUARY","一月");
define("_JULY","July");
define("_JUNE","六月");
define("_KEYWORDS_ADM","TO_TRANSLATE");
define("_LABELS_LIST","节目标签列表");
define("_LANGS","语文");
define("_LANGUAGE","语文");
define("_LATTITUD","TO_TRANSLATE");
define("_LBL_SEASONS","季节");
define("_LOGIN_FAILED","无效的使用者名称或密码");
define("_LOGIN_NOW","进入");
define("_LOGOUT","注销");
define("_LONGITUD","TO_TRANSLATE");
define("_LOVS","TO_TRANSLATE");
define("_LSTMAILING","收邮件客户列表");
define("_LSTUSER","用户清单");
define("_M2","M2");
define("_M2_TERRACE","平米阳台");
define("_M2_TERRENO","平米土地");
define("_MAILING","邮件活动");
define("_MAIL_BKVALID","TO_TRANSLATE");
define("_MAIL_BKVALID_TXT","TO_TRANSLATE");
define("_MAIL_CONFIRM","你会收到我们发出的邮电用于验证你的登记.");
define("_MAIL_FORMAT","邮电档案格式有错误");
define("_MAIL_HRECEV","我们己收到你的要求");
define("_MAIL_NMSG","我们会很快处理你的要求");
define("_MAIL_NOTI","收到确认通知");
define("_MAIL_REM","登入资料");
define("_MAIL_REM_TXT","你好, 

你登录的数据是 :");
define("_MAIL_SUBS","登记资料");
define("_MAIL_SUBS_TXT","你好, 

用给出的网址验证你的登记  :

");
define("_MAIN_IMG","主题图像");
define("_MANDATORY","TO_TRANSLATE");
define("_MAPINIT","TO_TRANSLATE");
define("_MARCH","三月");
define("_MAY","五月");
define("_MDAY","M");
define("_MKT","邮件");
define("_MNU_ADM","选单");
define("_MONDAY","星期一");
define("_MONTH","月");
define("_MSG","讯息");
define("_MY_ACCOUNTS","我的账户");
define("_MY_IMMOS","我的物业");
define("_MY_NEWS","我的新闻");
define("_MY_PROFILE","我的概况");
define("_MY_TICKETS","我的票据");
define("_MY_TK_STATS","TO_TRANSLATE");
define("_NAME","TO_TRANSLATE");
define("_NAME_ACCOUNT","账户名称");
define("_NAME_CATEGORY","目录");
define("_NAME_GAL","图库名称");
define("_NAME_MAILING","邮件名称");
define("_NAME_ORG","办公室");
define("_NAME_POB","城市");
define("_NAME_POSITION","职位");
define("_NAME_PRICE_LST","列表名称");
define("_NAME_PRODUCT","产品名称");
define("_NAME_SEASONS","季节名称");
define("_NAME_USER","雇员  / 用户名称");
define("_NESPECIAL","我们特别推荐");
define("_NEW","新");
define("_NEWS","新闻");
define("_NEWSLST","新闻列表");
define("_NEWS_EVENTS","新闻和活动");
define("_NEWUSER","新用户");
define("_NEW_PASSWORD","新密码");
define("_NEW_POS","在首页");
define("_NEW_PROP","全新物业");
define("_NEW_RESUM","简报");
define("_NEW_TITLE","标题");
define("_NEW_TXT","文字");
define("_NEXT","下一笔");
define("_NM_CONTACT","TO_TRANSLATE");
define("_NM_PROFILE","名称");
define("_NM_SCREEN","Screen");
define("_NM_TK_CTG","TO_TRANSLATE");
define("_NM_VIEW","View");
define("_NOREGUSERS","收邮件者清单中没有登记账户");
define("_NOSELECTED","未选中");
define("_NOTFOUND","TO_TRANSLATE");
define("_NOTI","新闻");
define("_NOTICIA","看新闻");
define("_NOVED","最新物业");
define("_NOVED_TXT","最新物业 ....");
define("_NOVEMBER","十一月");
define("_NO_ACCOUNT","找不到账户");
define("_NO_AV_LG","目前的语文不包含这页内容 ");
define("_NO_COD","编码是强制性必须提供的");
define("_NO_CONTACT","TO_TRANSLATE");
define("_NO_CTG","找不到任何目录");
define("_NO_EMPL","找不到任何雇员");
define("_NO_GALS","找不到任何图库");
define("_NO_IMG_FRONT","图库没有主题图像.你必须选择一主题图像,才可发行你的提供内容.");
define("_NO_IMG_INT_1","没有内含图像 1");
define("_NO_IMG_INT_2","没有内含图像 2");
define("_NO_IMG_INT_3","没有内含图像 3");
define("_NO_IMG_PORT","没有主题图像");
define("_NO_IMMO","找不到物业");
define("_NO_MAILING","找不到邮件");
define("_NO_MEMBERS","你的群组没有任何成员");
define("_NO_NOTS","没有新闻");
define("_NO_ORGS","找不到任何群组");
define("_NO_PRICE_LST","没有价格表");
define("_NO_PROD","找不到任何产品");
define("_NO_PSTS","没有职位");
define("_NO_SEASONS","无季节性");
define("_NO_TICKET","找不到票据");
define("_NUMORDER","顺序");
define("_NUM_DORMITORIO","睡房");
define("_NUM_DORMITORIOS","睡房");
define("_NUM_HITS","己阅读页数");
define("_NUM_ORDER","显示定单");
define("_NUM_PARKING","停车间");
define("_NUM_PARKINGS","停车位");
define("_NUM_ROBOTS","搜索器");
define("_NUM_SENT","送出次数");
define("_NUM_VISITS","访问");
define("_NUM_WC","沐浴室");
define("_NUM_WCS","沐浴室");
define("_OBSERV_LIST","假日租赁备忘标签列表");
define("_OCTOBER","十月");
define("_OF","于");
define("_OFICINAS","办公室");
define("_ONLOAD","TO_TRANSLATE");
define("_OPINION","分享你的意见");
define("_OPTIONAL","(备用)");
define("_ORDER","顺序");
define("_ORDERBY","顺序");
define("_ORG","组织");
define("_ORG_HAS_SUBORG","部门中拥有次部门, 请先删去次部门");
define("_ORG_LST","组织架构");
define("_OUTAPP","应用程序输出");
define("_PAGE","页");
define("_PAGO_MEN","每月还款");
define("_PAGS","页");
define("_PARAMS","参数");
define("_PARENTCTG_DCHILDREN","目录拥有次目录, 请先删去次目录");
define("_PASSWORD","密码");
define("_PATH_IMAGE","图像");
define("_PERMS","角式");
define("_PERMS_HAS_SCR","Profile has screens assigned.");
define("_PICTURES","图像");
define("_PIEPAGINA","Powered by <a href=\"http://reos.elazos.com\">ReOS "._VERSION."</a> and released under the <a href=\"http://www.fsf.org/licensing/licenses/agpl-3.0.html\">GNU/AGPLv3 License.</a>");
define("_PLEASE_LOGIN","输入你的使用者名称和密码");
define("_POBLACIONES","使用中的城市");
define("_POBS","用城市名搜索");
define("_POPHOST","TO_TRANSLATE");
define("_POPPASS","TO_TRANSLATE");
define("_POPUSER","TO_TRANSLATE");
define("_POSITION","职位");
define("_POS_IMG_PORT","首页位置");
define("_PRECIO","价格");
define("_PRECIO_ALQUILER","出租价格 "._CURRENCY."");
define("_PRECIO_COMPRA","出售价格 "._CURRENCY."");
define("_PREFERE","喜好");
define("_PREF_POBS","喜好的城市");
define("_PREVIOUS","前一笔");
define("_PRE_VIVIE","物业价格");
define("_PRICE_FROM","起始价格");
define("_PRICE_MAX","最高价格 "._CURRENCY."");
define("_PRICE_MIN","最低价格 "._CURRENCY."");
define("_PRIORITY","TO_TRANSLATE");
define("_PROCESS_OK","成功处理");
define("_PRODS","产品");
define("_PROFS","角式 / 简介");
define("_PROP_ACCOUNT","账户的物业");
define("_PROV_NAME","省份");
define("_PRT_LAYOUT","打印布局页");
define("_PST_ELEMTS","职位栏已有了内容. 请先删去内容");
define("_PUBLI_YOUR","发布你的物业");
define("_READMORE","阅读更多 ...");
define("_RECOM","推荐");
define("_REFERERS","推荐人");
define("_REF_IMMO","参考");
define("_REF_TICKET","TO_TRANSLATE");
define("_REGS_TXT","为了避免他用许户以你的名义登记,你将会收到我们发出的邮电用作确认登记.尽管你在客户区登记填表程交. 你的邮电将成为你的用户名称.");
define("_REGUSERS","把登记账户加入收邮件者清单");
define("_REM_CONFIRM","查看你的邮电.");
define("_REM_TXT","我们将会寄出你登录数据到你的邮电.");
define("_REM_USR","遗失了密码吗?");
define("_RESERVATION","TO_TRANSLATE");
define("_RESERV_CONFIRM","TO_TRANSLATE");
define("_RESTORE","还原备份");
define("_RESULTS","搜索结果");
define("_RE_NEW_PASS","从新输入新密码");
define("_RE_PASSWORD","从新输入密码");
define("_ROOT_DEPT","初设部门");
define("_ROWS","项目");
define("_SADAY","S");
define("_SATURDAY","星期六");
define("_SAT_DEPT","客户服务");
define("_SAVE","存档");
define("_SCREEN","Screen");
define("_SCREENS","Screens");
define("_SCREEN_HAS_VIEW","Screen has views assigned.");
define("_SDAY","S");
define("_SEARCH_TITLE","搜寻");
define("_SEASONS","假日租赁的季节");
define("_SEE2PRINT","打印");
define("_SEE_CYRILIC","顕示古代斯拉夫语字母");
define("_SEE_LATIN1","顕示欧美字母");
define("_SEGUROS","保险");
define("_SELECT","选择");
define("_SELECTED","选择");
define("_SELECTLANGUAGE","选择语文!");
define("_SEND_OUTLOOK","发送到Outlook");
define("_SEPTEMBER","九月");
define("_SERVICES_LIST","服务标签列表");
define("_SET_ACTIVITIES","活动");
define("_SET_EQUIP","器材");
define("_SET_IMG_FRONT","选择主题图像");
define("_SET_INTRO","引入介绍");
define("_SET_OBSERV","备忘录");
define("_SET_PROPERTIES","物业");
define("_SET_SERVICES","服务");
define("_SHOW_GAL","显示图库");
define("_SINFO","要求讯息");
define("_SINFO_ADVERT","一般常规, 任何你所提供的信息, 只用于此网站. 除非先得到你的同意,数据绝不会供给第三方作其它用途.");
define("_SINFO_CONFIRM","成功送出接洽窗体.");
define("_SINFO_TXT","请提供你个人的数据,我们将尽快和你联络.");
define("_SLOGAN","地产管理");
define("_START","主页");
define("_STATE","洲");
define("_STATISTICS","存取统计");
define("_SUBJECT","主旨");
define("_SUBS","登记");
define("_SUBS_PHRASE","订阅我们的新闻怏报");
define("_SUBS_TXT","为了避免其它用户以你的名义登记,你将会收到我们发出的邮电用作确认登记. 你凭借此登记表格订阅新闻快报.");
define("_SUNDAY","星期日");
define("_SUPPORT","支援");
define("_TDAY","T");
define("_TEAM_ACCOUNTS","我群组的账户");
define("_TEAM_IMMOS","我群组的物业");
define("_TEAM_TICKETS","我群组的票据");
define("_THDAY","TH");
define("_THEMES","TO_TRANSLATE");
define("_THOUSANDS_SEP",",");
define("_THUMB","照片");
define("_THURSDAY","星期四");
define("_TICKETS","票据");
define("_TITLE_LOGIN","管理员区");
define("_TK_CTG_LST","TO_TRANSLATE");
define("_TOCLOSE","TO_TRANSLATE");
define("_TODO","动作");
define("_TOEND","完结");
define("_TOTAL","总额");
define("_TOT_GST","开支总额 :");
define("_TOY_INTERES","接洽这物业的业主");
define("_TP_PRICE","价格种类");
define("_TP_PROPIEDAD","物业类型");
define("_TP_SDAYS","类型");
define("_TP_SEND","送出类型");
define("_TP_SEND_TO","送到");
define("_TP_SERVICIO","交易");
define("_TP_STATE","州");
define("_TP_VAT","加值税 %");
define("_TUESDAY","星期二");
define("_TXT_ADDRESS1","地址");
define("_TXT_AGE","年龄");
define("_TXT_ASUNT","主题");
define("_TXT_COMMENT","评语");
define("_TXT_COMO","你如何找到我们呢 ?");
define("_TXT_CONTENT","内容");
define("_TXT_COUNTRY","国家");
define("_TXT_CP","邮政区号");
define("_TXT_DESC","说明");
define("_TXT_EMAIL","邮电");
define("_TXT_EMAIL1","邮电");
define("_TXT_ES","价值");
define("_TXT_FAX","传真号码");
define("_TXT_MAILING","用邮件活动你可以向你的客户们发出大量的邮电");
define("_TXT_OBSRV","说明");
define("_TXT_POBLACION","城市");
define("_TXT_SEARCH","搜索字句");
define("_TXT_SIGN","TO_TRANSLATE");
define("_TXT_SUBJECT","主题");
define("_TXT_TELF1","电话号码");
define("_TXT_TELF2","电话号码 #2");
define("_TXT_TITLE"," 标题");
define("_TXT_UNREG","你收到此讯息因为你有意订阅我们的新闻邮件. 假如你不想再收到更多的邮电 :");
define("_TXT_URL","网址");
define("_TXT_WEB","网页");
define("_TXT_ZONA","地区");
define("_UMONTH","月");
define("_UNREG","终止订阅");
define("_UNTITLED","没有标题");
define("_UPDATE","更新");
define("_UPDATED","已成功更新");
define("_USED_PROP","二手物业");
define("_USER","用户");
define("_USERNAME","用户");
define("_USER_DELETED","已成功删去用户");
define("_USER_HAS_PST","用户已有了职位内容. 请先删去职位");
define("_USER_INSERTED","已成功加入用户");
define("_USER_TYPE","类型");
define("_USR_BOOK_NOVALID","TO_TRANSLATE");
define("_USR_CONFIRM","你的登记有效.");
define("_USR_NOCONFIRM","登记过程出错了.");
define("_USR_NOUNREG","你终止订阅的指示还没有经过验证. 如果你收到更多邮电,请跟客务部接洽.");
define("_USR_UNREG","你终止订阅的指示在处理中.");
define("_VALUE","TO_TRANSLATE");
define("_VERACCS","账户搜索");
define("_VERBOOKINGS","TO_TRANSLATE");
define("_VERCONFIG","卷标配置");
define("_VERCOUNTRIES","TO_TRANSLATE");
define("_VERGAL","画廊");
define("_VERHTML","内容");
define("_VERIMMO","搜索物业");
define("_VERINTROS","推介标签");
define("_VERLABELS","TO_TRANSLATE");
define("_VERMAILINGS","邮件活动");
define("_VERNOT","新闻及活动");
define("_VERORGS","组织");
define("_VERPERMS","角式列表 / 简介");
define("_VERPOBS","使用中的城市");
define("_VERPRD","产品");
define("_VERPREFS","TO_TRANSLATE");
define("_VERPRICELST","价格表");
define("_VERPRICEPRD","产品和价格");
define("_VERPROPER","推介物业标签");
define("_VERSCR","Screen清单t");
define("_VERSEASONS","季节列表");
define("_VERTICKETS","TO_TRANSLATE");
define("_VERTKCTGS","TO_TRANSLATE");
define("_VERTKEMAILS","TO_TRANSLATE");
define("_VERUSERS","用户名单");
define("_VERVIEWS","Views清单");
define("_VER_PERFIL","账户");
define("_VIEW","View");
define("_VIEWED","观看过");
define("_VIEWS","Views");
define("_VIEWS_LST","TO_TRANSLATE");
define("_VIEW_FRONT_IN","新");
define("_WANT_SELL","我想出售");
define("_WANT_SELL_TXT","获取你物业的真正市值");
define("_WDAY","W");
define("_WEDNESDAY","星期三");
define("_WORDS_TO_FIND","搜寻字句");
define("_XMLNAV","XML 布局档案");
define("_XMLOUTPUT","XML 输出档案");
define("_XMLPRT","XML 打印布局档案");
define("_XSLFILE","XSL 转变档案");
define("_XSLPRT","XSL 打印布局档案");
define("_YEAR","年");
define("_YEARS","年数");
define("_YOUR_LOAN","你的借贷");
define("_ZIP_FILE","ZIP压缩档案");
?>