<?php
/**
 * ReOS is a vertical software for real estates.
 * Copyright 2010 IT ELAZOS S.L.
 *
 * This file is part of ReOS v2.x.x.
 *
 * ReOS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ReOS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with ReOS.  If not, see <http://www.gnu.org/licenses/>.
 **/


//File generated from a txt file at : Thu, 18 Feb 2010 12:02:07 +0100

define("_0","Nein");
define("_1","Ja");
define("_ABOUTUS","Wer wir sind");
define("_ACCOUNTS","TO_TRANSLATE");
define("_ACONSULTAR","Nachfrage");
define("_ACTIVE","Aktiv");
define("_ACTIVE_ALL","TO_TRANSLATE");
define("_ACTIVITIES_LIST","TO_TRANSLATE");
define("_ADD","TO_TRANSLATE");
define("_ADDIMG","TO_TRANSLATE");
define("_ADDIMGNOT","TO_TRANSLATE");
define("_ADDPOINT","Google Maps");
define("_ADDPRICELST","TO_TRANSLATE");
define("_ADDPRICEPRD","TO_TRANSLATE");
define("_ADDT_FILES","TO_TRANSLATE");
define("_ADD_ACCOUNT","TO_TRANSLATE");
define("_ADD_CITY","TO_TRANSLATE");
define("_ADD_COMDAD","TO_TRANSLATE");
define("_ADD_CONTACT","TO_TRANSLATE");
define("_ADD_COUNTRY","TO_TRANSLATE");
define("_ADD_CTG","TO_TRANSLATE");
define("_ADD_DEPT","TO_TRANSLATE");
define("_ADD_GAL","TO_TRANSLATE");
define("_ADD_IMG_GAL","TO_TRANSLATE");
define("_ADD_IMMO","TO_TRANSLATE");
define("_ADD_MAILING","TO_TRANSLATE");
define("_ADD_NEW","TO_TRANSLATE");
define("_ADD_PERFIL","TO_TRANSLATE");
define("_ADD_PERM","TO_TRANSLATE");
define("_ADD_PICTURE","TO_TRANSLATE");
define("_ADD_POSITION","TO_TRANSLATE");
define("_ADD_PROD","TO_TRANSLATE");
define("_ADD_PROV","TO_TRANSLATE");
define("_ADD_SCR","TO_TRANSLATE");
define("_ADD_SDAY","TO_TRANSLATE");
define("_ADD_SEASON","TO_TRANSLATE");
define("_ADD_TICKET","TO_TRANSLATE");
define("_ADD_TK_CTG","TO_TRANSLATE");
define("_ADD_USER","TO_TRANSLATE");
define("_ADD_VAL","TO_TRANSLATE");
define("_ADD_VIEW","TO_TRANSLATE");
define("_ADD_ZONA","TO_TRANSLATE");
define("_ADMIN","TO_TRANSLATE");
define("_ALL_ACCOUNTS","TO_TRANSLATE");
define("_ALL_IMMOS","TO_TRANSLATE");
define("_ALL_NEWS","TO_TRANSLATE");
define("_ALL_TICKETS","TO_TRANSLATE");
define("_ANY","Egal");
define("_APP_FILE","TO_TRANSLATE");
define("_APRIL","April");
define("_ASIGN_POB","TO_TRANSLATE");
define("_AUGUST","August");
define("_AVG_DAY_HITS","TO_TRANSLATE");
define("_AVG_DAY_ROBOTS","TO_TRANSLATE");
define("_AVG_DAY_VISITS","TO_TRANSLATE");
define("_BACK","Zurück");
define("_BACKUP","TO_TRANSLATE");
define("_BOOK","TO_TRANSLATE");
define("_BOOKINGS","TO_TRANSLATE");
define("_BOOKING_VALID","TO_TRANSLATE");
define("_BOOKVALID","TO_TRANSLATE");
define("_BOOK_ISVALID","TO_TRANSLATE");
define("_BOOK_TXT","TO_TRANSLATE");
define("_BORRAR","Löschen");
define("_BUGGET","Voranschlag "._CURRENCY."");
define("_BUSY","Belegt");
define("_BUSYBOOKING","Property is booked for your selected dates");
define("_BUYERS_ACCOUNTS","TO_TRANSLATE");
define("_BUY_GUIDE","Leitfaden zum Kauf");
define("_CALC","Berechnen");
define("_CALC_INM","Berechnung der Hypothekenraten");
define("_CALC_LOAN_PAYMENTS","Berechnung der Hypothekenraten");
define("_CALENDAR","TO_TRANSLATE");
define("_CAPTCHA","TO_TRANSLATE");
define("_CATALOG","TO_TRANSLATE");
define("_CHANGE_PASS","Passwort ändern");
define("_CHARSET","UTF-8");
define("_CMT_CSSFILE","TO_TRANSLATE");
define("_CMT_IMAG","TO_TRANSLATE");
define("_CMT_XMLNAV","TO_TRANSLATE");
define("_CMT_XMLOUTPUT","TO_TRANSLATE");
define("_CMT_XMLPRT","TO_TRANSLATE");
define("_CMT_XSLFILE","TO_TRANSLATE");
define("_CMT_XSLPRT","TO_TRANSLATE");
define("_COD","TO_TRANSLATE");
define("_COD_CATEGORY","TO_TRANSLATE");
define("_COD_LANG","TO_TRANSLATE");
define("_COD_PRODUCT","TO_TRANSLATE");
define("_COMDAD_NAME","TO_TRANSLATE");
define("_COMO","TO_TRANSLATE");
define("_COM_APER","Bereitstellungsprovision");
define("_CONFIRM","Anmeldebestätigung");
define("_CONNECTED_AS","Angemeldet als");
define("_CONTACTAR","Kontakt");
define("_CONTACTS","TO_TRANSLATE");
define("_CONTENTS","TO_TRANSLATE");
define("_CPASS","TO_TRANSLATE");
define("_CSSCONFIG","TO_TRANSLATE");
define("_CSSFILE","TO_TRANSLATE");
define("_CSS_DELETED","TO_TRANSLATE");
define("_CTG","TO_TRANSLATE");
define("_CTGS","TO_TRANSLATE");
define("_CTG_BELONGS","TO_TRANSLATE");
define("_CTG_HAS_PROD","TO_TRANSLATE");
define("_CTG_NO_EXIST","TO_TRANSLATE");
define("_CTG_NO_NAME","TO_TRANSLATE");
define("_CURRENT_PASS","Aktuelles Passwort");
define("_CUSTOMER","Kunde");
define("_CUSTZONE","TO_TRANSLATE");
define("_DATE","TO_TRANSLATE");
define("_DATEMP","TO_TRANSLATE");
define("_DATETIME_SQL","'%d/%m/%Y - %H:%i'");
define("_DATE_FORMAT","d/m/Y");
define("_DATE_FT","Datum");
define("_DATE_SQL","'%d/%m/%Y'");
define("_DATOS_PERS","Persönliche Angaben");
define("_DATPERS","Persönliche Angaben");
define("_DAY","Tag");
define("_DEACTIVE_ALL","TO_TRANSLATE");
define("_DECEMBER","Dezember");
define("_DEC_POINT",",");
define("_DELETE","TO_TRANSLATE");
define("_DELETED","TO_TRANSLATE");
define("_DEPT","TO_TRANSLATE");
define("_DEPTS","TO_TRANSLATE");
define("_DESC_CATEGORY","TO_TRANSLATE");
define("_DESC_PROD","TO_TRANSLATE");
define("_DO_CALC","Berechnung der Hypothek");
define("_DTL","TO_TRANSLATE");
define("_DTL_ACCOUNT","TO_TRANSLATE");
define("_DTL_ACCPERFIL","TO_TRANSLATE");
define("_DTL_PROP","Angaben zur Immobilie");
define("_DT_CREATE","TO_TRANSLATE");
define("_DT_END","TO_TRANSLATE");
define("_DT_SENT","TO_TRANSLATE");
define("_DT_START","TO_TRANSLATE");
define("_DT_VAL","TO_TRANSLATE");
define("_DT_VALID","TO_TRANSLATE");
define("_EDIT","Bearbeiten");
define("_EDTACC","TO_TRANSLATE");
define("_EDTCOMDAD","TO_TRANSLATE");
define("_EDTCONTACT","TO_TRANSLATE");
define("_EDTCOUNTRY","TO_TRANSLATE");
define("_EDTCTG","TO_TRANSLATE");
define("_EDTGAL","Galerie");
define("_EDTHIMMO","TO_TRANSLATE");
define("_EDTHTML","TO_TRANSLATE");
define("_EDTIMMO","Immobilie");
define("_EDTIMMOGAL","TO_TRANSLATE");
define("_EDTLABEL","TO_TRANSLATE");
define("_EDTLST","TO_TRANSLATE");
define("_EDTMAILING","TO_TRANSLATE");
define("_EDTMSG","TO_TRANSLATE");
define("_EDTORG","TO_TRANSLATE");
define("_EDTPERFIL","TO_TRANSLATE");
define("_EDTPERM","TO_TRANSLATE");
define("_EDTPOB","TO_TRANSLATE");
define("_EDTPOSITION","TO_TRANSLATE");
define("_EDTPRD","TO_TRANSLATE");
define("_EDTPRDGAL","TO_TRANSLATE");
define("_EDTPREF","TO_TRANSLATE");
define("_EDTPRICELST","TO_TRANSLATE");
define("_EDTPRICEPRD","TO_TRANSLATE");
define("_EDTPROV","TO_TRANSLATE");
define("_EDTSCR","TO_TRANSLATE");
define("_EDTSDAY","TO_TRANSLATE");
define("_EDTSEASON","TO_TRANSLATE");
define("_EDTTICKET","TO_TRANSLATE");
define("_EDTTKCTG","TO_TRANSLATE");
define("_EDTTKEMAIL","TO_TRANSLATE");
define("_EDTUSER","TO_TRANSLATE");
define("_EDTVIEW","TO_TRANSLATE");
define("_EDT_ACCOUNT","Kunden bearbeiten");
define("_EDT_CONTACT","TO_TRANSLATE");
define("_EDT_CTG","TO_TRANSLATE");
define("_EDT_DEPT","TO_TRANSLATE");
define("_EDT_EMPL","TO_TRANSLATE");
define("_EDT_GAL","TO_TRANSLATE");
define("_EDT_IMMO","TO_TRANSLATE");
define("_EDT_MAILING","TO_TRANSLATE");
define("_EDT_NEW","TO_TRANSLATE");
define("_EDT_PERM","TO_TRANSLATE");
define("_EDT_PROD","TO_TRANSLATE");
define("_EDT_SCR","TO_TRANSLATE");
define("_EDT_USER","TO_TRANSLATE");
define("_EDT_VAL","TO_TRANSLATE");
define("_EDT_VIEW","TO_TRANSLATE");
define("_EMPL","TO_TRANSLATE");
define("_EMPLES","TO_TRANSLATE");
define("_ENVIAR","Absenden");
define("_EQUIP_LIST","TO_TRANSLATE");
define("_ERROR_CAPTCHA","Check Wortbestätigung.");
define("_ERROR_CHECK_PSW","TO_TRANSLATE");
define("_ERROR_CONTENT_MAILING","TO_TRANSLATE");
define("_ERROR_CURRENT_PSW","Das aktuelle Passwort ist ungültig");
define("_ERROR_DATS","TO_TRANSLATE");
define("_ERROR_DELETE","TO_TRANSLATE");
define("_ERROR_DIR_GAL","TO_TRANSLATE");
define("_ERROR_EMAIL_USER","Sie müssen eine E-Mail-Adresse eingeben");
define("_ERROR_ES_IN","TO_TRANSLATE");
define("_ERROR_IN","TO_TRANSLATE");
define("_ERROR_INSERT","TO_TRANSLATE");
define("_ERROR_LAST_USER","TO_TRANSLATE");
define("_ERROR_NAME_MAILING","TO_TRANSLATE");
define("_ERROR_NAME_USER","Der Name muss vollständig angegeben werden");
define("_ERROR_NM","TO_TRANSLATE");
define("_ERROR_NM_PROFILE","TO_TRANSLATE");
define("_ERROR_NOPOB","TO_TRANSLATE");
define("_ERROR_NUM_DOM","Geben Sie die Zimmeranzahl ein");
define("_ERROR_NUM_PARKING","TO_TRANSLATE");
define("_ERROR_NUM_WC","TO_TRANSLATE");
define("_ERROR_OBSRV","TO_TRANSLATE");
define("_ERROR_OPEN_DIR","TO_TRANSLATE");
define("_ERROR_OPEN_FILE","TO_TRANSLATE");
define("_ERROR_PASSUSR_NULL","Der Benutzername und das Passwort müssen entweder beide leer sein oder beide Zeichen enthalten");
define("_ERROR_PROCESS","TO_TRANSLATE");
define("_ERROR_PSW_ERROR","Das Passwort wurde falsch eingegeben; bitte geben Sie es erneut in beiden Feldern ein");
define("_ERROR_PSW_NOSTR","Das Passwort darf nur Buchstaben und Zahlen, jedoch keine Leerzeichen enthalten");
define("_ERROR_PSW_SHORT","Das Passwort muss aus mindestens 5 Zeichen bestehen");
define("_ERROR_PSW_USERNAME","Der Benutzername darf nicht als Passwort verwendet werden");
define("_ERROR_SUBJ_MAILING","TO_TRANSLATE");
define("_ERROR_SUPERF","TO_TRANSLATE");
define("_ERROR_SUPERF_CONST","TO_TRANSLATE");
define("_ERROR_SUPERT","TO_TRANSLATE");
define("_ERROR_TELF1_USER","Sie müssen eine Telefonnummer eingeben");
define("_ERROR_TXT_CONTENT","TO_TRANSLATE");
define("_ERROR_UPDATE","TO_TRANSLATE");
define("_ERROR_USNAME_EXIST","Der Benutzername ist bereits belegt, bitte wählen Sie einen anderen");
define("_ERROR_USRNAME_EXISTS","Der Benutzername ist bereits belegt.");
define("_ERROR_USRNAME_NOSTR","Der Benutzername darf nur Buchstaben und Zahlen, jedoch keine Leerzeichen enthalten");
define("_ERROR_USRNAME_SHORT","Der Benutzername muss aus mindestens 5 Zeichen bestehen");
define("_ER_SELET_TBL","TO_TRANSLATE");
define("_FDAY","Fr");
define("_FEBRUARY","Februar");
define("_FECHA_FT","Datum");
define("_FG_HIDDEN","TO_TRANSLATE");
define("_FG_PRIVATE","TO_TRANSLATE");
define("_FIND","Suchen");
define("_FIND_BY_CITIES","Suche nach Ort");
define("_FIND_BY_CRITERIA","Suche nach Kriterien");
define("_FIND_BY_TPPROP","Suche nach Immobilientyp");
define("_FINPAGINA","");
define("_FOLDER","TO_TRANSLATE");
define("_FOUND","Suchergebnisse insgesamt");
define("_FRIDAY","Freitag");
define("_FRONT","Titelseite");
define("_FULL_NAME","Vollständiger Name");
define("_GALLERIES","TO_TRANSLATE");
define("_GALLERY","TO_TRANSLATE");
define("_GALS","TO_TRANSLATE");
define("_GAL_LST","TO_TRANSLATE");
define("_GAST_GEST","Ausgaben für Agentur für Verwaltungsformalitäten, Notar, Eintragung. <br/> (Abhängig von der Agentur) Mindestens:");
define("_GENERAL_LAYOUT","TO_TRANSLATE");
define("_GEN_LANG","TO_TRANSLATE");
define("_GESTLANGS","TO_TRANSLATE");
define("_GST_COMPRA","Ausgaben beim Wohnungskauf");
define("_GST_HIPOT","Hypotheken-Kosten");
define("_GUIA","Leitfaden");
define("_HELP","Hilfe");
define("_HOME","Home");
define("_HOMEPG","Home");
define("_HOUR","Uhrzeit");
define("_IDIOMA","de");
define("_ID_CATEGORY","TO_TRANSLATE");
define("_ID_POSITION","Zugewiesen für");
define("_ID_TICKET","TO_TRANSLATE");
define("_IMAG","TO_TRANSLATE");
define("_IMG","Foto");
define("_IMGCONFIG","TO_TRANSLATE");
define("_IMGHOME","head.jpg");
define("_IMGS_NOT","TO_TRANSLATE");
define("_IMG_FILE_ERROR","TO_TRANSLATE");
define("_IMG_FRONT","TO_TRANSLATE");
define("_IMG_INT_1","TO_TRANSLATE");
define("_IMG_INT_2","TO_TRANSLATE");
define("_IMG_INT_3","TO_TRANSLATE");
define("_IMG_PORT","TO_TRANSLATE");
define("_IMMO","Angaben zur Immobilie");
define("_IMMOS","Immobilien");
define("_IMP_ACTOS","Beurkundungssteuer");
define("_IMP_COMPRA","Grunderwerbssteuer (gebraucht) oder MwSt. (neu)");
define("_IMP_ENTR","Anzahlungsbetrag");
define("_IMP_SOL","Hypotheken-Betrag");
define("_IND_ACTIVE","TO_TRANSLATE");
define("_IND_MAILING","TO_TRANSLATE");
define("_IND_OFERTA","Angebot");
define("_IND_PISCINA","Swimmingpool");
define("_INFOLEGAL","Rechtshinweis");
define("_INSERTED","TO_TRANSLATE");
define("_INSIDE","Innen");
define("_INTROS_LIST","TO_TRANSLATE");
define("_INT_BANC","Bankzinsen");
define("_INT_CAPACITY","Kapazität Pers.");
define("_INT_PERS","TO_TRANSLATE");
define("_INT_SUPERFICIE","Grundstück M2");
define("_INT_SUPERFICIE_CONST","Fläche M2");
define("_INT_TERRACE","Terrasse M2");
define("_IN_NAME_ACCOUNT","Der Kundenname muss angegeben werden");
define("_IN_NAME_GAL","TO_TRANSLATE");
define("_IN_NAME_IMMO","TO_TRANSLATE");
define("_IN_NAME_ORG","TO_TRANSLATE");
define("_IN_NOT_RESUM","TO_TRANSLATE");
define("_IN_NOT_TITLE","TO_TRANSLATE");
define("_IN_POB_IMMO","TO_TRANSLATE");
define("_IN_POB_ORG","TO_TRANSLATE");
define("_IN_SUBJECT","Geben Sie einen Betreff ein");
define("_JANUARY","Januar");
define("_JULY","Juli");
define("_JUNE","Juni");
define("_KEYWORDS_ADM","TO_TRANSLATE");
define("_LABELS_LIST","TO_TRANSLATE");
define("_LANGS","TO_TRANSLATE");
define("_LANGUAGE","Sprache");
define("_LATTITUD","TO_TRANSLATE");
define("_LBL_SEASONS","TO_TRANSLATE");
define("_LOGIN_FAILED","Ihr Benutzername oder Passwort sind nicht korrekt.");
define("_LOGIN_NOW","Öffnen");
define("_LOGOUT","Logout");
define("_LONGITUD","TO_TRANSLATE");
define("_LOVS","TO_TRANSLATE");
define("_LSTMAILING","TO_TRANSLATE");
define("_LSTUSER","TO_TRANSLATE");
define("_M2","M2");
define("_M2_TERRACE","M2 Terrasse");
define("_M2_TERRENO","M2 Grundstück");
define("_MAILING","TO_TRANSLATE");
define("_MAIL_BKVALID","TO_TRANSLATE");
define("_MAIL_BKVALID_TXT","TO_TRANSLATE");
define("_MAIL_CONFIRM","Ihre Anmeldung wurde bearbeitet. In Kürze erhalten Sie eine E-Mail, um Ihre Anmeldung zu bestätigen.");
define("_MAIL_FORMAT","Ungültiges Format der E-Mail-Adresse");
define("_MAIL_HRECEV","Wir haben Ihre Anfrage erhalten.");
define("_MAIL_NMSG","Wir werden sie in Kürze bearbeiten.");
define("_MAIL_NOTI","Empfangsbestätigung");
define("_MAIL_REM","TO_TRANSLATE");
define("_MAIL_REM_TXT","TO_TRANSLATE");
define("_MAIL_SUBS","Anmeldebestätigung");
define("_MAIL_SUBS_TXT","Sehr geehrte/r Frau/Herr, 

Um Ihre Anmeldung zu bestätigen und auf die Leistungen zugreifen zu können, müssen Sie den folgenden Link betätigen:

");
define("_MAIN_IMG","TO_TRANSLATE");
define("_MANDATORY","TO_TRANSLATE");
define("_MAPINIT","TO_TRANSLATE");
define("_MARCH","März");
define("_MAY","Mai");
define("_MDAY","Mo");
define("_MKT","Mailings");
define("_MNU_ADM","Menü");
define("_MONDAY","Montag");
define("_MONTH","TO_TRANSLATE");
define("_MSG","Nachricht");
define("_MY_ACCOUNTS","TO_TRANSLATE");
define("_MY_IMMOS","TO_TRANSLATE");
define("_MY_NEWS","TO_TRANSLATE");
define("_MY_PROFILE","Mein Profil");
define("_MY_TICKETS","TO_TRANSLATE");
define("_MY_TK_STATS","TO_TRANSLATE");
define("_NAME","TO_TRANSLATE");
define("_NAME_ACCOUNT","Name des Kunden");
define("_NAME_CATEGORY","TO_TRANSLATE");
define("_NAME_GAL","TO_TRANSLATE");
define("_NAME_MAILING","TO_TRANSLATE");
define("_NAME_ORG","Büro");
define("_NAME_POB","TO_TRANSLATE");
define("_NAME_POSITION","TO_TRANSLATE");
define("_NAME_PRICE_LST","TO_TRANSLATE");
define("_NAME_PRODUCT","TO_TRANSLATE");
define("_NAME_SEASONS","TO_TRANSLATE");
define("_NAME_USER","TO_TRANSLATE");
define("_NESPECIAL","Unser Spezialangebot");
define("_NEW","Neuigkeit");
define("_NEWS","News");
define("_NEWSLST","TO_TRANSLATE");
define("_NEWS_EVENTS","News und Events");
define("_NEWUSER","Neuer Benutzer");
define("_NEW_PASSWORD","Neues Passwort");
define("_NEW_POS","Auf der Titelseite");
define("_NEW_PROP","Neue Wohnung");
define("_NEW_RESUM","Resümee");
define("_NEW_TITLE","TO_TRANSLATE");
define("_NEW_TXT","Text");
define("_NEXT","Nächste");
define("_NM_CONTACT","TO_TRANSLATE");
define("_NM_PROFILE","TO_TRANSLATE");
define("_NM_SCREEN","TO_TRANSLATE");
define("_NM_TK_CTG","TO_TRANSLATE");
define("_NM_VIEW","TO_TRANSLATE");
define("_NOREGUSERS","TO_TRANSLATE");
define("_NOSELECTED","Unselected");
define("_NOTFOUND","TO_TRANSLATE");
define("_NOTI","TO_TRANSLATE");
define("_NOTICIA","Neuigkeit anzeigen");
define("_NOVED","Neuheiten");
define("_NOVED_TXT","Die letzten verfügbaren Immobilien");
define("_NOVEMBER","November");
define("_NO_ACCOUNT","TO_TRANSLATE");
define("_NO_AV_LG","Dieser Inhalt ist nicht in dieser Sprache verfügbar.");
define("_NO_COD","TO_TRANSLATE");
define("_NO_CONTACT","TO_TRANSLATE");
define("_NO_CTG","TO_TRANSLATE");
define("_NO_EMPL","TO_TRANSLATE");
define("_NO_GALS","TO_TRANSLATE");
define("_NO_IMG_FRONT","TO_TRANSLATE");
define("_NO_IMG_INT_1","TO_TRANSLATE");
define("_NO_IMG_INT_2","TO_TRANSLATE");
define("_NO_IMG_INT_3","TO_TRANSLATE");
define("_NO_IMG_PORT","TO_TRANSLATE");
define("_NO_IMMO","Für die Auswahl wurden keine Immobilien gefunden");
define("_NO_MAILING","TO_TRANSLATE");
define("_NO_MEMBERS","TO_TRANSLATE");
define("_NO_NOTS","TO_TRANSLATE");
define("_NO_ORGS","TO_TRANSLATE");
define("_NO_PRICE_LST","TO_TRANSLATE");
define("_NO_PROD","TO_TRANSLATE");
define("_NO_PSTS","TO_TRANSLATE");
define("_NO_SEASONS","TO_TRANSLATE");
define("_NO_TICKET","TO_TRANSLATE");
define("_NUMORDER","TO_TRANSLATE");
define("_NUM_DORMITORIO","Schlafzimmer");
define("_NUM_DORMITORIOS","Zimmers");
define("_NUM_HITS","TO_TRANSLATE");
define("_NUM_ORDER","TO_TRANSLATE");
define("_NUM_PARKING","Autostellplatz");
define("_NUM_PARKINGS","Autostellplätze");
define("_NUM_ROBOTS","TO_TRANSLATE");
define("_NUM_SENT","TO_TRANSLATE");
define("_NUM_VISITS","TO_TRANSLATE");
define("_NUM_WC","Badezimmer");
define("_NUM_WCS","Badezimmer");
define("_OBSERV_LIST","TO_TRANSLATE");
define("_OCTOBER","Oktober");
define("_OF","von");
define("_OFICINAS","Büros");
define("_ONLOAD","TO_TRANSLATE");
define("_OPINION","You view about this web");
define("_OPTIONAL","(Optional)");
define("_ORDER","Reihenfolge");
define("_ORDERBY","Ordnen nach");
define("_ORG","TO_TRANSLATE");
define("_ORG_HAS_SUBORG","TO_TRANSLATE");
define("_ORG_LST","TO_TRANSLATE");
define("_OUTAPP","TO_TRANSLATE");
define("_PAGE","TO_TRANSLATE");
define("_PAGO_MEN","Monatliche Hypothekenzahlung");
define("_PAGS","Seiten");
define("_PARAMS","TO_TRANSLATE");
define("_PARENTCTG_DCHILDREN","TO_TRANSLATE");
define("_PASSWORD","Passwort");
define("_PATH_IMAGE","TO_TRANSLATE");
define("_PERMS","TO_TRANSLATE");
define("_PERMS_HAS_SCR","TO_TRANSLATE");
define("_PICTURES","Fotos");
define("_PIEPAGINA","Powered by <a href=\"http://reos.elazos.com\">ReOS "._VERSION."</a> and released under the <a href=\"http://www.fsf.org/licensing/licenses/agpl-3.0.html\">GNU/AGPLv3 License.</a>");
define("_PLEASE_LOGIN","Bitten geben Sie Ihren Benutzernamen und das Passwort ein");
define("_POBLACIONES","TO_TRANSLATE");
define("_POBS","Suche nach Orten");
define("_POPHOST","TO_TRANSLATE");
define("_POPPASS","TO_TRANSLATE");
define("_POPUSER","TO_TRANSLATE");
define("_POSITION","TO_TRANSLATE");
define("_POS_IMG_PORT","TO_TRANSLATE");
define("_PRECIO","Preis");
define("_PRECIO_ALQUILER","Mietpreis  "._CURRENCY."");
define("_PRECIO_COMPRA","Kaufpreis "._CURRENCY."");
define("_PREFERE","TO_TRANSLATE");
define("_PREF_POBS","Bevorzugte Orte");
define("_PREVIOUS","Vorherige");
define("_PRE_VIVIE","Wohnungspreis");
define("_PRICE_FROM","Preis von");
define("_PRICE_MAX","Höchstpreis "._CURRENCY."");
define("_PRICE_MIN","Mindestpreis "._CURRENCY."");
define("_PRIORITY","TO_TRANSLATE");
define("_PROCESS_OK","TO_TRANSLATE");
define("_PRODS","TO_TRANSLATE");
define("_PROFS","TO_TRANSLATE");
define("_PROP_ACCOUNT","Immobilien des Kunden");
define("_PROV_NAME","TO_TRANSLATE");
define("_PRT_LAYOUT","TO_TRANSLATE");
define("_PST_ELEMTS","TO_TRANSLATE");
define("_PUBLI_YOUR","TO_TRANSLATE");
define("_READMORE","Weiter lesen ");
define("_RECOM","Unsere Empfehlung");
define("_REFERERS","TO_TRANSLATE");
define("_REF_IMMO","Referenznummer");
define("_REF_TICKET","TO_TRANSLATE");
define("_REGS_TXT","TO_TRANSLATE");
define("_REGUSERS","TO_TRANSLATE");
define("_REM_CONFIRM","TO_TRANSLATE");
define("_REM_TXT","TO_TRANSLATE");
define("_REM_USR","TO_TRANSLATE");
define("_RESERVATION","TO_TRANSLATE");
define("_RESERV_CONFIRM","TO_TRANSLATE");
define("_RESTORE","TO_TRANSLATE");
define("_RESULTS","Suchergebnis");
define("_RE_NEW_PASS","Geben Sie das neue Passwort erneut ein");
define("_RE_PASSWORD","Passwort erneut eingeben");
define("_ROOT_DEPT","TO_TRANSLATE");
define("_ROWS","Register");
define("_SADAY","Sa");
define("_SATURDAY","Samstag");
define("_SAT_DEPT","Kundendienst");
define("_SAVE","Speichern");
define("_SCREEN","TO_TRANSLATE");
define("_SCREENS","TO_TRANSLATE");
define("_SCREEN_HAS_VIEW","TO_TRANSLATE");
define("_SDAY","So");
define("_SEARCH_TITLE","Suche");
define("_SEASONS","TO_TRANSLATE");
define("_SEE2PRINT","Druckansicht");
define("_SEE_CYRILIC","TO_TRANSLATE");
define("_SEE_LATIN1","TO_TRANSLATE");
define("_SEGUROS","Versicherungen");
define("_SELECT","Auswählen");
define("_SELECTED","Ausgewählt");
define("_SELECTLANGUAGE","Sprache ändern!");
define("_SEND_OUTLOOK","TO_TRANSLATE");
define("_SEPTEMBER","September");
define("_SERVICES_LIST","TO_TRANSLATE");
define("_SET_ACTIVITIES","Aktivitäten");
define("_SET_EQUIP","Ausstattung");
define("_SET_IMG_FRONT","TO_TRANSLATE");
define("_SET_INTRO","Einleitung");
define("_SET_OBSERV","Anmerkungen");
define("_SET_PROPERTIES","Merkmale");
define("_SET_SERVICES","Leistungen");
define("_SHOW_GAL","Galerie anzeigen");
define("_SINFO","Informationsanfrage");
define("_SINFO_ADVERT","Über die Website werden keine persönlichen Angaben ohne Ihre Kenntnis erhoben bzw. an Dritte weitergeleitet.");
define("_SINFO_CONFIRM","TO_TRANSLATE");
define("_SINFO_TXT","Senden Sie uns Ihre Angaben zu, und wir werden uns mit Ihnen in Verbindung setzen.");
define("_SLOGAN","Immobilienmanagement");
define("_START","TO_TRANSLATE");
define("_STATE","Zustand");
define("_STATISTICS","TO_TRANSLATE");
define("_SUBJECT","TO_TRANSLATE");
define("_SUBS","Anmeldung");
define("_SUBS_PHRASE","Erhalten Sie unseren Newsletter");
define("_SUBS_TXT","Um Ihre Anmeldung durch andere Benutzer zu verhindern, werden Sie zur Bestätigung eine E-Mail mit Anleitungen erhalten, um ihre Anmeldung gültig werden zu lassen. Mit Übersendung dieses Formulars melden Sie sich für den Newsletter-Service an.");
define("_SUNDAY","Sonntag");
define("_SUPPORT","TO_TRANSLATE");
define("_TDAY","Di");
define("_TEAM_ACCOUNTS","TO_TRANSLATE");
define("_TEAM_IMMOS","TO_TRANSLATE");
define("_TEAM_TICKETS","TO_TRANSLATE");
define("_THDAY","Do");
define("_THEMES","TO_TRANSLATE");
define("_THOUSANDS_SEP",".");
define("_THUMB","TO_TRANSLATE");
define("_THURSDAY","Donnerstag");
define("_TICKETS","TO_TRANSLATE");
define("_TITLE_LOGIN","TO_TRANSLATE");
define("_TK_CTG_LST","TO_TRANSLATE");
define("_TOCLOSE","TO_TRANSLATE");
define("_TODO","TO_TRANSLATE");
define("_TOEND","TO_TRANSLATE");
define("_TOTAL","Gesamtbetrag");
define("_TOT_GST","Gesamtausgaben:");
define("_TOY_INTERES","Zu dieser Immobilie kontaktieren");
define("_TP_PRICE","Preistyp");
define("_TP_PROPIEDAD","Immobilientyp");
define("_TP_SDAYS","TO_TRANSLATE");
define("_TP_SEND","TO_TRANSLATE");
define("_TP_SEND_TO","TO_TRANSLATE");
define("_TP_SERVICIO","Transaktion");
define("_TP_STATE","TO_TRANSLATE");
define("_TP_VAT","TO_TRANSLATE");
define("_TUESDAY","Dienstag");
define("_TXT_ADDRESS1","Adresse");
define("_TXT_AGE","TO_TRANSLATE");
define("_TXT_ASUNT","Betreff");
define("_TXT_COMMENT","Kommentare");
define("_TXT_COMO","TO_TRANSLATE");
define("_TXT_CONTENT","TO_TRANSLATE");
define("_TXT_COUNTRY","TO_TRANSLATE");
define("_TXT_CP","Postleitzahl");
define("_TXT_DESC","Beschreibung");
define("_TXT_EMAIL","TO_TRANSLATE");
define("_TXT_EMAIL1","E-Mail-Adresse");
define("_TXT_ES","TO_TRANSLATE");
define("_TXT_FAX","Faxnummer");
define("_TXT_MAILING","TO_TRANSLATE");
define("_TXT_OBSRV","TO_TRANSLATE");
define("_TXT_POBLACION","Ort");
define("_TXT_SEARCH","TO_TRANSLATE");
define("_TXT_SIGN","TO_TRANSLATE");
define("_TXT_SUBJECT","TO_TRANSLATE");
define("_TXT_TELF1","Telefonnummer");
define("_TXT_TELF2","Telefonnummer 2");
define("_TXT_TITLE","Anrede");
define("_TXT_UNREG","Sie erhalten diese E-Mail aufgrund Ihrer Anmeldung in unserer Verteilerliste. Sollten Sie keine weiteren E-Mails erhalten wollen, klicken Sie auf:");
define("_TXT_URL","TO_TRANSLATE");
define("_TXT_WEB","Website");
define("_TXT_ZONA","Zone");
define("_UMONTH","Monat");
define("_UNREG","Abmelden");
define("_UNTITLED","TO_TRANSLATE");
define("_UPDATE","TO_TRANSLATE");
define("_UPDATED","TO_TRANSLATE");
define("_USED_PROP","Gebrauchte Wohnung");
define("_USER","TO_TRANSLATE");
define("_USERNAME","Benutzername");
define("_USER_DELETED","TO_TRANSLATE");
define("_USER_HAS_PST","TO_TRANSLATE");
define("_USER_INSERTED","TO_TRANSLATE");
define("_USER_TYPE","Typ");
define("_USR_BOOK_NOVALID","TO_TRANSLATE");
define("_USR_CONFIRM","Ihre Anmeldung wurde bestätigt.");
define("_USR_NOCONFIRM","Bei Ihrer Anmeldebestätigung wurde ein Fehler entdeckt.");
define("_USR_NOUNREG","Ihre Abmeldung konnte nicht bestätigt werden. Sollten Sie weitere E-Mails erhalten, setzen Sie sich bitte mit dem Kundendienst in Verbindung.");
define("_USR_UNREG","Sie wurden aus der E-Mail-Verteilerliste gestrichen.");
define("_VALUE","TO_TRANSLATE");
define("_VERACCS","TO_TRANSLATE");
define("_VERBOOKINGS","Availability Search");
define("_VERCONFIG","TO_TRANSLATE");
define("_VERCOUNTRIES","TO_TRANSLATE");
define("_VERGAL","TO_TRANSLATE");
define("_VERHTML","TO_TRANSLATE");
define("_VERIMMO","Immobiliensuche");
define("_VERINTROS","TO_TRANSLATE");
define("_VERLABELS","TO_TRANSLATE");
define("_VERMAILINGS","TO_TRANSLATE");
define("_VERNOT","TO_TRANSLATE");
define("_VERORGS","TO_TRANSLATE");
define("_VERPERMS","TO_TRANSLATE");
define("_VERPOBS","Aktive Städte");
define("_VERPRD","Produkte");
define("_VERPREFS","TO_TRANSLATE");
define("_VERPRICELST","TO_TRANSLATE");
define("_VERPRICEPRD","TO_TRANSLATE");
define("_VERPROPER","TO_TRANSLATE");
define("_VERSCR","TO_TRANSLATE");
define("_VERSEASONS","TO_TRANSLATE");
define("_VERTICKETS","TO_TRANSLATE");
define("_VERTKCTGS","TO_TRANSLATE");
define("_VERTKEMAILS","TO_TRANSLATE");
define("_VERUSERS","TO_TRANSLATE");
define("_VERVIEWS","TO_TRANSLATE");
define("_VER_PERFIL","Kaufprofil");
define("_VIEW","View");
define("_VIEWED","Angezeigt");
define("_VIEWS","TO_TRANSLATE");
define("_VIEWS_LST","TO_TRANSLATE");
define("_VIEW_FRONT_IN","TO_TRANSLATE");
define("_WANT_SELL","Ich will verkaufen");
define("_WANT_SELL_TXT","Erhalten Sie den wahren Gegenwert für Ihr Haus!");
define("_WDAY","Mi");
define("_WEDNESDAY","Mittwoch");
define("_WORDS_TO_FIND","Nach Wörtern suchen");
define("_XMLNAV","TO_TRANSLATE");
define("_XMLOUTPUT","TO_TRANSLATE");
define("_XMLPRT","TO_TRANSLATE");
define("_XSLFILE","TO_TRANSLATE");
define("_XSLPRT","TO_TRANSLATE");
define("_YEAR","Jahr");
define("_YEARS","Jahre");
define("_YOUR_LOAN","Berechnen Sie Ihre Hypothek");
define("_ZIP_FILE","TO_TRANSLATE");
?>