<?php
/**
 * ReOS is a vertical software for real estates.
 * Copyright 2010 IT ELAZOS S.L.
 *
 * This file is part of ReOS v2.x.x.
 *
 * ReOS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ReOS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with ReOS.  If not, see <http://www.gnu.org/licenses/>.
 **/


//File generated from a txt file at : Thu, 18 Feb 2010 12:02:08 +0100

define("_0","No");
define("_1","Si");
define("_ABOUTUS","Quienes Somos");
define("_ACCOUNTS","Clientes");
define("_ACONSULTAR","A consultar");
define("_ACTIVE","Activo");
define("_ACTIVE_ALL","TO_TRANSLATE");
define("_ACTIVITIES_LIST","Lista de valores actividades vacaciones");
define("_ADD","Añadir");
define("_ADDIMG","Añadir Foto");
define("_ADDIMGNOT","Fotos Noticia");
define("_ADDPOINT","Google Maps");
define("_ADDPRICELST","Añadir Lista de Precios");
define("_ADDPRICEPRD","Añadir Producto/Precio");
define("_ADDT_FILES","FICHEROS ADICIONALES");
define("_ADD_ACCOUNT","Añadir Cliente");
define("_ADD_CITY","Añadir Población");
define("_ADD_COMDAD","Añadir Comunidad");
define("_ADD_CONTACT","Añadir Contacto");
define("_ADD_COUNTRY","Añadir País");
define("_ADD_CTG","Añadir familia");
define("_ADD_DEPT","Añadir Departamento");
define("_ADD_GAL","Añadir Galeria");
define("_ADD_IMG_GAL","Añadir imagen a la galería");
define("_ADD_IMMO","Añadir Inmueble");
define("_ADD_MAILING","Añadir Mailing");
define("_ADD_NEW","Añadir Noticia");
define("_ADD_PERFIL","Añadir Perfil de Compra");
define("_ADD_PERM","Añadir Role / Perfil");
define("_ADD_PICTURE","Añadir foto");
define("_ADD_POSITION","Añadir Empleado");
define("_ADD_PROD","Añadir producto");
define("_ADD_PROV","Añadir Provincia");
define("_ADD_SCR","Añadir Pantalla");
define("_ADD_SDAY","Añadir nuevos días");
define("_ADD_SEASON","Añadir nueva temporada");
define("_ADD_TICKET","Añadir Ticket");
define("_ADD_TK_CTG","Añadir Categoria");
define("_ADD_USER","Añadir Usuario");
define("_ADD_VAL","Añadir Valor");
define("_ADD_VIEW","Añadir Vista");
define("_ADD_ZONA","Nueva Zona");
define("_ADMIN","Administración");
define("_ALL_ACCOUNTS","Todos los Clientes");
define("_ALL_IMMOS","Todos los Inmuebles");
define("_ALL_NEWS","Todas las Noticias");
define("_ALL_TICKETS","Todos los Tickets");
define("_ANY","Indiferente");
define("_APP_FILE","Fichero Aplicación");
define("_APRIL","Abril");
define("_ASIGN_POB","Seleccionar Poblaciones preferidas");
define("_AUGUST","Agosto");
define("_AVG_DAY_HITS","Media Páginas Vistas Diarias");
define("_AVG_DAY_ROBOTS","Media Buscadores Diarios");
define("_AVG_DAY_VISITS","Media Visitas Diarias");
define("_BACK","Retroceder");
define("_BACKUP","Copias de Seguridad");
define("_BOOK","Libro de visitas");
define("_BOOKINGS","Reservas");
define("_BOOKING_VALID","Su petición de reserva ha sido enviada. Recibirá un email de validación.");
define("_BOOKVALID","Validación Reserva");
define("_BOOK_ISVALID","Su reserva ha sido validada. Nos pondremos en contacto con Ud. para confirmar su reserva.");
define("_BOOK_TXT","Puede dejar su opinión rellenando el formulario del final. Muchas gracias por su participación.");
define("_BORRAR","Borrar");
define("_BUGGET","Presupuesto "._CURRENCY."");
define("_BUSY","Ocupado");
define("_BUSYBOOKING","La propiedad está ocupada para las fechas seleccionadas");
define("_BUYERS_ACCOUNTS","Buscar Compradores");
define("_BUY_GUIDE","Guía de Compra");
define("_CALC","Calcular");
define("_CALC_INM","Cálculo de cuotas hipoteca");
define("_CALC_LOAN_PAYMENTS","Cálculo de cuotas hipoteca");
define("_CALENDAR","Calendario");
define("_CAPTCHA","Texto de verificación");
define("_CATALOG","Catálogo");
define("_CHANGE_PASS","Cambiar Contraseña");
define("_CHARSET","UTF-8");
define("_CMT_CSSFILE","Fichero CSS - Cascading Style Sheets");
define("_CMT_IMAG","Gestión de imágenes de diseño y ficheros flash");
define("_CMT_XMLNAV","Fichero XML que define la estructura de cada pagina");
define("_CMT_XMLOUTPUT","Fichero generado por la aplicación como entrada del fichero XSL Transformation");
define("_CMT_XMLPRT","Fichero XML que define la estructura de cada página para imprimir");
define("_CMT_XSLFILE","Fichero XSL de transformación. Toma como entrada el fichero XML Output de la aplicación.");
define("_CMT_XSLPRT","Fichero XSL de transformación. Toma como entrada el fichero XML Output de la aplicación.");
define("_COD","Código");
define("_COD_CATEGORY","Código de Familia");
define("_COD_LANG","Idioma");
define("_COD_PRODUCT","Código de Producto");
define("_COMDAD_NAME","Comunidad Autonoma");
define("_COMO","Nos conociste por...");
define("_COM_APER","Comisión apertura :");
define("_CONFIRM","Confirmación de registro");
define("_CONNECTED_AS","Conectado como");
define("_CONTACTAR","Contactar");
define("_CONTACTS","Contactos");
define("_CONTENTS","Contenidos");
define("_CPASS","Contraseña");
define("_CSSCONFIG","Ficheros CSS");
define("_CSSFILE","CSS File");
define("_CSS_DELETED","Fichero CSS eliminado");
define("_CTG","Familia");
define("_CTGS","Familias");
define("_CTG_BELONGS","Familia a la que pertenece");
define("_CTG_HAS_PROD","Error al eliminar familia. La familia tiene productos, elimine primero los productos");
define("_CTG_NO_EXIST","Familia no existe");
define("_CTG_NO_NAME","El nombre de familia es obligatorio");
define("_CURRENT_PASS","Contraseña Actual");
define("_CUSTOMER","Cliente");
define("_CUSTZONE","Zona Clientes");
define("_DATE","Fecha");
define("_DATEMP","Datos Empresa");
define("_DATETIME_SQL","'%d/%m/%Y - %H:%i'");
define("_DATE_FORMAT","d/m/Y");
define("_DATE_FT","Fecha");
define("_DATE_SQL","'%d/%m/%Y'");
define("_DATOS_PERS","Datos Personales");
define("_DATPERS","Datos Personales");
define("_DAY","Día");
define("_DEACTIVE_ALL","TO_TRANSLATE");
define("_DECEMBER","Diciembre");
define("_DEC_POINT",",");
define("_DELETE","Eliminar");
define("_DELETED","Elemento eliminado correctamente");
define("_DEPT","Departamento");
define("_DEPTS","Departamentos");
define("_DESC_CATEGORY","Descripción");
define("_DESC_PROD","Descripción");
define("_DO_CALC","Cáculo Hipoteca");
define("_DTL","Detalle");
define("_DTL_ACCOUNT","Datos Cliente");
define("_DTL_ACCPERFIL","Datos Perfil de Compra");
define("_DTL_PROP","Datos Inmueble");
define("_DT_CREATE","Fecha Alta");
define("_DT_END","Fecha Fin");
define("_DT_SENT","Fecha de Envio");
define("_DT_START","Fecha Inicio");
define("_DT_VAL","Fecha de validez");
define("_DT_VALID","Valido hasta");
define("_EDIT","Editar");
define("_EDTACC","Cliente");
define("_EDTCOMDAD","Edit Comunidad");
define("_EDTCONTACT","Contacto");
define("_EDTCOUNTRY","País");
define("_EDTCTG","Familia Producto");
define("_EDTGAL","Galeria");
define("_EDTHIMMO","Propiedades Alojamiento Vacaciones");
define("_EDTHTML","Editar página");
define("_EDTIMMO","Inmueble");
define("_EDTIMMOGAL","Fotos inmueble");
define("_EDTLABEL","Editar Literal");
define("_EDTLST","Valor");
define("_EDTMAILING","Detalle de mailing");
define("_EDTMSG","Editar Mensaje");
define("_EDTORG","Departamento");
define("_EDTPERFIL","Perfil de Compra");
define("_EDTPERM","Perfil");
define("_EDTPOB","Editar Población");
define("_EDTPOSITION","Detalle Empleado");
define("_EDTPRD","Producto");
define("_EDTPRDGAL","Fotos Producto");
define("_EDTPREF","Editar Valor");
define("_EDTPRICELST","Editar Lista de precios");
define("_EDTPRICEPRD","Editar Precio");
define("_EDTPROV","Editar Provincia");
define("_EDTSCR","Pantalla");
define("_EDTSDAY","Días y precios");
define("_EDTSEASON","Detalle Temporada");
define("_EDTTICKET","TO_TRANSLATE");
define("_EDTTKCTG","Editar Categoria");
define("_EDTTKEMAIL","Email Template");
define("_EDTUSER","Usuario");
define("_EDTVIEW","Vista");
define("_EDT_ACCOUNT","Editar cliente");
define("_EDT_CONTACT","Editar Contacto");
define("_EDT_CTG","Editar Familia");
define("_EDT_DEPT","Editar Departamento");
define("_EDT_EMPL","Editar Empleado");
define("_EDT_GAL","Editar Galeria");
define("_EDT_IMMO","Editar Inmueble");
define("_EDT_MAILING","Editar mailing");
define("_EDT_NEW","Editar Noticia");
define("_EDT_PERM","Editar Role / Perfil");
define("_EDT_PROD","Editar producto");
define("_EDT_SCR","Editar Pantalla");
define("_EDT_USER","Editar Usuario");
define("_EDT_VAL","Editar Valor");
define("_EDT_VIEW","Editar Vista");
define("_EMPL","Empleado");
define("_EMPLES","TO_TRANSLATE");
define("_ENVIAR","Enviar");
define("_EQUIP_LIST","Lista de valores equipamiento alquileres vacaciones");
define("_ERROR_CAPTCHA","Introduzca el texto de verificación.");
define("_ERROR_CHECK_PSW","Error al comprobar contraseña");
define("_ERROR_CONTENT_MAILING","Introduzca el contenido del mail");
define("_ERROR_CURRENT_PSW","Contraseña actual incorrecta");
define("_ERROR_DATS","Error al acceder a los datos");
define("_ERROR_DELETE","Error durante la eliminación");
define("_ERROR_DIR_GAL","Error al crear directorios de la galería");
define("_ERROR_EMAIL_USER","Debe introducir el email");
define("_ERROR_ES_IN","Debe introducir una valor en español.");
define("_ERROR_IN","Error");
define("_ERROR_INSERT","Error al añadir");
define("_ERROR_LAST_USER","No se puede eliminar el último usuario de la organización");
define("_ERROR_NAME_MAILING","Introduzca el nombre del mailing");
define("_ERROR_NAME_USER","El nombre completo es obligatorio");
define("_ERROR_NM","Debe introducir el nombre");
define("_ERROR_NM_PROFILE","El nombre debe tener más de 5 carácteres");
define("_ERROR_NOPOB","No se han encontrado poblaciones para la provincia");
define("_ERROR_NUM_DOM","Introduzca el número de habitaciones");
define("_ERROR_NUM_PARKING","Introduzca el numero de plazas de parking");
define("_ERROR_NUM_WC","Introduzca el número de baños");
define("_ERROR_OBSRV","Debe introducir la descripción");
define("_ERROR_OPEN_DIR","No se puede abrir el directorio");
define("_ERROR_OPEN_FILE","Error al abrir fichero");
define("_ERROR_PASSUSR_NULL","EL usuario y la contraseña debe estar en blanco o tener valos ambos");
define("_ERROR_PROCESS","El proceso ha generado errores");
define("_ERROR_PSW_ERROR","Ha introducido la contraseña incorrectamente, reescriba la contraseña en los dos campos");
define("_ERROR_PSW_NOSTR","La contraseña solo puede contener letras y numeros, espacios no");
define("_ERROR_PSW_SHORT","La contraseña debe tener más de 5 carácteres");
define("_ERROR_PSW_USERNAME","La contraseña no puede ser igual al nombre de usuario");
define("_ERROR_SUBJ_MAILING","Introduzca el asunto");
define("_ERROR_SUPERF","Introduzca la superficie del terreno/parcela en M2, sino tiene ponga 0");
define("_ERROR_SUPERF_CONST","Introduzca la superficie en M2, sino tiene ponga 0");
define("_ERROR_SUPERT","Introduzca la superficie de terraza o ponga 0 si no tiene");
define("_ERROR_TELF1_USER","Debe introducir el teléfono");
define("_ERROR_TXT_CONTENT","Debe introducir el mensaje.");
define("_ERROR_UPDATE","Error durante la modificación");
define("_ERROR_USNAME_EXIST","El nombre de usuario ya existe, elija otro");
define("_ERROR_USRNAME_EXISTS","El usuario ya existe");
define("_ERROR_USRNAME_NOSTR","El usuario solo puede contener letras y numeros, espacios no");
define("_ERROR_USRNAME_SHORT","El nombre de usuario debe tener más de 5 carácteres");
define("_ER_SELET_TBL","Error en SELECT tabla");
define("_FDAY","Vi");
define("_FEBRUARY","Febrero");
define("_FECHA_FT","Fecha");
define("_FG_HIDDEN","Hidden");
define("_FG_PRIVATE","Mensaje privado");
define("_FIND","Buscar");
define("_FIND_BY_CITIES","Busqueda por Población");
define("_FIND_BY_CRITERIA","Busqueda por Criterios");
define("_FIND_BY_TPPROP","Busqueda por tipo de inmueble");
define("_FINPAGINA","");
define("_FOLDER","Directorio");
define("_FOUND","Total encontrados");
define("_FRIDAY","Viernes");
define("_FRONT","Portada");
define("_FULL_NAME","Nombre Completo");
define("_GALLERIES","Galerías de Fotos");
define("_GALLERY","Galeria");
define("_GALS","Galerias de Fotos");
define("_GAL_LST","Lista de Galerías");
define("_GAST_GEST","Gastos Gestoría, Notaría, Registro. <br/> (Depende del Gestor) Mínimo :");
define("_GENERAL_LAYOUT","ESTRUCTURA PAG.GENERALES");
define("_GEN_LANG","Instalar cambios en idiomas");
define("_GESTLANGS","Gestión de idiomas");
define("_GST_COMPRA","Gastos compra de la vivienda");
define("_GST_HIPOT","Gastos Hipoeca");
define("_GUIA","Guía");
define("_HELP","Ayuda");
define("_HOME","Inicio");
define("_HOMEPG","Inicio");
define("_HOUR","Hora");
define("_IDIOMA","es");
define("_ID_CATEGORY","id Familia");
define("_ID_POSITION","Asignado a");
define("_ID_TICKET","Número de Ticket");
define("_IMAG","Imágenes y ficheros flash");
define("_IMG","Foto");
define("_IMGCONFIG","Imágenes Plantilla");
define("_IMGHOME","head.jpg");
define("_IMGS_NOT","Imagenes de la noticia");
define("_IMG_FILE_ERROR","tiene un formato incorrecto  (Acentos, espacios, etc..NO) o es más grande de");
define("_IMG_FRONT","Imagen Portada");
define("_IMG_INT_1","Imagen Interior 1");
define("_IMG_INT_2","Imagen Interior 2");
define("_IMG_INT_3","Imagen Interior 3");
define("_IMG_PORT","Imagen Portada");
define("_IMMO","Datos inmueble");
define("_IMMOS","Inmuebles");
define("_IMP_ACTOS","Impuesto de actos jurídicos documentados :");
define("_IMP_COMPRA","Imp. Tran. Patrimoniales (Segunda mano) o IVA (Nueva) :");
define("_IMP_ENTR","Importe de la Entrada");
define("_IMP_SOL","Importe Hipoteca");
define("_IND_ACTIVE","Activo");
define("_IND_MAILING","Mailing");
define("_IND_OFERTA","Oferta");
define("_IND_PISCINA","Piscina");
define("_INFOLEGAL","Información Legal");
define("_INSERTED","Elemento añadido correctamente");
define("_INSIDE","Interior");
define("_INTROS_LIST","Lista de valores de intro de una oferta");
define("_INT_BANC","Interés Bancario");
define("_INT_CAPACITY","Capacidad pers.");
define("_INT_PERS","Número de personas");
define("_INT_SUPERFICIE","Terreno M2");
define("_INT_SUPERFICIE_CONST","Superficie M2");
define("_INT_TERRACE","Terraza M2");
define("_IN_NAME_ACCOUNT","El nombre de cliente es obligatorio");
define("_IN_NAME_GAL","El nombre de la galeria es obligatorio");
define("_IN_NAME_IMMO","La referencia de la Inmueble es obligatoria");
define("_IN_NAME_ORG","TO_TRANSLATE");
define("_IN_NOT_RESUM","El resumen de la noticia es obligatorio");
define("_IN_NOT_TITLE","El título de la noticia es obligatorio");
define("_IN_POB_IMMO","Debe seleccionar una población. Si no esta en la lista de poblaciones pongase en contacto con el administrador");
define("_IN_POB_ORG","Debe seleccionar una población para el departamento");
define("_IN_SUBJECT","Introduzca un asunto");
define("_JANUARY","Enero");
define("_JULY","Julio");
define("_JUNE","Junio");
define("_KEYWORDS_ADM","TO_TRANSLATE");
define("_LABELS_LIST","Lista de literales del programa");
define("_LANGS","Idiomas");
define("_LANGUAGE","Idioma");
define("_LATTITUD","TO_TRANSLATE");
define("_LBL_SEASONS","Temporada");
define("_LOGIN_FAILED","Su usuario o contraseña con incorrectos !");
define("_LOGIN_NOW","Entrar");
define("_LOGOUT","Desconectar");
define("_LONGITUD","TO_TRANSLATE");
define("_LOVS","Listas de valores");
define("_LSTMAILING","Lista de Mailings");
define("_LSTUSER","Lista de Usuarios");
define("_M2","M2");
define("_M2_TERRACE","M2 de terraza");
define("_M2_TERRENO","M2 de terreno");
define("_MAILING","Campañas de Mailing");
define("_MAIL_BKVALID","Validación de la reserva");
define("_MAIL_BKVALID_TXT","Muy sr. Mio, 

Para validar su reserva debe acceder al siguiente enlace :");
define("_MAIL_CONFIRM","Su petición de registro ha sido procesada, en breves momentos recibirá un correo para validar su registro.");
define("_MAIL_FORMAT","El formato del email es incorrecto");
define("_MAIL_HRECEV","Hemos recibido su petición");
define("_MAIL_NMSG","En breve le atenderemos.");
define("_MAIL_NOTI","Notificación de recepción");
define("_MAIL_REM","Datos de Acceso");
define("_MAIL_REM_TXT","Muy sr. Mio, 

Sus datos de acceso son :");
define("_MAIL_SUBS","Confirmación de registro");
define("_MAIL_SUBS_TXT","Muy sr. Mio, 

Para validar su registro  debe acceder al siguiente enlace :

");
define("_MAIN_IMG","Imagen principal");
define("_MANDATORY","Hay campos obligatorios");
define("_MAPINIT","Vista Inicial Google Maps");
define("_MARCH","Marzo");
define("_MAY","Mayo");
define("_MDAY","Lu");
define("_MKT","Mailings");
define("_MNU_ADM","Menu");
define("_MONDAY","Lunes");
define("_MONTH","Mes");
define("_MSG","Mensaje");
define("_MY_ACCOUNTS","Mis Clientes");
define("_MY_IMMOS","Mis Inmuebles");
define("_MY_NEWS","Mis Noticias");
define("_MY_PROFILE","Mi Perfil");
define("_MY_TICKETS","Mis Tickets");
define("_MY_TK_STATS","Mis Estadísticas");
define("_NAME","Nombre");
define("_NAME_ACCOUNT","Nombre de Cliente");
define("_NAME_CATEGORY","Familia");
define("_NAME_GAL","Nombre Galeria");
define("_NAME_MAILING","Nombre del Mailing");
define("_NAME_ORG","Oficina");
define("_NAME_POB","Población");
define("_NAME_POSITION","Cargo");
define("_NAME_PRICE_LST","Nombre Lista");
define("_NAME_PRODUCT","Nombre Producto");
define("_NAME_SEASONS","Nombre Temporada");
define("_NAME_USER","Nombre Empleado / Usuario");
define("_NESPECIAL","Nuestra Oferta Especial");
define("_NEW","Noticia");
define("_NEWS","Noticias");
define("_NEWSLST","Lista de Noticias");
define("_NEWS_EVENTS","Noticias y eventos");
define("_NEWUSER","Nuevo Usuario");
define("_NEW_PASSWORD","Nueva Contraseña");
define("_NEW_POS","Posición");
define("_NEW_PROP","Vivienda Nueva");
define("_NEW_RESUM","Resumen");
define("_NEW_TITLE","Título");
define("_NEW_TXT","Texto");
define("_NEXT","Siguiente");
define("_NM_CONTACT","Nombre Contacto");
define("_NM_PROFILE","Nombre");
define("_NM_SCREEN","Pantalla");
define("_NM_TK_CTG","Categoría");
define("_NM_VIEW","Vista");
define("_NOREGUSERS","No hay clientes registrados al boletín de noticias");
define("_NOSELECTED","No Seleccionado");
define("_NOTFOUND","TO_TRANSLATE");
define("_NOTI","Noticia");
define("_NOTICIA","Visualizar Noticia");
define("_NOVED","Novedades");
define("_NOVED_TXT","Ultimos inmuebles en cartera");
define("_NOVEMBER","Noviembre");
define("_NO_ACCOUNT","No hay clientes");
define("_NO_AV_LG","Este contenido no esta disponible en este idioma.");
define("_NO_COD","Código es obligatorio");
define("_NO_CONTACT","No se han encontrado contactos");
define("_NO_CTG","No hay familias");
define("_NO_EMPL","No hay empleados");
define("_NO_GALS","No hay galerias para la selección");
define("_NO_IMG_FRONT","La Galeria de imagenes no tiene establecida una imagen principal. La publicación de anuncios necesita la imagen principal.");
define("_NO_IMG_INT_1","No hay Imagen Interior 1");
define("_NO_IMG_INT_2","No hay Imagen Interior 2");
define("_NO_IMG_INT_3","No hay Imagen Interior 3");
define("_NO_IMG_PORT","No hay Imagen portada");
define("_NO_IMMO","No hay Inmuebles");
define("_NO_MAILING","No hay mailings");
define("_NO_MEMBERS","No tiene miembros en su equipo");
define("_NO_NOTS","No hay noticias");
define("_NO_ORGS","No hay organizaciones");
define("_NO_PRICE_LST","No hay listas de precios");
define("_NO_PROD","No hay productos");
define("_NO_PSTS","No positions");
define("_NO_SEASONS","No hay temporadas");
define("_NO_TICKET","No se han encontrado tickets para la selección");
define("_NUMORDER","Orden");
define("_NUM_DORMITORIO","habitación");
define("_NUM_DORMITORIOS","habitaciones");
define("_NUM_HITS","Páginas Vistas");
define("_NUM_ORDER","Orden de aparición");
define("_NUM_PARKING","plaza de parking");
define("_NUM_PARKINGS","plazas de parking");
define("_NUM_ROBOTS","Buscadores");
define("_NUM_SENT","Envíos realizados");
define("_NUM_VISITS","Visitas");
define("_NUM_WC","baño");
define("_NUM_WCS","Baños");
define("_OBSERV_LIST","Lista de valores observaciones alquiler vacaciones");
define("_OCTOBER","Octubre");
define("_OF","de");
define("_OFICINAS","Oficinas");
define("_ONLOAD","TO_TRANSLATE");
define("_OPINION","Opinión de esta web");
define("_OPTIONAL","(Opcional)");
define("_ORDER","Orden");
define("_ORDERBY","Ordenar por");
define("_ORG","Organización");
define("_ORG_HAS_SUBORG","El departamento tiene sub-departamento, elimine los sub-departamentos");
define("_ORG_LST","Estructura de la Organización");
define("_OUTAPP","SALIDA DE LA APLICACIÓN");
define("_PAGE","Página");
define("_PAGO_MEN","Pago mensual de la Hipoteca");
define("_PAGS","Páginas");
define("_PARAMS","Parámetros");
define("_PARENTCTG_DCHILDREN","Error al eliminar familia. La familia tiene subfamilias, elimine primero las subfamilias");
define("_PASSWORD","Contraseña");
define("_PATH_IMAGE","Imagen");
define("_PERMS","Roles");
define("_PERMS_HAS_SCR","El perfil tiene pantallas asignadas.");
define("_PICTURES","Fotos");
define("_PIEPAGINA","Powered by <a href=\"http://reos.elazos.com\">ReOS "._VERSION."</a> and released under the <a href=\"http://www.fsf.org/licensing/licenses/agpl-3.0.html\">GNU/AGPLv3 License.</a>");
define("_PLEASE_LOGIN","Por favor, identifiquese con su usuario y contraseña");
define("_POBLACIONES","Activar Poblaciones");
define("_POBS","Busqueda por poblaciones");
define("_POPHOST","Mail Host");
define("_POPPASS","Pop3 Password");
define("_POPUSER","Pop3 User");
define("_POSITION","Cargo");
define("_POS_IMG_PORT","Posición de la imagen en portada");
define("_PRECIO","Precio");
define("_PRECIO_ALQUILER","Precio de Alquiler "._CURRENCY."");
define("_PRECIO_COMPRA","Precio de Compra "._CURRENCY."");
define("_PREFERE","Preferencias");
define("_PREF_POBS","Poblaciones Preferidas");
define("_PREVIOUS","Anterior");
define("_PRE_VIVIE","Precio de la vivienda");
define("_PRICE_FROM","Precio desde");
define("_PRICE_MAX","Precio Máximo "._CURRENCY."");
define("_PRICE_MIN","Precio Mínimo "._CURRENCY."");
define("_PRIORITY","Prioridad");
define("_PROCESS_OK","Proceso ejecutado correctamente");
define("_PRODS","Productos");
define("_PROFS","Roles / Perfiles");
define("_PROP_ACCOUNT","Inmuebles del Cliente");
define("_PROV_NAME","Provincia");
define("_PRT_LAYOUT","ESTRUCTURA PAG. IMPRESIÓN");
define("_PST_ELEMTS","El cargo tiene asignados elementos, elimine primero los elementos");
define("_PUBLI_YOUR","Publica tu propiedad");
define("_READMORE","Leer más...");
define("_RECOM","Recomendamos");
define("_REFERERS","Remitentes");
define("_REF_IMMO","Referencia");
define("_REF_TICKET","Referencia");
define("_REGS_TXT","Para evitar que otros usuarios puedan registrarle, usted recibirá un correo de confirmación con las instrucciones para validar su registro. Mediante el envio de este formulario, usted se registra a la zona de clientes. Su correo electrónico será su identificador de usuario.");
define("_REGUSERS","Clientes registrados al boletín de noticias");
define("_REM_CONFIRM","Comprueba tu correo.");
define("_REM_TXT","Te enviaremos tu datos de acceso (Usuario y password) a tu dirección de correo electrónico.");
define("_REM_USR","¿ No recuerdas tus datos de acceso ?");
define("_RESERVATION","Reservar");
define("_RESERV_CONFIRM","Su petición de reserva ha sido confirmada.");
define("_RESTORE","Recuperar Copias");
define("_RESULTS","Resultado de la busqueda");
define("_RE_NEW_PASS","Reescriba la nueva Contraseña");
define("_RE_PASSWORD","Reescribir Contraseña");
define("_ROOT_DEPT","Departamento Inicial");
define("_ROWS","Registros");
define("_SADAY","Sa");
define("_SATURDAY","Sabado");
define("_SAT_DEPT","Atención a Clientes");
define("_SAVE","Guardar");
define("_SCREEN","Pantalla");
define("_SCREENS","Pantallas");
define("_SCREEN_HAS_VIEW","La pantalla tiene vistas asignadas.");
define("_SDAY","Do");
define("_SEARCH_TITLE","Busqueda");
define("_SEASONS","Temporadas para alquileres de vacaciones");
define("_SEE2PRINT","Ver para imprimir");
define("_SEE_CYRILIC","Ver idiomas Cyrilicos (Ruso)");
define("_SEE_LATIN1","Ver idiomas Occidentales");
define("_SEGUROS","Seguros");
define("_SELECT","Seleccionar");
define("_SELECTED","Seleccionado");
define("_SELECTLANGUAGE","Change Language !");
define("_SEND_OUTLOOK","Enviar a Outlook");
define("_SEPTEMBER","Septiembre");
define("_SERVICES_LIST","Lista de valores servcios vacaciones");
define("_SET_ACTIVITIES","Actividades");
define("_SET_EQUIP","Equipamiento");
define("_SET_IMG_FRONT","Hacer principal");
define("_SET_INTRO","Introducción");
define("_SET_OBSERV","Observaciones");
define("_SET_PROPERTIES","Características");
define("_SET_SERVICES","Servicios");
define("_SHOW_GAL","Mostrar Galeria");
define("_SINFO","Solicitud de Información");
define("_SINFO_ADVERT","A través de la página web no se recoge ningún dato personal sin su conocimiento, ni se ceden a terceros.");
define("_SINFO_CONFIRM","Formulario de contacto enviado correctamente.");
define("_SINFO_TXT","Envíenos sus datos y nos pondremos en contacto con usted");
define("_SLOGAN","Gestión Inmobiliaria");
define("_START","Inicio");
define("_STATE","Estado");
define("_STATISTICS","Estadísticas de Accesos");
define("_SUBJECT","Asunto");
define("_SUBS","Registrate");
define("_SUBS_PHRASE","Recibe nuestro boletín de novedades");
define("_SUBS_TXT","Para evitar que otros usuarios puedan registrarle, usted recibirá un correo de confirmación con las instrucciones para validar su registro. Mediante el envio de este formulario, usted se registra en el servicio de boletin de noticias.");
define("_SUNDAY","Domingo");
define("_SUPPORT","Soporte");
define("_TDAY","Ma");
define("_TEAM_ACCOUNTS","Clientes de mi equipo");
define("_TEAM_IMMOS","Inmuebles de mi equipo");
define("_TEAM_TICKETS","Tickets de mi equipo");
define("_THDAY","Ju");
define("_THEMES","Themes");
define("_THOUSANDS_SEP",".");
define("_THUMB","Fotos");
define("_THURSDAY","Jueves");
define("_TICKETS","Tickets");
define("_TITLE_LOGIN","Area de administración");
define("_TK_CTG_LST","Lista de Categorias");
define("_TOCLOSE","Cerrar");
define("_TODO","Acción");
define("_TOEND","Finalizar");
define("_TOTAL","Total");
define("_TOT_GST","Total gastos :");
define("_TOY_INTERES","Contactar por este Inmmueble");
define("_TP_PRICE","Tipo Precio");
define("_TP_PROPIEDAD","Tipo Inmueble");
define("_TP_SDAYS","Tipo");
define("_TP_SEND","Tipo de Envio");
define("_TP_SEND_TO","Enviar a");
define("_TP_SERVICIO","Operación");
define("_TP_STATE","Estado");
define("_TP_VAT","Tipo IVA %");
define("_TUESDAY","Martes");
define("_TXT_ADDRESS1","Dirección");
define("_TXT_AGE","Edad");
define("_TXT_ASUNT","Asunto");
define("_TXT_COMMENT","Comentarios");
define("_TXT_COMO","¿Cómo nos conociste?");
define("_TXT_CONTENT","Contenido");
define("_TXT_COUNTRY","País");
define("_TXT_CP","Código postal");
define("_TXT_DESC","Descripción");
define("_TXT_EMAIL","Correo");
define("_TXT_EMAIL1","Correo");
define("_TXT_ES","Valores");
define("_TXT_FAX","Fax");
define("_TXT_MAILING","Mediante las campañas de eMailing Uds. puede enviar masivamente información a sus clientes registrados.");
define("_TXT_OBSRV","Descripción");
define("_TXT_POBLACION","Población");
define("_TXT_SEARCH","Textos de Busqueda");
define("_TXT_SIGN","Firma");
define("_TXT_SUBJECT","Asunto");
define("_TXT_TELF1","Teléfono");
define("_TXT_TELF2","Teléfono 2");
define("_TXT_TITLE","Título");
define("_TXT_UNREG","Ha recibido este correo como resultado de su propio registro en nuestra lista de distribucción. Si no desea recibir más correos pulse :");
define("_TXT_URL","Dirección Web");
define("_TXT_WEB","Web");
define("_TXT_ZONA","Zona");
define("_UMONTH","Mes");
define("_UNREG","Dar de baja");
define("_UNTITLED","No definido");
define("_UPDATE","Actualizar");
define("_UPDATED","Modificación realizada correctamente");
define("_USED_PROP","Vivienda de segunda mano");
define("_USER","Usuario");
define("_USERNAME","Usuario");
define("_USER_DELETED","Usuario eliminado correctamente");
define("_USER_HAS_PST","El usuario tiene un cargo asignado. Elimine primero el cargo en organizaciones");
define("_USER_INSERTED","Usuario añadido correctamente");
define("_USER_TYPE","Tipo");
define("_USR_BOOK_NOVALID","No podemos validar su reserva.");
define("_USR_CONFIRM","Se ha confirmado su registro.");
define("_USR_NOCONFIRM","Se ha detectado un error en su confirmación de registro.");
define("_USR_NOUNREG","Su inscripción no ha podido ser validad para ser dada de baja. Pongase en contacto con Atención a clientes en caso de recibir más correos.");
define("_USR_UNREG","Ha sido dado de baja de la lista de distribución de correos");
define("_VALUE","Valor");
define("_VERACCS","Busqueda de Clientes");
define("_VERBOOKINGS","Busqueda de disponibilidad");
define("_VERCONFIG","Configuración de la plantilla");
define("_VERCOUNTRIES","Lista Paises/Ciudades ");
define("_VERGAL","Galerias de Fotos");
define("_VERHTML","Ver páginas");
define("_VERIMMO","Busqueda de Inmuebles");
define("_VERINTROS","Valores Intro de Oferta");
define("_VERLABELS","Textos de la aplicación");
define("_VERMAILINGS","Campañas de Mailing");
define("_VERNOT","Noticias y Eventos");
define("_VERORGS","Organización");
define("_VERPERMS","Lista de Roles / Perfiles");
define("_VERPOBS","Activar Poblaciones");
define("_VERPRD","Productos");
define("_VERPREFS","App. Variables");
define("_VERPRICELST","Listas de Precios");
define("_VERPRICEPRD","Productos y Precios");
define("_VERPROPER","Valores característcas de Oferta");
define("_VERSCR","Lista de Pantallas");
define("_VERSEASONS","Lista de Temporadas");
define("_VERTICKETS","Tickets");
define("_VERTKCTGS","Categorias de Soporte");
define("_VERTKEMAILS","Email Templates");
define("_VERUSERS","Lista Usuarios");
define("_VERVIEWS","Lista de vistas");
define("_VER_PERFIL","Perfil de Compra");
define("_VIEW","Vista");
define("_VIEWED","Visualizados");
define("_VIEWS","Vistas");
define("_VIEWS_LST","Lista de Vistas");
define("_VIEW_FRONT_IN","Noticia");
define("_WANT_SELL","Quiero Vender");
define("_WANT_SELL_TXT","Consiga por su vivienda lo que realmente vale !");
define("_WDAY","Mi");
define("_WEDNESDAY","Miercoles");
define("_WORDS_TO_FIND","Buscar palabras");
define("_XMLNAV","XML Layout File");
define("_XMLOUTPUT","XML Output File");
define("_XMLPRT","XML Printing Layout File");
define("_XSLFILE"," XSL Transformation File");
define("_XSLPRT","XSL Printing Transformation File");
define("_YEAR","Año");
define("_YEARS","Años");
define("_YOUR_LOAN","Calcula tu hipoteca");
define("_ZIP_FILE","Fichero ZIP");
?>