<?php
/**
 * ReOS is a vertical software for real estates.
 * Copyright 2010 IT ELAZOS S.L.
 *
 * This file is part of ReOS v2.x.x.
 *
 * ReOS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ReOS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with ReOS.  If not, see <http://www.gnu.org/licenses/>.
 **/


//File generated from a txt file at : Thu, 18 Feb 2010 12:02:08 +0100

define("_0","Nee");
define("_1","Ja");
define("_ABOUTUS","Wie zijn wij?");
define("_ACCOUNTS","TO_TRANSLATE");
define("_ACONSULTAR","Raadplegen");
define("_ACTIVE","Actief");
define("_ACTIVE_ALL","TO_TRANSLATE");
define("_ACTIVITIES_LIST","TO_TRANSLATE");
define("_ADD","TO_TRANSLATE");
define("_ADDIMG","TO_TRANSLATE");
define("_ADDIMGNOT","TO_TRANSLATE");
define("_ADDPOINT","Google Maps");
define("_ADDPRICELST","TO_TRANSLATE");
define("_ADDPRICEPRD","TO_TRANSLATE");
define("_ADDT_FILES","TO_TRANSLATE");
define("_ADD_ACCOUNT","TO_TRANSLATE");
define("_ADD_CITY","TO_TRANSLATE");
define("_ADD_COMDAD","TO_TRANSLATE");
define("_ADD_CONTACT","TO_TRANSLATE");
define("_ADD_COUNTRY","TO_TRANSLATE");
define("_ADD_CTG","TO_TRANSLATE");
define("_ADD_DEPT","TO_TRANSLATE");
define("_ADD_GAL","TO_TRANSLATE");
define("_ADD_IMG_GAL","TO_TRANSLATE");
define("_ADD_IMMO","TO_TRANSLATE");
define("_ADD_MAILING","TO_TRANSLATE");
define("_ADD_NEW","TO_TRANSLATE");
define("_ADD_PERFIL","TO_TRANSLATE");
define("_ADD_PERM","TO_TRANSLATE");
define("_ADD_PICTURE","TO_TRANSLATE");
define("_ADD_POSITION","TO_TRANSLATE");
define("_ADD_PROD","TO_TRANSLATE");
define("_ADD_PROV","TO_TRANSLATE");
define("_ADD_SCR","TO_TRANSLATE");
define("_ADD_SDAY","TO_TRANSLATE");
define("_ADD_SEASON","TO_TRANSLATE");
define("_ADD_TICKET","TO_TRANSLATE");
define("_ADD_TK_CTG","TO_TRANSLATE");
define("_ADD_USER","TO_TRANSLATE");
define("_ADD_VAL","TO_TRANSLATE");
define("_ADD_VIEW","TO_TRANSLATE");
define("_ADD_ZONA","TO_TRANSLATE");
define("_ADMIN","TO_TRANSLATE");
define("_ALL_ACCOUNTS","TO_TRANSLATE");
define("_ALL_IMMOS","TO_TRANSLATE");
define("_ALL_NEWS","TO_TRANSLATE");
define("_ALL_TICKETS","TO_TRANSLATE");
define("_ANY","Neutraal");
define("_APP_FILE","TO_TRANSLATE");
define("_APRIL","April");
define("_ASIGN_POB","TO_TRANSLATE");
define("_AUGUST","Augustus");
define("_AVG_DAY_HITS","TO_TRANSLATE");
define("_AVG_DAY_ROBOTS","TO_TRANSLATE");
define("_AVG_DAY_VISITS","TO_TRANSLATE");
define("_BACK","Terugkeren");
define("_BACKUP","TO_TRANSLATE");
define("_BOOK","TO_TRANSLATE");
define("_BOOKINGS","TO_TRANSLATE");
define("_BOOKING_VALID","TO_TRANSLATE");
define("_BOOKVALID","TO_TRANSLATE");
define("_BOOK_ISVALID","TO_TRANSLATE");
define("_BOOK_TXT","TO_TRANSLATE");
define("_BORRAR","Wissen");
define("_BUGGET","Prijsopgave "._CURRENCY."");
define("_BUSY","Bezet");
define("_BUSYBOOKING","TO_TRANSLATE");
define("_BUYERS_ACCOUNTS","TO_TRANSLATE");
define("_BUY_GUIDE","Koopgids");
define("_CALC","Berekenen");
define("_CALC_INM","Berekening van afbetalingstermijnen van hypotheek");
define("_CALC_LOAN_PAYMENTS","Berekening van afbetalingstermijnen van hypotheek ");
define("_CALENDAR","TO_TRANSLATE");
define("_CAPTCHA","TO_TRANSLATE");
define("_CATALOG","TO_TRANSLATE");
define("_CHANGE_PASS","Wachtwoord wijzigen");
define("_CHARSET","UTF-8");
define("_CMT_CSSFILE","TO_TRANSLATE");
define("_CMT_IMAG","TO_TRANSLATE");
define("_CMT_XMLNAV","TO_TRANSLATE");
define("_CMT_XMLOUTPUT","TO_TRANSLATE");
define("_CMT_XMLPRT","TO_TRANSLATE");
define("_CMT_XSLFILE","TO_TRANSLATE");
define("_CMT_XSLPRT","TO_TRANSLATE");
define("_COD","TO_TRANSLATE");
define("_COD_CATEGORY","TO_TRANSLATE");
define("_COD_LANG","TO_TRANSLATE");
define("_COD_PRODUCT","TO_TRANSLATE");
define("_COMDAD_NAME","TO_TRANSLATE");
define("_COMO","TO_TRANSLATE");
define("_COM_APER","Bereidstellingsprovisie");
define("_CONFIRM","Bevestiging van registratie");
define("_CONNECTED_AS","Verbinding aangegaan als");
define("_CONTACTAR","Contact opnemen");
define("_CONTACTS","TO_TRANSLATE");
define("_CONTENTS","TO_TRANSLATE");
define("_CPASS","TO_TRANSLATE");
define("_CSSCONFIG","TO_TRANSLATE");
define("_CSSFILE","TO_TRANSLATE");
define("_CSS_DELETED","TO_TRANSLATE");
define("_CTG","TO_TRANSLATE");
define("_CTGS","TO_TRANSLATE");
define("_CTG_BELONGS","TO_TRANSLATE");
define("_CTG_HAS_PROD","TO_TRANSLATE");
define("_CTG_NO_EXIST","TO_TRANSLATE");
define("_CTG_NO_NAME","TO_TRANSLATE");
define("_CURRENT_PASS","Huidig wachtwoord");
define("_CUSTOMER","Klant");
define("_CUSTZONE","TO_TRANSLATE");
define("_DATE","TO_TRANSLATE");
define("_DATEMP","TO_TRANSLATE");
define("_DATETIME_SQL","'%d/%m/%Y - %H:%i'");
define("_DATE_FORMAT","d/m/Y");
define("_DATE_FT","Datum");
define("_DATE_SQL","'%d/%m/%Y'");
define("_DATOS_PERS","Persoonlijke gegevens");
define("_DATPERS","TO_TRANSLATE");
define("_DAY","Dag");
define("_DEACTIVE_ALL","TO_TRANSLATE");
define("_DECEMBER","December");
define("_DEC_POINT",",");
define("_DELETE","TO_TRANSLATE");
define("_DELETED","TO_TRANSLATE");
define("_DEPT","TO_TRANSLATE");
define("_DEPTS","TO_TRANSLATE");
define("_DESC_CATEGORY","TO_TRANSLATE");
define("_DESC_PROD","TO_TRANSLATE");
define("_DO_CALC","Berekening van hypotheek");
define("_DTL","TO_TRANSLATE");
define("_DTL_ACCOUNT","TO_TRANSLATE");
define("_DTL_ACCPERFIL","TO_TRANSLATE");
define("_DTL_PROP","Gegevens over het pand");
define("_DT_CREATE","TO_TRANSLATE");
define("_DT_END","TO_TRANSLATE");
define("_DT_SENT","TO_TRANSLATE");
define("_DT_START","TO_TRANSLATE");
define("_DT_VAL","TO_TRANSLATE");
define("_DT_VALID","TO_TRANSLATE");
define("_EDIT","Bewerken");
define("_EDTACC","TO_TRANSLATE");
define("_EDTCOMDAD","TO_TRANSLATE");
define("_EDTCONTACT","TO_TRANSLATE");
define("_EDTCOUNTRY","TO_TRANSLATE");
define("_EDTCTG","TO_TRANSLATE");
define("_EDTGAL","Galerie");
define("_EDTHIMMO","TO_TRANSLATE");
define("_EDTHTML","TO_TRANSLATE");
define("_EDTIMMO","Onroerend goed");
define("_EDTIMMOGAL","TO_TRANSLATE");
define("_EDTLABEL","TO_TRANSLATE");
define("_EDTLST","TO_TRANSLATE");
define("_EDTMAILING","TO_TRANSLATE");
define("_EDTMSG","TO_TRANSLATE");
define("_EDTORG","TO_TRANSLATE");
define("_EDTPERFIL","TO_TRANSLATE");
define("_EDTPERM","TO_TRANSLATE");
define("_EDTPOB","TO_TRANSLATE");
define("_EDTPOSITION","TO_TRANSLATE");
define("_EDTPRD","TO_TRANSLATE");
define("_EDTPRDGAL","TO_TRANSLATE");
define("_EDTPREF","TO_TRANSLATE");
define("_EDTPRICELST","TO_TRANSLATE");
define("_EDTPRICEPRD","TO_TRANSLATE");
define("_EDTPROV","TO_TRANSLATE");
define("_EDTSCR","TO_TRANSLATE");
define("_EDTSDAY","TO_TRANSLATE");
define("_EDTSEASON","TO_TRANSLATE");
define("_EDTTICKET","TO_TRANSLATE");
define("_EDTTKCTG","TO_TRANSLATE");
define("_EDTTKEMAIL","TO_TRANSLATE");
define("_EDTUSER","TO_TRANSLATE");
define("_EDTVIEW","TO_TRANSLATE");
define("_EDT_ACCOUNT","Klant bewerken");
define("_EDT_CONTACT","TO_TRANSLATE");
define("_EDT_CTG","TO_TRANSLATE");
define("_EDT_DEPT","TO_TRANSLATE");
define("_EDT_EMPL","TO_TRANSLATE");
define("_EDT_GAL","TO_TRANSLATE");
define("_EDT_IMMO","TO_TRANSLATE");
define("_EDT_MAILING","TO_TRANSLATE");
define("_EDT_NEW","TO_TRANSLATE");
define("_EDT_PERM","TO_TRANSLATE");
define("_EDT_PROD","TO_TRANSLATE");
define("_EDT_SCR","TO_TRANSLATE");
define("_EDT_USER","TO_TRANSLATE");
define("_EDT_VAL","TO_TRANSLATE");
define("_EDT_VIEW","TO_TRANSLATE");
define("_EMPL","TO_TRANSLATE");
define("_EMPLES","TO_TRANSLATE");
define("_ENVIAR","Verzenden");
define("_EQUIP_LIST","TO_TRANSLATE");
define("_ERROR_CAPTCHA","Check woordverificatie.");
define("_ERROR_CHECK_PSW","TO_TRANSLATE");
define("_ERROR_CONTENT_MAILING","TO_TRANSLATE");
define("_ERROR_CURRENT_PSW","Huidig wachtwoord incorrect");
define("_ERROR_DATS","TO_TRANSLATE");
define("_ERROR_DELETE","TO_TRANSLATE");
define("_ERROR_DIR_GAL","TO_TRANSLATE");
define("_ERROR_EMAIL_USER","U moet het e-mailadres invullen");
define("_ERROR_ES_IN","TO_TRANSLATE");
define("_ERROR_IN","TO_TRANSLATE");
define("_ERROR_INSERT","TO_TRANSLATE");
define("_ERROR_LAST_USER","TO_TRANSLATE");
define("_ERROR_NAME_MAILING","TO_TRANSLATE");
define("_ERROR_NAME_USER","De volledige naam moet ingevoerd worden");
define("_ERROR_NM","TO_TRANSLATE");
define("_ERROR_NM_PROFILE","TO_TRANSLATE");
define("_ERROR_NOPOB","TO_TRANSLATE");
define("_ERROR_NUM_DOM","Vul het aantal slaapkamers in");
define("_ERROR_NUM_PARKING","TO_TRANSLATE");
define("_ERROR_NUM_WC","TO_TRANSLATE");
define("_ERROR_OBSRV","TO_TRANSLATE");
define("_ERROR_OPEN_DIR","TO_TRANSLATE");
define("_ERROR_OPEN_FILE","TO_TRANSLATE");
define("_ERROR_PASSUSR_NULL","De gebruikersnaam en het wachtwoord moeten leeg zijn of beide ingevuld zijn");
define("_ERROR_PROCESS","TO_TRANSLATE");
define("_ERROR_PSW_ERROR","Het wachtwoord werd verkeerd ingevuld, typ opnieuw het wachtwoord in de twee velden");
define("_ERROR_PSW_NOSTR","Het wachtwoord mag alleen letters en cijfers bevatten, geen spaties");
define("_ERROR_PSW_SHORT","Het wachtwoord moet bestaan uit meer dan 5 tekens");
define("_ERROR_PSW_USERNAME","Het wachtwoord mag niet identiek zijn aan de gebruikersnaam");
define("_ERROR_SUBJ_MAILING","TO_TRANSLATE");
define("_ERROR_SUPERF","TO_TRANSLATE");
define("_ERROR_SUPERF_CONST","TO_TRANSLATE");
define("_ERROR_SUPERT","TO_TRANSLATE");
define("_ERROR_TELF1_USER","U moet het telefoonnummer invullen");
define("_ERROR_TXT_CONTENT","TO_TRANSLATE");
define("_ERROR_UPDATE","TO_TRANSLATE");
define("_ERROR_USNAME_EXIST","Deze gebruikersnaam bestaat al, kies een andere naam");
define("_ERROR_USRNAME_EXISTS","Deze gebruikersnaam bestaat al");
define("_ERROR_USRNAME_NOSTR","De gebruikersnaam mag alleen letters en cijfers bevatten, geen spaties");
define("_ERROR_USRNAME_SHORT","De gebruikersnaam moet bestaan uit meer dan 5 tekens");
define("_ER_SELET_TBL","TO_TRANSLATE");
define("_FDAY","V");
define("_FEBRUARY","Februari");
define("_FECHA_FT","Datum");
define("_FG_HIDDEN","TO_TRANSLATE");
define("_FG_PRIVATE","TO_TRANSLATE");
define("_FIND","Zoeken");
define("_FIND_BY_CITIES","Zoeken op gemeente");
define("_FIND_BY_CRITERIA","Zoeken volgens criteria");
define("_FIND_BY_TPPROP","Zoeken op type onroerend goed");
define("_FINPAGINA","");
define("_FOLDER","TO_TRANSLATE");
define("_FOUND","Totaal van gevonden eenheden");
define("_FRIDAY","Vrijdag");
define("_FRONT","Voorpagina");
define("_FULL_NAME","Volledige naam");
define("_GALLERIES","TO_TRANSLATE");
define("_GALLERY","TO_TRANSLATE");
define("_GALS","TO_TRANSLATE");
define("_GAL_LST","TO_TRANSLATE");
define("_GAST_GEST","Kosten voor administratiekantoor, notaris, kadaster. <br/>(Afhankelijk van de beheerder) Minimum:");
define("_GENERAL_LAYOUT","TO_TRANSLATE");
define("_GEN_LANG","TO_TRANSLATE");
define("_GESTLANGS","TO_TRANSLATE");
define("_GST_COMPRA","Kosten voor de aankoop van de woning");
define("_GST_HIPOT","Hypotheekkosten");
define("_GUIA","Gids");
define("_HELP","Help");
define("_HOME","Begin");
define("_HOMEPG","Begin");
define("_HOUR","Tijd");
define("_IDIOMA","nl");
define("_ID_CATEGORY","TO_TRANSLATE");
define("_ID_POSITION","Toegekend aan");
define("_ID_TICKET","TO_TRANSLATE");
define("_IMAG","TO_TRANSLATE");
define("_IMG","Foto");
define("_IMGCONFIG","TO_TRANSLATE");
define("_IMGHOME","head.jpg");
define("_IMGS_NOT","TO_TRANSLATE");
define("_IMG_FILE_ERROR","TO_TRANSLATE");
define("_IMG_FRONT","TO_TRANSLATE");
define("_IMG_INT_1","TO_TRANSLATE");
define("_IMG_INT_2","TO_TRANSLATE");
define("_IMG_INT_3","TO_TRANSLATE");
define("_IMG_PORT","TO_TRANSLATE");
define("_IMMO","Gegevens over de eigendom");
define("_IMMOS","TO_TRANSLATE");
define("_IMP_ACTOS","Belasting op zegel- en registratierechten");
define("_IMP_COMPRA","Overdrachtsbelasting (tweedehands) of BTW (Nieuw):");
define("_IMP_ENTR","Bedrag van aanbetaling");
define("_IMP_SOL","Bedrag van hypotheek");
define("_IND_ACTIVE","TO_TRANSLATE");
define("_IND_MAILING","TO_TRANSLATE");
define("_IND_OFERTA","Aanbod");
define("_IND_PISCINA","Zwembad");
define("_INFOLEGAL","Wettelijke informatie");
define("_INSERTED","TO_TRANSLATE");
define("_INSIDE","Binnengedeelte");
define("_INTROS_LIST","TO_TRANSLATE");
define("_INT_BANC","Bankinterest");
define("_INT_CAPACITY","Capaciteit pers.");
define("_INT_PERS","TO_TRANSLATE");
define("_INT_SUPERFICIE","Grond M2");
define("_INT_SUPERFICIE_CONST","Oppervlakte M2");
define("_INT_TERRACE","TO_TRANSLATE");
define("_IN_NAME_ACCOUNT","De naam van de klant is verplicht");
define("_IN_NAME_GAL","TO_TRANSLATE");
define("_IN_NAME_IMMO","TO_TRANSLATE");
define("_IN_NAME_ORG","TO_TRANSLATE");
define("_IN_NOT_RESUM","TO_TRANSLATE");
define("_IN_NOT_TITLE","TO_TRANSLATE");
define("_IN_POB_IMMO","TO_TRANSLATE");
define("_IN_POB_ORG","TO_TRANSLATE");
define("_IN_SUBJECT","Vul een onderwerp in");
define("_JANUARY","Januari");
define("_JULY","Juli");
define("_JUNE","Juni");
define("_KEYWORDS_ADM","TO_TRANSLATE");
define("_LABELS_LIST","TO_TRANSLATE");
define("_LANGS","TO_TRANSLATE");
define("_LANGUAGE","Taal");
define("_LATTITUD","TO_TRANSLATE");
define("_LBL_SEASONS","TO_TRANSLATE");
define("_LOGIN_FAILED","Uw gebruikersnaam of wachtwoord is incorrect");
define("_LOGIN_NOW","Openen");
define("_LOGOUT","Verbinding verbreken");
define("_LONGITUD","TO_TRANSLATE");
define("_LOVS","TO_TRANSLATE");
define("_LSTMAILING","TO_TRANSLATE");
define("_LSTUSER","TO_TRANSLATE");
define("_M2","M2");
define("_M2_TERRACE","TO_TRANSLATE");
define("_M2_TERRENO","M2 terrein");
define("_MAILING","TO_TRANSLATE");
define("_MAIL_BKVALID","TO_TRANSLATE");
define("_MAIL_BKVALID_TXT","TO_TRANSLATE");
define("_MAIL_CONFIRM","Uw inschrijvingsverzoek is verwerkt, binnen enkele ogenblikken ontvangt u een e-mail waarin uw inschrijving bevestigd wordt.");
define("_MAIL_FORMAT","De e-mailopmaak is incorrect");
define("_MAIL_HRECEV","Wij hebben uw verzoek ontvangen");
define("_MAIL_NMSG","Wij zullen zo spoedig mogelijk ingaan op uw verzoek");
define("_MAIL_NOTI","Ontvangstbevestiging");
define("_MAIL_REM","TO_TRANSLATE");
define("_MAIL_REM_TXT","TO_TRANSLATE");
define("_MAIL_SUBS","Bevestiging van inschrijving");
define("_MAIL_SUBS_TXT","Geachte heer/mevrouw, 

Om uw inschrijving te bevestigen en toegang te krijgen tot de diensten van Propiweb moet u de volgende link openen:

");
define("_MAIN_IMG","TO_TRANSLATE");
define("_MANDATORY","TO_TRANSLATE");
define("_MAPINIT","TO_TRANSLATE");
define("_MARCH","Maart");
define("_MAY","Mei");
define("_MDAY","M");
define("_MKT","Mailings");
define("_MNU_ADM","Menu");
define("_MONDAY","Maandag");
define("_MONTH","TO_TRANSLATE");
define("_MSG","Bericht");
define("_MY_ACCOUNTS","TO_TRANSLATE");
define("_MY_IMMOS","TO_TRANSLATE");
define("_MY_NEWS","TO_TRANSLATE");
define("_MY_PROFILE","Mijn profiel");
define("_MY_TICKETS","TO_TRANSLATE");
define("_MY_TK_STATS","TO_TRANSLATE");
define("_NAME","TO_TRANSLATE");
define("_NAME_ACCOUNT","Naam van klant");
define("_NAME_CATEGORY","TO_TRANSLATE");
define("_NAME_GAL","TO_TRANSLATE");
define("_NAME_MAILING","TO_TRANSLATE");
define("_NAME_ORG","Kantoor");
define("_NAME_POB","TO_TRANSLATE");
define("_NAME_POSITION","TO_TRANSLATE");
define("_NAME_PRICE_LST","TO_TRANSLATE");
define("_NAME_PRODUCT","TO_TRANSLATE");
define("_NAME_SEASONS","TO_TRANSLATE");
define("_NAME_USER","TO_TRANSLATE");
define("_NESPECIAL","Onze speciale aanbieding");
define("_NEW","Nieuwsitem");
define("_NEWS","Nieuws");
define("_NEWSLST","TO_TRANSLATE");
define("_NEWS_EVENTS","Nieuws en evenementen");
define("_NEWUSER","Nieuwe gebruiker");
define("_NEW_PASSWORD","Nieuw wachtwoord");
define("_NEW_POS","Op de voorpagina");
define("_NEW_PROP","Nieuwe woning");
define("_NEW_RESUM","Samenvatting");
define("_NEW_TITLE","TO_TRANSLATE");
define("_NEW_TXT","Tekst");
define("_NEXT","Volgende");
define("_NM_CONTACT","TO_TRANSLATE");
define("_NM_PROFILE","TO_TRANSLATE");
define("_NM_SCREEN","TO_TRANSLATE");
define("_NM_TK_CTG","TO_TRANSLATE");
define("_NM_VIEW","TO_TRANSLATE");
define("_NOREGUSERS","TO_TRANSLATE");
define("_NOSELECTED","Ongeselecteerde");
define("_NOTFOUND","TO_TRANSLATE");
define("_NOTI","TO_TRANSLATE");
define("_NOTICIA","Nieuwsitem weergeven");
define("_NOVED","Nieuwigheden");
define("_NOVED_TXT","Laatste onroerende goederen in aanbod");
define("_NOVEMBER","November");
define("_NO_ACCOUNT","TO_TRANSLATE");
define("_NO_AV_LG","Deze inhoud is niet beschikbaar in deze taal");
define("_NO_COD","TO_TRANSLATE");
define("_NO_CONTACT","TO_TRANSLATE");
define("_NO_CTG","TO_TRANSLATE");
define("_NO_EMPL","TO_TRANSLATE");
define("_NO_GALS","TO_TRANSLATE");
define("_NO_IMG_FRONT","TO_TRANSLATE");
define("_NO_IMG_INT_1","TO_TRANSLATE");
define("_NO_IMG_INT_2","TO_TRANSLATE");
define("_NO_IMG_INT_3","TO_TRANSLATE");
define("_NO_IMG_PORT","TO_TRANSLATE");
define("_NO_IMMO","Er zijn geen onroerende goederen voor deze selectie");
define("_NO_MAILING","TO_TRANSLATE");
define("_NO_MEMBERS","TO_TRANSLATE");
define("_NO_NOTS","TO_TRANSLATE");
define("_NO_ORGS","TO_TRANSLATE");
define("_NO_PRICE_LST","TO_TRANSLATE");
define("_NO_PROD","TO_TRANSLATE");
define("_NO_PSTS","TO_TRANSLATE");
define("_NO_SEASONS","TO_TRANSLATE");
define("_NO_TICKET","TO_TRANSLATE");
define("_NUMORDER","TO_TRANSLATE");
define("_NUM_DORMITORIO","slaapkamer");
define("_NUM_DORMITORIOS","slaapkamers");
define("_NUM_HITS","TO_TRANSLATE");
define("_NUM_ORDER","TO_TRANSLATE");
define("_NUM_PARKING","parkeerplaats");
define("_NUM_PARKINGS","parkeerplaatsen");
define("_NUM_ROBOTS","TO_TRANSLATE");
define("_NUM_SENT","TO_TRANSLATE");
define("_NUM_VISITS","TO_TRANSLATE");
define("_NUM_WC","badkamer");
define("_NUM_WCS","Badkamers");
define("_OBSERV_LIST","TO_TRANSLATE");
define("_OCTOBER","Oktober");
define("_OF","of");
define("_OFICINAS","Kantoren");
define("_ONLOAD","TO_TRANSLATE");
define("_OPINION","You view about this web");
define("_OPTIONAL","(Optioneel)");
define("_ORDER","Volgorde");
define("_ORDERBY","Schikken op");
define("_ORG","TO_TRANSLATE");
define("_ORG_HAS_SUBORG","TO_TRANSLATE");
define("_ORG_LST","TO_TRANSLATE");
define("_OUTAPP","TO_TRANSLATE");
define("_PAGE","TO_TRANSLATE");
define("_PAGO_MEN","Maandelijkse afbetaling van de hypotheek");
define("_PAGS","Paginas");
define("_PARAMS","TO_TRANSLATE");
define("_PARENTCTG_DCHILDREN","TO_TRANSLATE");
define("_PASSWORD","Wachtwoord");
define("_PATH_IMAGE","TO_TRANSLATE");
define("_PERMS","TO_TRANSLATE");
define("_PERMS_HAS_SCR","TO_TRANSLATE");
define("_PICTURES","Fotos");
define("_PIEPAGINA","Powered by <a href=\"http://reos.elazos.com\">ReOS "._VERSION."</a> and released under the <a href=\"http://www.fsf.org/licensing/licenses/agpl-3.0.html\">GNU/AGPLv3 License.</a>");
define("_PLEASE_LOGIN","Gelieve u te identificeren met uw gebruikersnaam en wachtwoord");
define("_POBLACIONES","TO_TRANSLATE");
define("_POBS","Zoeken op gemeenten");
define("_POPHOST","TO_TRANSLATE");
define("_POPPASS","TO_TRANSLATE");
define("_POPUSER","TO_TRANSLATE");
define("_POSITION","TO_TRANSLATE");
define("_POS_IMG_PORT","TO_TRANSLATE");
define("_PRECIO","Prijs");
define("_PRECIO_ALQUILER","Huurprijs "._CURRENCY."");
define("_PRECIO_COMPRA","Koopprijs "._CURRENCY."");
define("_PREFERE","TO_TRANSLATE");
define("_PREF_POBS","Voorkeursgemeenten");
define("_PREVIOUS","Vorige");
define("_PRE_VIVIE","Prijs van de woning");
define("_PRICE_FROM","TO_TRANSLATE");
define("_PRICE_MAX","Max.prijs "._CURRENCY."");
define("_PRICE_MIN","Min.prijs "._CURRENCY."");
define("_PRIORITY","TO_TRANSLATE");
define("_PROCESS_OK","TO_TRANSLATE");
define("_PRODS","TO_TRANSLATE");
define("_PROFS","TO_TRANSLATE");
define("_PROP_ACCOUNT","Onroerende goederen van klant");
define("_PROV_NAME","TO_TRANSLATE");
define("_PRT_LAYOUT","TO_TRANSLATE");
define("_PST_ELEMTS","TO_TRANSLATE");
define("_PUBLI_YOUR","TO_TRANSLATE");
define("_READMORE","Meer lezen...");
define("_RECOM","Aanbevelingen");
define("_REFERERS","TO_TRANSLATE");
define("_REF_IMMO","Referentie");
define("_REF_TICKET","TO_TRANSLATE");
define("_REGS_TXT","TO_TRANSLATE");
define("_REGUSERS","TO_TRANSLATE");
define("_REM_CONFIRM","TO_TRANSLATE");
define("_REM_TXT","TO_TRANSLATE");
define("_REM_USR","TO_TRANSLATE");
define("_RESERVATION","TO_TRANSLATE");
define("_RESERV_CONFIRM","TO_TRANSLATE");
define("_RESTORE","TO_TRANSLATE");
define("_RESULTS","Resultaat van de zoekopdracht");
define("_RE_NEW_PASS","Nieuw wachtwoord opnieuw intypen");
define("_RE_PASSWORD","Wachtwoord opnieuw intypen");
define("_ROOT_DEPT","TO_TRANSLATE");
define("_ROWS","Registers");
define("_SADAY","ZA");
define("_SATURDAY","Zaterdag");
define("_SAT_DEPT","Klantenservice");
define("_SAVE","Opslaan");
define("_SCREEN","TO_TRANSLATE");
define("_SCREENS","TO_TRANSLATE");
define("_SCREEN_HAS_VIEW","TO_TRANSLATE");
define("_SDAY","ZO");
define("_SEARCH_TITLE","Zoeken");
define("_SEASONS","TO_TRANSLATE");
define("_SEE2PRINT","Afdrukweergave");
define("_SEE_CYRILIC","TO_TRANSLATE");
define("_SEE_LATIN1","TO_TRANSLATE");
define("_SEGUROS","Verzekeringen:");
define("_SELECT","Selecteren");
define("_SELECTED","Geselecteerd");
define("_SELECTLANGUAGE","Taal wijzigen !");
define("_SEND_OUTLOOK","TO_TRANSLATE");
define("_SEPTEMBER","September");
define("_SERVICES_LIST","TO_TRANSLATE");
define("_SET_ACTIVITIES","Activiteiten");
define("_SET_EQUIP","Materiaal");
define("_SET_IMG_FRONT","TO_TRANSLATE");
define("_SET_INTRO","Inleiding");
define("_SET_OBSERV","Opmerkingen");
define("_SET_PROPERTIES","Kenmerken");
define("_SET_SERVICES","Diensten");
define("_SHOW_GAL","Galerie weergeven");
define("_SINFO","Informatie aanvragen");
define("_SINFO_ADVERT","Op onze webpagina worden geen persoonlijke gegevens verzameld buiten uw weten en uw gegevens worden ook niet doorgegeven aan derden");
define("_SINFO_CONFIRM","TO_TRANSLATE");
define("_SINFO_TXT","Stuur ons uw gegevens en wij contacteren u");
define("_SLOGAN","Onroerend-goedbeheer");
define("_START","Begin");
define("_STATE","Staat");
define("_STATISTICS","TO_TRANSLATE");
define("_SUBJECT","TO_TRANSLATE");
define("_SUBS","Inschrijven");
define("_SUBS_PHRASE","Ontvang de nieuwigheden");
define("_SUBS_TXT","Om te vermijden dat andere gebruikers u kunnen inschrijven, ontvangt u een e-mail ter bevestiging, met aanwijzingen voor de bekrachtiging van uw registratie. Door de verzending van dit formulier schrijft u zich in voor de service van de nieuwsbulletins. Uw e-mail wordt uw gebruikersnaam");
define("_SUNDAY","Zondag");
define("_SUPPORT","TO_TRANSLATE");
define("_TDAY","DI");
define("_TEAM_ACCOUNTS","TO_TRANSLATE");
define("_TEAM_IMMOS","TO_TRANSLATE");
define("_TEAM_TICKETS","TO_TRANSLATE");
define("_THDAY","DO");
define("_THEMES","TO_TRANSLATE");
define("_THOUSANDS_SEP",".");
define("_THUMB","TO_TRANSLATE");
define("_THURSDAY","Donderdag");
define("_TICKETS","TO_TRANSLATE");
define("_TITLE_LOGIN","TO_TRANSLATE");
define("_TK_CTG_LST","TO_TRANSLATE");
define("_TOCLOSE","TO_TRANSLATE");
define("_TODO","TO_TRANSLATE");
define("_TOEND","TO_TRANSLATE");
define("_TOTAL","Totaal");
define("_TOT_GST","Totale kosten:");
define("_TOY_INTERES","Contact opnemen via dit onroerendgoedbedrijf");
define("_TP_PRICE","Prijstype");
define("_TP_PROPIEDAD","T. Onroerend goed");
define("_TP_SDAYS","TO_TRANSLATE");
define("_TP_SEND","TO_TRANSLATE");
define("_TP_SEND_TO","TO_TRANSLATE");
define("_TP_SERVICIO","Verrichting");
define("_TP_STATE","TO_TRANSLATE");
define("_TP_VAT","TO_TRANSLATE");
define("_TUESDAY","Dinsdag");
define("_TXT_ADDRESS1","Adres");
define("_TXT_AGE","TO_TRANSLATE");
define("_TXT_ASUNT","Onderwerp");
define("_TXT_COMMENT","Opmerkingen");
define("_TXT_COMO","TO_TRANSLATE");
define("_TXT_CONTENT","TO_TRANSLATE");
define("_TXT_COUNTRY","TO_TRANSLATE");
define("_TXT_CP","Postcode");
define("_TXT_DESC","Beschrijving");
define("_TXT_EMAIL","E-mail");
define("_TXT_EMAIL1","E-mail");
define("_TXT_ES","TO_TRANSLATE");
define("_TXT_FAX","Fax");
define("_TXT_MAILING","TO_TRANSLATE");
define("_TXT_OBSRV","TO_TRANSLATE");
define("_TXT_POBLACION","Gemeente");
define("_TXT_SEARCH","TO_TRANSLATE");
define("_TXT_SIGN","TO_TRANSLATE");
define("_TXT_SUBJECT","TO_TRANSLATE");
define("_TXT_TELF1","Telefoonnummer");
define("_TXT_TELF2","Telefoonnummer 2");
define("_TXT_TITLE","Titel");
define("_TXT_UNREG","U ontvangt dit bericht omdat u zich ingeschreven hebt op onze meiling-lijst. Als u geen mail meer wilt ontvangen, klik dan hier:");
define("_TXT_URL","TO_TRANSLATE");
define("_TXT_WEB","Website");
define("_TXT_ZONA","Buurt");
define("_UMONTH","Maand");
define("_UNREG","Uit de lijst verwijderen");
define("_UNTITLED","TO_TRANSLATE");
define("_UPDATE","TO_TRANSLATE");
define("_UPDATED","TO_TRANSLATE");
define("_USED_PROP","Tweedehandswoning");
define("_USER","TO_TRANSLATE");
define("_USERNAME","Gebruikersnaam");
define("_USER_DELETED","TO_TRANSLATE");
define("_USER_HAS_PST","TO_TRANSLATE");
define("_USER_INSERTED","TO_TRANSLATE");
define("_USER_TYPE","Type");
define("_USR_BOOK_NOVALID","TO_TRANSLATE");
define("_USR_CONFIRM","Uw registratie is bevestigd.");
define("_USR_NOCONFIRM","Er is een fout opgetreden tijdens het registratieproces.");
define("_USR_NOUNREG","Uw verwijdering uit de mailing-lijst kon niet bevestigd worden. Gelieve de klantendienst te contacteren als u mails blijft ontvangen");
define("_USR_UNREG","U bent uit de mailing-lijst verwijderd.");
define("_VALUE","TO_TRANSLATE");
define("_VERACCS","TO_TRANSLATE");
define("_VERBOOKINGS","TO_TRANSLATE");
define("_VERCONFIG","TO_TRANSLATE");
define("_VERCOUNTRIES","TO_TRANSLATE");
define("_VERGAL","TO_TRANSLATE");
define("_VERHTML","TO_TRANSLATE");
define("_VERIMMO","Zoeken naar onroerende goederen");
define("_VERINTROS","TO_TRANSLATE");
define("_VERLABELS","TO_TRANSLATE");
define("_VERMAILINGS","TO_TRANSLATE");
define("_VERNOT","TO_TRANSLATE");
define("_VERORGS","TO_TRANSLATE");
define("_VERPERMS","TO_TRANSLATE");
define("_VERPOBS","Actieve Steden");
define("_VERPRD","Products");
define("_VERPREFS","TO_TRANSLATE");
define("_VERPRICELST","TO_TRANSLATE");
define("_VERPRICEPRD","TO_TRANSLATE");
define("_VERPROPER","TO_TRANSLATE");
define("_VERSCR","TO_TRANSLATE");
define("_VERSEASONS","TO_TRANSLATE");
define("_VERTICKETS","TO_TRANSLATE");
define("_VERTKCTGS","TO_TRANSLATE");
define("_VERTKEMAILS","TO_TRANSLATE");
define("_VERUSERS","TO_TRANSLATE");
define("_VERVIEWS","TO_TRANSLATE");
define("_VER_PERFIL","Koopprofiel");
define("_VIEW","View");
define("_VIEWED","Weergegeven");
define("_VIEWS","TO_TRANSLATE");
define("_VIEWS_LST","TO_TRANSLATE");
define("_VIEW_FRONT_IN","TO_TRANSLATE");
define("_WANT_SELL","Ik wil verkopen");
define("_WANT_SELL_TXT","Verkrijg voor uw woning een prijs voor de werkelijke waarde!");
define("_WDAY","W");
define("_WEDNESDAY","Woensdag");
define("_WORDS_TO_FIND","Zoeken naar woorden");
define("_XMLNAV","TO_TRANSLATE");
define("_XMLOUTPUT","TO_TRANSLATE");
define("_XMLPRT","TO_TRANSLATE");
define("_XSLFILE","TO_TRANSLATE");
define("_XSLPRT","TO_TRANSLATE");
define("_YEAR","Jaar");
define("_YEARS","Jaar");
define("_YOUR_LOAN","Bereken uw hypotheek");
define("_ZIP_FILE","TO_TRANSLATE");
?>