<?php
/**
 * ReOS is a vertical software for real estates.
 * Copyright 2010 IT ELAZOS S.L.
 *
 * This file is part of ReOS v2.x.x.
 *
 * ReOS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ReOS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with ReOS.  If not, see <http://www.gnu.org/licenses/>.
 **/


//File generated from a txt file at : Thu, 18 Feb 2010 12:02:08 +0100

define("_0","否");
define("_1","是");
define("_ABOUTUS","關於我們");
define("_ACCOUNTS","賬戶");
define("_ACONSULTAR","在要求中");
define("_ACTIVE","使用中");
define("_ACTIVE_ALL","TO_TRANSLATE");
define("_ACTIVITIES_LIST","活動標籤列表");
define("_ADD","加入");
define("_ADDIMG","加入圖像");
define("_ADDIMGNOT","新圖像");
define("_ADDPOINT","Google Maps");
define("_ADDPRICELST","加添價格表");
define("_ADDPRICEPRD","加添產品和價格");
define("_ADDT_FILES","附加檔案");
define("_ADD_ACCOUNT","加入賬戶");
define("_ADD_CITY","TO_TRANSLATE");
define("_ADD_COMDAD","TO_TRANSLATE");
define("_ADD_CONTACT","TO_TRANSLATE");
define("_ADD_COUNTRY","TO_TRANSLATE");
define("_ADD_CTG","加入目錄");
define("_ADD_DEPT","加入部門");
define("_ADD_GAL","加入圖庫");
define("_ADD_IMG_GAL","加入圖像到圖庫");
define("_ADD_IMMO","加入物業");
define("_ADD_MAILING","加上郵件");
define("_ADD_NEW","加入新聞");
define("_ADD_PERFIL","加入買家簡介");
define("_ADD_PERM","加入角式 / 簡介");
define("_ADD_PICTURE","加入圖像");
define("_ADD_POSITION","加入雇員");
define("_ADD_PROD","加入產品");
define("_ADD_PROV","TO_TRANSLATE");
define("_ADD_SCR","加入Screen");
define("_ADD_SDAY","加入新日期");
define("_ADD_SEASON","加入新季節");
define("_ADD_TICKET","加入票據");
define("_ADD_TK_CTG","TO_TRANSLATE");
define("_ADD_USER","加入用戶");
define("_ADD_VAL","加入價值");
define("_ADD_VIEW","加入View");
define("_ADD_ZONA","新地區");
define("_ADMIN","管理");
define("_ALL_ACCOUNTS","全部賬戶");
define("_ALL_IMMOS","全部物業");
define("_ALL_NEWS","全部新聞");
define("_ALL_TICKETS","全部票據");
define("_ANY","任何");
define("_APP_FILE","應用程式檔案");
define("_APRIL","四月");
define("_ASIGN_POB","選擇期望的城市");
define("_AUGUST","八月");
define("_AVG_DAY_HITS","平均每天訪問次數");
define("_AVG_DAY_ROBOTS","平均每天用搜索器次數");
define("_AVG_DAY_VISITS","平均每天訪問次數");
define("_BACK","返回");
define("_BACKUP","備份");
define("_BOOK","訪問冊子");
define("_BOOKINGS","TO_TRANSLATE");
define("_BOOKING_VALID","TO_TRANSLATE");
define("_BOOKVALID","TO_TRANSLATE");
define("_BOOK_ISVALID","TO_TRANSLATE");
define("_BOOK_TXT","用頁尾部足標表格分享你的意見. 多謝你的提供.");
define("_BORRAR","刪除");
define("_BUGGET","預算支出金額 "._CURRENCY."");
define("_BUSY","煩忙");
define("_BUSYBOOKING","TO_TRANSLATE");
define("_BUYERS_ACCOUNTS","搜尋買家");
define("_BUY_GUIDE","購物指南");
define("_CALC","計算");
define("_CALC_INM","按揭貸款計算");
define("_CALC_LOAN_PAYMENTS","按揭貸款付賬計算");
define("_CALENDAR","日常事務");
define("_CAPTCHA","TO_TRANSLATE");
define("_CATALOG","目錄");
define("_CHANGE_PASS","更改密碼");
define("_CHARSET","UTF-8");
define("_CMT_CSSFILE","層疊樣式表");
define("_CMT_IMAG","圖像及閃客檔案處理程式");
define("_CMT_XMLNAV","XML 檔案用於規定各頁的佈局.");
define("_CMT_XMLOUTPUT","應用程式產生出來的檔案,用作輸入 XSL 轉變檔案");
define("_CMT_XMLPRT","XML 檔案用於規定各列印頁的佈局.");
define("_CMT_XSLFILE","XSL 轉變檔案 - 輸入應XML用程式的輸出檔案 .");
define("_CMT_XSLPRT","XSL 轉變檔案. 用於輸入XML應用程式的輸出檔案.");
define("_COD","TO_TRANSLATE");
define("_COD_CATEGORY","目錄編碼");
define("_COD_LANG","語文");
define("_COD_PRODUCT","產品編碼");
define("_COMDAD_NAME","TO_TRANSLATE");
define("_COMO","我會見你...");
define("_COM_APER","設定傭金");
define("_CONFIRM","驗證登記");
define("_CONNECTED_AS","登錄");
define("_CONTACTAR","接洽");
define("_CONTACTS","TO_TRANSLATE");
define("_CONTENTS","內容");
define("_CPASS","密碼");
define("_CSSCONFIG","CSS 檔案");
define("_CSSFILE","CSS 檔案");
define("_CSS_DELETED","已刪去CSS檔案");
define("_CTG","目錄");
define("_CTGS","家庭");
define("_CTG_BELONGS","所屬家庭");
define("_CTG_HAS_PROD","目錄內有產品,先刪去 產品");
define("_CTG_NO_EXIST","不存在任何家庭");
define("_CTG_NO_NAME","目錄是強制性必須提供的");
define("_CURRENT_PASS","目前使用的密碼");
define("_CUSTOMER","賬戶");
define("_CUSTZONE","客戶區");
define("_DATE","日期");
define("_DATEMP","機構資料");
define("_DATETIME_SQL","'%d/%m/%Y - %H:%i'");
define("_DATE_FORMAT","d/m/Y");
define("_DATE_FT","日期");
define("_DATE_SQL","'%d/%m/%Y'");
define("_DATOS_PERS","個人資料");
define("_DATPERS","個人資料");
define("_DAY","日");
define("_DEACTIVE_ALL","TO_TRANSLATE");
define("_DECEMBER","十二月");
define("_DEC_POINT",".");
define("_DELETE","刪除");
define("_DELETED","已成功刪除");
define("_DEPT","部門");
define("_DEPTS","部門");
define("_DESC_CATEGORY","說明");
define("_DESC_PROD","說明");
define("_DO_CALC","按揭貸款計算");
define("_DTL","TO_TRANSLATE");
define("_DTL_ACCOUNT","賬戶資料");
define("_DTL_ACCPERFIL","買家簡介資料");
define("_DTL_PROP","物業資料");
define("_DT_CREATE","創建日期");
define("_DT_END","結束日期");
define("_DT_SENT","送出日期");
define("_DT_START","開始日期");
define("_DT_VAL","過期日子");
define("_DT_VALID","有效");
define("_EDIT","編改");
define("_EDTACC","賬戶");
define("_EDTCOMDAD","TO_TRANSLATE");
define("_EDTCONTACT","TO_TRANSLATE");
define("_EDTCOUNTRY","TO_TRANSLATE");
define("_EDTCTG","產品目錄");
define("_EDTGAL","畫廊");
define("_EDTHIMMO","假日寓所物業");
define("_EDTHTML","編改頁");
define("_EDTIMMO","物業");
define("_EDTIMMOGAL","物業圖像");
define("_EDTLABEL","TO_TRANSLATE");
define("_EDTLST","價值");
define("_EDTMAILING","郵件詳述");
define("_EDTMSG","TO_TRANSLATE");
define("_EDTORG","部門");
define("_EDTPERFIL","買家簡介");
define("_EDTPERM","簡介");
define("_EDTPOB","TO_TRANSLATE");
define("_EDTPOSITION","雇員詳細資料");
define("_EDTPRD","產品");
define("_EDTPRDGAL","物業圖像");
define("_EDTPREF","TO_TRANSLATE");
define("_EDTPRICELST","編改價格表");
define("_EDTPRICEPRD","編改價格");
define("_EDTPROV","TO_TRANSLATE");
define("_EDTSCR","Screen");
define("_EDTSDAY","日子及價格");
define("_EDTSEASON","季節詳情");
define("_EDTTICKET","編改票據");
define("_EDTTKCTG","TO_TRANSLATE");
define("_EDTTKEMAIL","TO_TRANSLATE");
define("_EDTUSER","用戶");
define("_EDTVIEW","View");
define("_EDT_ACCOUNT","編改賬戶");
define("_EDT_CONTACT","TO_TRANSLATE");
define("_EDT_CTG","編改家庭");
define("_EDT_DEPT","編改部門");
define("_EDT_EMPL","編改雇員資料");
define("_EDT_GAL","編改圖庫");
define("_EDT_IMMO","編改物業");
define("_EDT_MAILING","編改郵件");
define("_EDT_NEW","編改新聞");
define("_EDT_PERM","編改角式 / 簡介");
define("_EDT_PROD","編改產品");
define("_EDT_SCR","編改Screen");
define("_EDT_USER","編改用戶");
define("_EDT_VAL","編改價值");
define("_EDT_VIEW","編改View");
define("_EMPL","雇員");
define("_EMPLES","TO_TRANSLATE");
define("_ENVIAR","發送");
define("_EQUIP_LIST","假日租賃器材用品標籤列表");
define("_ERROR_CAPTCHA","檢查字詞驗證");
define("_ERROR_CHECK_PSW","密碼錯誤");
define("_ERROR_CONTENT_MAILING","內容是強制性必須提供的");
define("_ERROR_CURRENT_PSW","目前密碼是錯誤的");
define("_ERROR_DATS","取存資料錯誤");
define("_ERROR_DELETE","刪除過程中出錯");
define("_ERROR_DIR_GAL","創建圖庫目錄過程中出錯");
define("_ERROR_EMAIL_USER","郵電是強制性必須提供的");
define("_ERROR_ES_IN","你必須輸入西班牙的值");
define("_ERROR_IN","錯誤了");
define("_ERROR_INSERT","加插資料過程中出錯");
define("_ERROR_LAST_USER","你是不容許刪除組織內最後一位用戶的");
define("_ERROR_NAME_MAILING","郵件名稱是強制性必須提供的");
define("_ERROR_NAME_USER","完整名稱是強制性必須提供的");
define("_ERROR_NM","你必須輸入名稱");
define("_ERROR_NM_PROFILE","名稱必須最少是六個字");
define("_ERROR_NOPOB","找不到任何城市");
define("_ERROR_NUM_DOM","房間數目是強制性必須提供的");
define("_ERROR_NUM_PARKING","輸入停車位數量");
define("_ERROR_NUM_WC","沐浴室數目是強制性必須提供的");
define("_ERROR_OBSRV","你必須輸入說明");
define("_ERROR_OPEN_DIR","打不開目錄夾,");
define("_ERROR_OPEN_FILE","開啟檔案有錯誤");
define("_ERROR_PASSUSR_NULL","用戶名稱和密碼可以是空白的或兩者皆有值");
define("_ERROR_PROCESS","處理出現錯誤");
define("_ERROR_PSW_ERROR","密碼錯誤 ! 在兩空白欄位內重新輸入密碼");
define("_ERROR_PSW_NOSTR","密碼只可用英文字母");
define("_ERROR_PSW_SHORT","密碼長度最少要六個字");
define("_ERROR_PSW_USERNAME","密碼和用戶名稱不可以一致");
define("_ERROR_SUBJ_MAILING","主題是強制性必須提供的");
define("_ERROR_SUPERF","土地面績 平米 或 零");
define("_ERROR_SUPERF_CONST","面績 平米 或 零");
define("_ERROR_SUPERT","輸入陽臺面績或 '0' ,如果沒有陽臺");
define("_ERROR_TELF1_USER","電話號碼是強制性必須提供的");
define("_ERROR_TXT_CONTENT","你必須輸入訊息.");
define("_ERROR_UPDATE","更新過程中出錯");
define("_ERROR_USNAME_EXIST","用戶名稱己存在 ! 請另外再選其它用戶名稱.");
define("_ERROR_USRNAME_EXISTS","用戶名稱已存在 !");
define("_ERROR_USRNAME_NOSTR","用戶名稱只可用英文字母");
define("_ERROR_USRNAME_SHORT","使用者戶名稱長度最少要六個字");
define("_ER_SELET_TBL","選擇資料表有錯誤");
define("_FDAY","F");
define("_FEBRUARY","二月");
define("_FECHA_FT","日期");
define("_FG_HIDDEN","TO_TRANSLATE");
define("_FG_PRIVATE","TO_TRANSLATE");
define("_FIND","搜尋");
define("_FIND_BY_CITIES","用城市名稱搜索");
define("_FIND_BY_CRITERIA","標準搜索");
define("_FIND_BY_TPPROP","用物業類型搜索");
define("_FINPAGINA","");
define("_FOLDER","文件夾");
define("_FOUND","找尋到");
define("_FRIDAY","星期五");
define("_FRONT","首頁");
define("_FULL_NAME","完整名稱");
define("_GALLERIES","圖像圖庫");
define("_GALLERY","圖庫");
define("_GALS","圖庫");
define("_GAL_LST","圖庫清單");
define("_GAST_GEST","代理支出, 公證行費用, 登記費用.<br/>(由經理人而定) 最低:");
define("_GENERAL_LAYOUT","主佈局頁");
define("_GEN_LANG","安裝的語文已經改變");
define("_GESTLANGS","語文工具");
define("_GST_COMPRA","購買物業開支");
define("_GST_HIPOT","按揭貸款開支");
define("_GUIA","指南");
define("_HELP","說明");
define("_HOME","首頁");
define("_HOMEPG","主頁");
define("_HOUR","時間");
define("_IDIOMA","zh-tw");
define("_ID_CATEGORY","目錄標記");
define("_ID_POSITION","指派給");
define("_ID_TICKET","票據標籤");
define("_IMAG","圖像及閃支客檔案");
define("_IMG","圖像");
define("_IMGCONFIG","標籤圖像");
define("_IMGHOME","head.jpg");
define("_IMGS_NOT","新的圖像");
define("_IMG_FILE_ERROR","錯誤的格式 (重音符號, 空白, 等等...)  或大於");
define("_IMG_FRONT","首頁圖像");
define("_IMG_INT_1","內含圖像 1");
define("_IMG_INT_2","內含圖像 2");
define("_IMG_INT_3","內含圖像 3");
define("_IMG_PORT","主題圖像");
define("_IMMO","物業資料");
define("_IMMOS","物業");
define("_IMP_ACTOS","稅務交易法定文件:");
define("_IMP_COMPRA","Tax Patrimonial Transmissions 或 加值稅");
define("_IMP_ENTR","給出總額");
define("_IMP_SOL","按揭貸款賬戶");
define("_IND_ACTIVE","活躍");
define("_IND_MAILING","郵件");
define("_IND_OFERTA","提供");
define("_IND_PISCINA","泳池");
define("_INFOLEGAL","法律資料");
define("_INSERTED","加插資料成功");
define("_INSIDE","內含");
define("_INTROS_LIST","介紹標籤列表");
define("_INT_BANC","銀行利率");
define("_INT_CAPACITY","Capacity Pers");
define("_INT_PERS","TO_TRANSLATE");
define("_INT_SUPERFICIE","平米土地 ");
define("_INT_SUPERFICIE_CONST","面績 平米");
define("_INT_TERRACE","平米陽臺");
define("_IN_NAME_ACCOUNT","賬戶名稱是強制性必須提供的");
define("_IN_NAME_GAL","圖庫名稱是強制性必須提供的");
define("_IN_NAME_IMMO","參考是強制性必須提供的");
define("_IN_NAME_ORG","TO_TRANSLATE");
define("_IN_NOT_RESUM","摘要是強制性必須提供的");
define("_IN_NOT_TITLE","標題是強制性必須提供的");
define("_IN_POB_IMMO","你必須選擇一城市. 如沒有列出,請接洽管理員");
define("_IN_POB_ORG","你必須選擇一城市");
define("_IN_SUBJECT","輸入主題");
define("_JANUARY","一月");
define("_JULY","July");
define("_JUNE","六月");
define("_KEYWORDS_ADM","TO_TRANSLATE");
define("_LABELS_LIST","節目標籤列表");
define("_LANGS","語文");
define("_LANGUAGE","語文");
define("_LATTITUD","TO_TRANSLATE");
define("_LBL_SEASONS","季節");
define("_LOGIN_FAILED","無效的使用者名稱或密碼");
define("_LOGIN_NOW","進入");
define("_LOGOUT","登出");
define("_LONGITUD","TO_TRANSLATE");
define("_LOVS","TO_TRANSLATE");
define("_LSTMAILING","收郵件客戶列表");
define("_LSTUSER","用戶清單");
define("_M2","M2");
define("_M2_TERRACE","平米陽臺");
define("_M2_TERRENO","平米土地");
define("_MAILING","郵件活動");
define("_MAIL_BKVALID","TO_TRANSLATE");
define("_MAIL_BKVALID_TXT","TO_TRANSLATE");
define("_MAIL_CONFIRM","你會收到我們發出的郵電用於驗證你的登記.");
define("_MAIL_FORMAT","郵電檔案格式有錯誤");
define("_MAIL_HRECEV","我們己收到你的要求");
define("_MAIL_NMSG","我們會很快處理你的要求");
define("_MAIL_NOTI","收到確認通知");
define("_MAIL_REM","登入資料");
define("_MAIL_REM_TXT","你好, 

你登錄的資料是 :");
define("_MAIL_SUBS","登記資料");
define("_MAIL_SUBS_TXT","你好, 

用給出的網址驗證你的登記  :

");
define("_MAIN_IMG","主題圖像");
define("_MANDATORY","TO_TRANSLATE");
define("_MAPINIT","TO_TRANSLATE");
define("_MARCH","三月");
define("_MAY","五月");
define("_MDAY","M");
define("_MKT","郵件");
define("_MNU_ADM","選單");
define("_MONDAY","星期一");
define("_MONTH","月");
define("_MSG","訊息");
define("_MY_ACCOUNTS","我的賬戶");
define("_MY_IMMOS","我的物業");
define("_MY_NEWS","我的新聞");
define("_MY_PROFILE","我的概況");
define("_MY_TICKETS","我的票據");
define("_MY_TK_STATS","TO_TRANSLATE");
define("_NAME","TO_TRANSLATE");
define("_NAME_ACCOUNT","賬戶名稱");
define("_NAME_CATEGORY","目錄");
define("_NAME_GAL","圖庫名稱");
define("_NAME_MAILING","郵件名稱");
define("_NAME_ORG","辦公室");
define("_NAME_POB","城市");
define("_NAME_POSITION","職位");
define("_NAME_PRICE_LST","列表名稱");
define("_NAME_PRODUCT","產品名稱");
define("_NAME_SEASONS","季節名稱");
define("_NAME_USER","雇員  / 用戶名稱");
define("_NESPECIAL","我們特別推荐");
define("_NEW","新");
define("_NEWS","新聞");
define("_NEWSLST","新聞列表");
define("_NEWS_EVENTS","新聞和活動");
define("_NEWUSER","新用戶");
define("_NEW_PASSWORD","新密碼");
define("_NEW_POS","在首頁");
define("_NEW_PROP","全新物業");
define("_NEW_RESUM","簡報");
define("_NEW_TITLE","標題");
define("_NEW_TXT","文字");
define("_NEXT","下一筆");
define("_NM_CONTACT","TO_TRANSLATE");
define("_NM_PROFILE","名稱");
define("_NM_SCREEN","Screen");
define("_NM_TK_CTG","TO_TRANSLATE");
define("_NM_VIEW","View");
define("_NOREGUSERS","收郵件者清單中沒有登記賬戶");
define("_NOSELECTED","未選中");
define("_NOTFOUND","TO_TRANSLATE");
define("_NOTI","新聞");
define("_NOTICIA","看新聞");
define("_NOVED","最新物業");
define("_NOVED_TXT","最新物業 ....");
define("_NOVEMBER","十一月");
define("_NO_ACCOUNT","找不到賬戶");
define("_NO_AV_LG","目前的語文不包含這頁內容 ");
define("_NO_COD","編碼是強制性必須提供的");
define("_NO_CONTACT","TO_TRANSLATE");
define("_NO_CTG","找不到任何目錄");
define("_NO_EMPL","找不到任何雇員");
define("_NO_GALS","找不到任何圖庫");
define("_NO_IMG_FRONT","圖庫沒有主題圖像.你必須選擇一主題圖像,才可發行你的提供內容.");
define("_NO_IMG_INT_1","沒有內含圖像 1");
define("_NO_IMG_INT_2","沒有內含圖像 2");
define("_NO_IMG_INT_3","沒有內含圖像 3");
define("_NO_IMG_PORT","沒有主題圖像");
define("_NO_IMMO","找不到物業");
define("_NO_MAILING","找不到郵件");
define("_NO_MEMBERS","你的群組沒有任何成員");
define("_NO_NOTS","沒有新聞");
define("_NO_ORGS","找不到任何群組");
define("_NO_PRICE_LST","沒有價格表");
define("_NO_PROD","找不到任何產品");
define("_NO_PSTS","沒有職位");
define("_NO_SEASONS","無季節性");
define("_NO_TICKET","找不到票據");
define("_NUMORDER","順序");
define("_NUM_DORMITORIO","睡房");
define("_NUM_DORMITORIOS","睡房");
define("_NUM_HITS","己閱讀頁數");
define("_NUM_ORDER","顯示定單");
define("_NUM_PARKING","停車間");
define("_NUM_PARKINGS","停車位");
define("_NUM_ROBOTS","搜索器");
define("_NUM_SENT","送出次數");
define("_NUM_VISITS","訪問");
define("_NUM_WC","沐浴室");
define("_NUM_WCS","沐浴室");
define("_OBSERV_LIST","假日租賃備忘標籤列表");
define("_OCTOBER","十月");
define("_OF","於");
define("_OFICINAS","辦公室");
define("_ONLOAD","TO_TRANSLATE");
define("_OPINION","分享你的意見");
define("_OPTIONAL","(備用)");
define("_ORDER","順序");
define("_ORDERBY","順序");
define("_ORG","組織");
define("_ORG_HAS_SUBORG","部門中擁有次部門, 請先刪去次部門");
define("_ORG_LST","組織架構");
define("_OUTAPP","應用程式輸出");
define("_PAGE","頁");
define("_PAGO_MEN","每月還款");
define("_PAGS","頁");
define("_PARAMS","參數");
define("_PARENTCTG_DCHILDREN","目錄擁有次目錄, 請先刪去次目錄");
define("_PASSWORD","密碼");
define("_PATH_IMAGE","圖像");
define("_PERMS","角式");
define("_PERMS_HAS_SCR","Profile has screens assigned.");
define("_PICTURES","圖像");
define("_PIEPAGINA","Powered by <a href=\"http://reos.elazos.com\">ReOS "._VERSION."</a> and released under the <a href=\"http://www.fsf.org/licensing/licenses/agpl-3.0.html\">GNU/AGPLv3 License.</a>");
define("_PLEASE_LOGIN","輸入你的使用者名稱和密碼");
define("_POBLACIONES","使用中的城市");
define("_POBS","用城市名搜索");
define("_POPHOST","TO_TRANSLATE");
define("_POPPASS","TO_TRANSLATE");
define("_POPUSER","TO_TRANSLATE");
define("_POSITION","職位");
define("_POS_IMG_PORT","首頁位置");
define("_PRECIO","價格");
define("_PRECIO_ALQUILER","出租價格 "._CURRENCY."");
define("_PRECIO_COMPRA","出售價格 "._CURRENCY."");
define("_PREFERE","喜好");
define("_PREF_POBS","喜好的城市");
define("_PREVIOUS","前一筆");
define("_PRE_VIVIE","物業價格");
define("_PRICE_FROM","起始價格");
define("_PRICE_MAX","最高價格 "._CURRENCY."");
define("_PRICE_MIN","最低價格 "._CURRENCY."");
define("_PRIORITY","TO_TRANSLATE");
define("_PROCESS_OK","成功處理");
define("_PRODS","產品");
define("_PROFS","角式 / 簡介");
define("_PROP_ACCOUNT","賬戶的物業");
define("_PROV_NAME","省份");
define("_PRT_LAYOUT","列印佈局頁");
define("_PST_ELEMTS","職位欄已有了內容. 請先刪去內容");
define("_PUBLI_YOUR","發佈你的物業");
define("_READMORE","閱讀更多 ...");
define("_RECOM","推荐");
define("_REFERERS","推薦人");
define("_REF_IMMO","參考");
define("_REF_TICKET","TO_TRANSLATE");
define("_REGS_TXT","為了避免他用許戶以你的名義登記,你將會收到我們發出的郵電用作確認登記.儘管你在客戶區登記填表程交. 你的郵電將成為你的用戶名稱.");
define("_REGUSERS","把登記賬戶加入收郵件者清單");
define("_REM_CONFIRM","查看你的郵電.");
define("_REM_TXT","我們將會寄出你登錄資料到你的郵電.");
define("_REM_USR","遺失了密碼嗎?");
define("_RESERVATION","TO_TRANSLATE");
define("_RESERV_CONFIRM","TO_TRANSLATE");
define("_RESTORE","還原備份");
define("_RESULTS","搜索結果");
define("_RE_NEW_PASS","從新輸入新密碼");
define("_RE_PASSWORD","從新輸入密碼");
define("_ROOT_DEPT","初設部門");
define("_ROWS","項目");
define("_SADAY","S");
define("_SATURDAY","星期六");
define("_SAT_DEPT","客戶服務");
define("_SAVE","存檔");
define("_SCREEN","Screen");
define("_SCREENS","Screens");
define("_SCREEN_HAS_VIEW","Screen has views assigned.");
define("_SDAY","S");
define("_SEARCH_TITLE","搜尋");
define("_SEASONS","假日租賃的季節");
define("_SEE2PRINT","列印");
define("_SEE_CYRILIC","顕示古代斯拉夫語字母");
define("_SEE_LATIN1","顕示歐美字母");
define("_SEGUROS","保險");
define("_SELECT","選擇");
define("_SELECTED","選擇");
define("_SELECTLANGUAGE","選擇語文!");
define("_SEND_OUTLOOK","發送到Outlook");
define("_SEPTEMBER","九月");
define("_SERVICES_LIST","服務標籤列表");
define("_SET_ACTIVITIES","活動");
define("_SET_EQUIP","器材");
define("_SET_IMG_FRONT","選擇主題圖像");
define("_SET_INTRO","引入介紹");
define("_SET_OBSERV","備忘錄");
define("_SET_PROPERTIES","物業");
define("_SET_SERVICES","服務");
define("_SHOW_GAL","顯示圖庫");
define("_SINFO","要求訊息");
define("_SINFO_ADVERT","一般常規, 任何你所提供的資訊, 只用於此網站. 除非先得到你的同意,資料絕不會供給第三方作其他用途.");
define("_SINFO_CONFIRM","成功送出接洽表單.");
define("_SINFO_TXT","請提供你個人的資料,我們將盡快和你聯絡.");
define("_SLOGAN","地產管理");
define("_START","主頁");
define("_STATE","洲");
define("_STATISTICS","存取統計");
define("_SUBJECT","主旨");
define("_SUBS","登記");
define("_SUBS_PHRASE","訂閱我們的新聞怏報");
define("_SUBS_TXT","為了避免其他用戶以你的名義登記,你將會收到我們發出的郵電用作確認登記. 你憑藉此登記表格訂閱新聞快報.");
define("_SUNDAY","星期日");
define("_SUPPORT","支援");
define("_TDAY","T");
define("_TEAM_ACCOUNTS","我群組的賬戶");
define("_TEAM_IMMOS","我群組的物業");
define("_TEAM_TICKETS","我群組的票據");
define("_THDAY","TH");
define("_THEMES","TO_TRANSLATE");
define("_THOUSANDS_SEP",",");
define("_THUMB","照片");
define("_THURSDAY","星期四");
define("_TICKETS","票據");
define("_TITLE_LOGIN","管理員區");
define("_TK_CTG_LST","TO_TRANSLATE");
define("_TOCLOSE","TO_TRANSLATE");
define("_TODO","動作");
define("_TOEND","完結");
define("_TOTAL","總額");
define("_TOT_GST","開支總額 :");
define("_TOY_INTERES","接洽這物業的業主");
define("_TP_PRICE","價格種類");
define("_TP_PROPIEDAD","物業類型");
define("_TP_SDAYS","類型");
define("_TP_SEND","送出類型");
define("_TP_SEND_TO","送到");
define("_TP_SERVICIO","交易");
define("_TP_STATE","州");
define("_TP_VAT","加值稅 %");
define("_TUESDAY","星期二");
define("_TXT_ADDRESS1","地址");
define("_TXT_AGE","年齡");
define("_TXT_ASUNT","主題");
define("_TXT_COMMENT","評語");
define("_TXT_COMO","你如何找到我們呢 ?");
define("_TXT_CONTENT","內容");
define("_TXT_COUNTRY","國家");
define("_TXT_CP","郵政區號");
define("_TXT_DESC","說明");
define("_TXT_EMAIL","郵電");
define("_TXT_EMAIL1","郵電");
define("_TXT_ES","價值");
define("_TXT_FAX","傳真號碼");
define("_TXT_MAILING","用郵件活動你可以向你的客戶們發出大量的郵電");
define("_TXT_OBSRV","說明");
define("_TXT_POBLACION","城市");
define("_TXT_SEARCH","搜索字句");
define("_TXT_SIGN","TO_TRANSLATE");
define("_TXT_SUBJECT","主題");
define("_TXT_TELF1","電話號碼");
define("_TXT_TELF2","電話號碼 #2");
define("_TXT_TITLE"," 標題");
define("_TXT_UNREG","你收到此訊息因為你有意訂閱我們的新聞郵件. 假如你不想再收到更多的郵電 :");
define("_TXT_URL","網址");
define("_TXT_WEB","網頁");
define("_TXT_ZONA","地區");
define("_UMONTH","月");
define("_UNREG","終止訂閱");
define("_UNTITLED","沒有標題");
define("_UPDATE","更新");
define("_UPDATED","已成功更新");
define("_USED_PROP","二手物業");
define("_USER","用戶");
define("_USERNAME","用戶");
define("_USER_DELETED","已成功刪去用戶");
define("_USER_HAS_PST","用戶已有了職位內容. 請先刪去職位");
define("_USER_INSERTED","已成功加入用戶");
define("_USER_TYPE","類型");
define("_USR_BOOK_NOVALID","TO_TRANSLATE");
define("_USR_CONFIRM","你的登記有效.");
define("_USR_NOCONFIRM","登記過程出錯了.");
define("_USR_NOUNREG","你終止訂閱的指示還沒有經過驗證. 如果你收到更多郵電,請跟客務部接洽.");
define("_USR_UNREG","你終止訂閱的指示在處理中.");
define("_VALUE","TO_TRANSLATE");
define("_VERACCS","賬戶搜索");
define("_VERBOOKINGS","TO_TRANSLATE");
define("_VERCONFIG","標籤配置");
define("_VERCOUNTRIES","TO_TRANSLATE");
define("_VERGAL","畫廊");
define("_VERHTML","內容");
define("_VERIMMO","搜索物業");
define("_VERINTROS","推介標籤");
define("_VERLABELS","TO_TRANSLATE");
define("_VERMAILINGS","郵件活動");
define("_VERNOT","新聞及活動");
define("_VERORGS","組織");
define("_VERPERMS","角式列表 / 簡介");
define("_VERPOBS","使用中的城市");
define("_VERPRD","產品");
define("_VERPREFS","TO_TRANSLATE");
define("_VERPRICELST","價格表");
define("_VERPRICEPRD","產品和價格");
define("_VERPROPER","推介物業標籤");
define("_VERSCR","Screen清單t");
define("_VERSEASONS","季節列表");
define("_VERTICKETS","TO_TRANSLATE");
define("_VERTKCTGS","TO_TRANSLATE");
define("_VERTKEMAILS","TO_TRANSLATE");
define("_VERUSERS","用戶名單");
define("_VERVIEWS","Views清單");
define("_VER_PERFIL","賬戶");
define("_VIEW","View");
define("_VIEWED","觀看過");
define("_VIEWS","Views");
define("_VIEWS_LST","TO_TRANSLATE");
define("_VIEW_FRONT_IN","新");
define("_WANT_SELL","我想出售");
define("_WANT_SELL_TXT","獲取你物業的真正市值");
define("_WDAY","W");
define("_WEDNESDAY","星期三");
define("_WORDS_TO_FIND","搜尋字句");
define("_XMLNAV","XML 佈局檔案");
define("_XMLOUTPUT","XML 輸出檔案");
define("_XMLPRT","XML 列印佈局檔案");
define("_XSLFILE","XSL 轉變檔案");
define("_XSLPRT","XSL 列印佈局檔案");
define("_YEAR","年");
define("_YEARS","年數");
define("_YOUR_LOAN","你的借貸");
define("_ZIP_FILE","ZIP壓縮檔案");
?>