<?php
/**
 * ReOS is a vertical software for real estates.
 * Copyright 2010 IT ELAZOS S.L.
 *
 * This file is part of ReOS v2.x.x.
 *
 * ReOS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ReOS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with ReOS.  If not, see <http://www.gnu.org/licenses/>.
 **/


//File generated from a txt file at : Thu, 18 Feb 2010 12:02:08 +0100

define("_0","Non");
define("_1","Oui");
define("_ABOUTUS","Qui sommes-nous");
define("_ACCOUNTS","Clients");
define("_ACONSULTAR","Consulter");
define("_ACTIVE","Actif");
define("_ACTIVE_ALL","TO_TRANSLATE");
define("_ACTIVITIES_LIST","Liste d'étiquettes d'Activités");
define("_ADD","TO_TRANSLATE");
define("_ADDIMG","Ajouter Photo");
define("_ADDIMGNOT","Photos Nouvelles");
define("_ADDPOINT","Google Maps");
define("_ADDPRICELST","Ajouter Liste de Prix");
define("_ADDPRICEPRD","Ajouter Produits/Prix");
define("_ADDT_FILES","FICHIERS ADDITIONNELS");
define("_ADD_ACCOUNT","Ajoutez Client");
define("_ADD_CITY","TO_TRANSLATE");
define("_ADD_COMDAD","TO_TRANSLATE");
define("_ADD_CONTACT","TO_TRANSLATE");
define("_ADD_COUNTRY","TO_TRANSLATE");
define("_ADD_CTG","Ajoutez Catégorie");
define("_ADD_DEPT","Ajoutez Département");
define("_ADD_GAL","Ajoutez Gallerie");
define("_ADD_IMG_GAL","Ajoutez image à la galerie");
define("_ADD_IMMO","Ajouter Propriété");
define("_ADD_MAILING","Ajoutez Mailing");
define("_ADD_NEW","Ajoutez Nouvelle");
define("_ADD_PERFIL","Ajoutez Profil d'Achat");
define("_ADD_PERM","TO_TRANSLATE");
define("_ADD_PICTURE","Ajoutez Image");
define("_ADD_POSITION","Ajouter Employé");
define("_ADD_PROD","Ajoutez Produit");
define("_ADD_PROV","TO_TRANSLATE");
define("_ADD_SCR","TO_TRANSLATE");
define("_ADD_SDAY","Ajouter Jours");
define("_ADD_SEASON","Ajouter Nouvelle Saison");
define("_ADD_TICKET","Ajouter Ticket");
define("_ADD_TK_CTG","TO_TRANSLATE");
define("_ADD_USER","Ajouter Utilizateur");
define("_ADD_VAL","Ajouter Valeur");
define("_ADD_VIEW","TO_TRANSLATE");
define("_ADD_ZONA","Nouvelle Zone");
define("_ADMIN","Administration");
define("_ALL_ACCOUNTS","Tous les Clients");
define("_ALL_IMMOS","Toutes les Propriétés");
define("_ALL_NEWS","Toutes les Nouvelles");
define("_ALL_TICKETS","TO_TRANSLATE");
define("_ANY","Indifférent");
define("_APP_FILE","TO_TRANSLATE");
define("_APRIL","Avril");
define("_ASIGN_POB","Choisissez les villes désirées");
define("_AUGUST","Août");
define("_AVG_DAY_HITS","Moyenne Quotidiennes de Page Vues");
define("_AVG_DAY_ROBOTS","Moyenne Quotidiens des Moteurs de Recherche");
define("_AVG_DAY_VISITS","Moyenne Quotidiennes de Visites");
define("_BACK","Revenir en arrière");
define("_BACKUP","Backup");
define("_BOOK","TO_TRANSLATE");
define("_BOOKINGS","TO_TRANSLATE");
define("_BOOKING_VALID","TO_TRANSLATE");
define("_BOOKVALID","TO_TRANSLATE");
define("_BOOK_ISVALID","TO_TRANSLATE");
define("_BOOK_TXT","TO_TRANSLATE");
define("_BORRAR","Effacer");
define("_BUGGET","Budget "._CURRENCY."");
define("_BUSY","Occupé");
define("_BUSYBOOKING","Property is booked for your selected dates");
define("_BUYERS_ACCOUNTS","Recherche d'Acheteurs");
define("_BUY_GUIDE","Guide Achat");
define("_CALC","Calculer");
define("_CALC_INM","Calcul de remboursements mensuels de l'emprunt immobilier");
define("_CALC_LOAN_PAYMENTS","Calcul de remboursements mensuels de l'emprunt immobilier");
define("_CALENDAR","Calendrier");
define("_CAPTCHA","TO_TRANSLATE");
define("_CATALOG","Catalogue");
define("_CHANGE_PASS","Changer le Mot de passe");
define("_CHARSET","UTF-8");
define("_CMT_CSSFILE","Fichier CSS - Cascading Style Sheets");
define("_CMT_IMAG","Gestion d'images et fichiers flash");
define("_CMT_XMLNAV","Fichier XML qui définit la structure de chaque page");
define("_CMT_XMLOUTPUT","Fichier produit par le logicielle comme entrée du fichier XSL Transformation");
define("_CMT_XMLPRT","Gestion d'images et fichiers flash de la conception graphic");
define("_CMT_XSLFILE","Fichier XSL de Transformation - Prend comme entrée le fichier XML Output");
define("_CMT_XSLPRT","Fichier XSL de Transformation - Prend comme entrée le fichier XML Output");
define("_COD","Code");
define("_COD_CATEGORY","Code de Catégorie");
define("_COD_LANG","Langue");
define("_COD_PRODUCT","Code de Produit");
define("_COMDAD_NAME","Departement");
define("_COMO","TO_TRANSLATE");
define("_COM_APER","Commission d'ouverture :");
define("_CONFIRM","Confirmation d'enregistrement");
define("_CONNECTED_AS","Connecté en tant que");
define("_CONTACTAR","Contact");
define("_CONTACTS","TO_TRANSLATE");
define("_CONTENTS","Contenus");
define("_CPASS","Mot de passe");
define("_CSSCONFIG","Fichier CSS");
define("_CSSFILE","Fichier CSS");
define("_CSS_DELETED","Fichier CSS supprimer");
define("_CTG","Catégorie");
define("_CTGS","Catégories");
define("_CTG_BELONGS","Catégorie à  laquelle il appartient");
define("_CTG_HAS_PROD","La catégorie a les produits, supprimer avant les produits");
define("_CTG_NO_EXIST","Catégorie n'existe pas");
define("_CTG_NO_NAME","Le nom de catégorie est obligatoire");
define("_CURRENT_PASS","Mot de passe Actuel");
define("_CUSTOMER","Client");
define("_CUSTZONE","Zone Client");
define("_DATE","Date");
define("_DATEMP","Données d'Organisation");
define("_DATETIME_SQL","'%d/%m/%Y - %H:%i'");
define("_DATE_FORMAT","d/m/Y");
define("_DATE_FT","Date");
define("_DATE_SQL","'%d/%m/%Y'");
define("_DATOS_PERS","Données Personnelles");
define("_DATPERS","Données Personnelles");
define("_DAY","Jour");
define("_DEACTIVE_ALL","TO_TRANSLATE");
define("_DECEMBER","Décembre");
define("_DEC_POINT",",");
define("_DELETE","Effacer");
define("_DELETED","Élément éliminé correctement");
define("_DEPT","Département");
define("_DEPTS","Départements");
define("_DESC_CATEGORY","Description");
define("_DESC_PROD","Description");
define("_DO_CALC","Calcul Emprunt Immobilier");
define("_DTL","TO_TRANSLATE");
define("_DTL_ACCOUNT","Données Client");
define("_DTL_ACCPERFIL","Données Profil d'Achat");
define("_DTL_PROP","Informations sur le bien immobilier");
define("_DT_CREATE","Date Création");
define("_DT_END","Date Fin");
define("_DT_SENT","Date d'Envoi");
define("_DT_START","Date Début");
define("_DT_VAL","Date Validité");
define("_DT_VALID","Valu jusque");
define("_EDIT","Éditer");
define("_EDTACC","Client");
define("_EDTCOMDAD","TO_TRANSLATE");
define("_EDTCONTACT","TO_TRANSLATE");
define("_EDTCOUNTRY","TO_TRANSLATE");
define("_EDTCTG","Catégorie de Produit");
define("_EDTGAL","Galerie");
define("_EDTHIMMO","Logements de Vacances");
define("_EDTHTML","Éditer Page");
define("_EDTIMMO","Bien Immobilier");
define("_EDTIMMOGAL","Photos bien immobilier");
define("_EDTLABEL","TO_TRANSLATE");
define("_EDTLST","Valeur");
define("_EDTMAILING","Détail du Mailing");
define("_EDTMSG","TO_TRANSLATE");
define("_EDTORG","Departement");
define("_EDTPERFIL","Profil d'Achat");
define("_EDTPERM","TO_TRANSLATE");
define("_EDTPOB","TO_TRANSLATE");
define("_EDTPOSITION","Détail Employé");
define("_EDTPRD","Produit");
define("_EDTPRDGAL","Photo Produit");
define("_EDTPREF","TO_TRANSLATE");
define("_EDTPRICELST","Éditer Liste de Prix");
define("_EDTPRICEPRD","Éditer Prix");
define("_EDTPROV","TO_TRANSLATE");
define("_EDTSCR","TO_TRANSLATE");
define("_EDTSDAY","Jours et prix");
define("_EDTSEASON","Détail Saison");
define("_EDTTICKET","TO_TRANSLATE");
define("_EDTTKCTG","TO_TRANSLATE");
define("_EDTTKEMAIL","TO_TRANSLATE");
define("_EDTUSER","Utilizateur");
define("_EDTVIEW","TO_TRANSLATE");
define("_EDT_ACCOUNT","Éditer client");
define("_EDT_CONTACT","TO_TRANSLATE");
define("_EDT_CTG","Éditer Catégorie");
define("_EDT_DEPT","Éditer Departement");
define("_EDT_EMPL","Éditer Employé");
define("_EDT_GAL","Éditer Galerie");
define("_EDT_IMMO","Editer Immeuble");
define("_EDT_MAILING","Editer mailing");
define("_EDT_NEW","Editer Nouvelle");
define("_EDT_PERM","TO_TRANSLATE");
define("_EDT_PROD","Éditer Produit");
define("_EDT_SCR","TO_TRANSLATE");
define("_EDT_USER","Éditer Utilizateur");
define("_EDT_VAL","Éditer la Valeur");
define("_EDT_VIEW","TO_TRANSLATE");
define("_EMPL","Employé");
define("_EMPLES","TO_TRANSLATE");
define("_ENVIAR","Envoyer");
define("_EQUIP_LIST","Équipements du Logement de Vacances");
define("_ERROR_CAPTCHA","Vérifier le mot de vérification");
define("_ERROR_CHECK_PSW","Erreur en vérifiant mot de passe");
define("_ERROR_CONTENT_MAILING","Le contenu est obligatoire");
define("_ERROR_CURRENT_PSW","Mot de passe actuel incorrect");
define("_ERROR_DATS","Erreur en accédant à les données");
define("_ERROR_DELETE","Erreur pendant l'effacement");
define("_ERROR_DIR_GAL","Erreur créant les chemises de la galery");
define("_ERROR_EMAIL_USER","Vous devez indiquer l'e-mail.");
define("_ERROR_ES_IN","Vous devez écrire une valeur espagnole");
define("_ERROR_IN","Erreur");
define("_ERROR_INSERT","Erreur pendant l'insertion");
define("_ERROR_LAST_USER","Vous ne pouvez pas supprimer le dernier utilisateur de l'organisation");
define("_ERROR_NAME_MAILING","Le nom du mailing est obligatoire");
define("_ERROR_NAME_USER","Le nom complet est obligatoire");
define("_ERROR_NM","TO_TRANSLATE");
define("_ERROR_NM_PROFILE","TO_TRANSLATE");
define("_ERROR_NOPOB","Villes non trouvées");
define("_ERROR_NUM_DOM","Indiquez le nombre de chambres");
define("_ERROR_NUM_PARKING","Écrivez le nombre de parkings");
define("_ERROR_NUM_WC","Le nombre de salles de bains est obligatoire");
define("_ERROR_OBSRV","TO_TRANSLATE");
define("_ERROR_OPEN_DIR","La chemise ne peut pas être ouverte");
define("_ERROR_OPEN_FILE","Erreur pendant l'ouverture du fichier");
define("_ERROR_PASSUSR_NULL","Le nom d'utilisateur et le mot de passe doivent être tous les deux vides ou tous les deux complétés");
define("_ERROR_PROCESS","Le processus a produit des erreurs");
define("_ERROR_PSW_ERROR","Mot de passe incorrect, merci d'entrer le mot de passe correct");
define("_ERROR_PSW_NOSTR","Le mot de passe ne peut contenir que des lettres et des chiffres, sans espaces");
define("_ERROR_PSW_SHORT","Le mot de passe doit comporter plus de 5 caractères");
define("_ERROR_PSW_USERNAME","Le mot de passe ne peut pas être le même que le nom d'utilisateur");
define("_ERROR_SUBJ_MAILING","Le sujet est obligatoire");
define("_ERROR_SUPERF","Parcelle de terrain en m2 ou zéro");
define("_ERROR_SUPERF_CONST","Surface en m2 ou zéro");
define("_ERROR_SUPERT","Écrivez la surface de terrasse ou 0  si n'existe pas");
define("_ERROR_TELF1_USER","Vous devez indiquer le nº de téléphone");
define("_ERROR_TXT_CONTENT","TO_TRANSLATE");
define("_ERROR_UPDATE","Erreur pendant la mise à jour");
define("_ERROR_USNAME_EXIST","Le nom d'utilisateur existe déjà, choisissez-en un autre");
define("_ERROR_USRNAME_EXISTS","L'utilisateur existe déjà");
define("_ERROR_USRNAME_NOSTR","Le nom d'utilisateur ne peut contenir que des lettres et des chiffres, sans espaces");
define("_ERROR_USRNAME_SHORT","Le nom d'utilisateur doit comporter plus de 5 caractères");
define("_ER_SELET_TBL","Erreur pendant SELECT TABLE");
define("_FDAY","Ve");
define("_FEBRUARY","Février");
define("_FECHA_FT","Date");
define("_FG_HIDDEN","TO_TRANSLATE");
define("_FG_PRIVATE","TO_TRANSLATE");
define("_FIND","Rechercher");
define("_FIND_BY_CITIES","Recherche par Ville");
define("_FIND_BY_CRITERIA","Recherche par Critères");
define("_FIND_BY_TPPROP","Recherche par type d'immeuble");
define("_FINPAGINA","");
define("_FOLDER","Chemise");
define("_FOUND","Total de coïncidences trouvées");
define("_FRIDAY","Vendredi");
define("_FRONT","Première page");
define("_FULL_NAME","Nom Complet");
define("_GALLERIES","Galeries de Photos");
define("_GALLERY","Galerie");
define("_GALS","Galeries de Photos");
define("_GAL_LST","Liste de Galeries");
define("_GAST_GEST","Frais de Gestion, Frais de Notaire, Inscription officielle. <br/> (Dépend de l'organisme de gestion) Minimum :");
define("_GENERAL_LAYOUT","STRUCTURE PAGES PRINCIPALES");
define("_GEN_LANG","Installez les changements des langues");
define("_GESTLANGS","Outils de Langues");
define("_GST_COMPRA","Frais d'achat du logement");
define("_GST_HIPOT","Frais d'Hypothèque");
define("_GUIA","Guide");
define("_HELP","Aide");
define("_HOME","Accueil");
define("_HOMEPG","Accueil");
define("_HOUR","Heure");
define("_IDIOMA","fr");
define("_ID_CATEGORY","Id de Catégorie");
define("_ID_POSITION","Attribué à");
define("_ID_TICKET","TO_TRANSLATE");
define("_IMAG","Images & Fichier flash");
define("_IMG","Photo");
define("_IMGCONFIG","Template Images");
define("_IMGHOME","head.jpg");
define("_IMGS_NOT","Images de la Nouvelle");
define("_IMG_FILE_ERROR","a un format faux (accents, espaces, etc.....) ou est plus grand que");
define("_IMG_FRONT","Image de Frontpage");
define("_IMG_INT_1","Image Intérieure 1");
define("_IMG_INT_2","Image Intérieure 2");
define("_IMG_INT_3","Image Intérieure 3");
define("_IMG_PORT","Frontpage Image");
define("_IMMO","Informations sur le bien immobilier");
define("_IMMOS","Biens Immobiliers");
define("_IMP_ACTOS","Impôts sur les actes authentiques");
define("_IMP_COMPRA","Taxe sur la Transmission de Patrimoine (Bien d'occasion) ou de TVA (Logement neuf) :");
define("_IMP_ENTR","Montant de l'Apport personnel");
define("_IMP_SOL","Montant emprunt immobilier");
define("_IND_ACTIVE","Actif");
define("_IND_MAILING","Mailing");
define("_IND_OFERTA","Offre");
define("_IND_PISCINA","Piscine");
define("_INFOLEGAL","Informations Juridiques");
define("_INSERTED","Insertion avec succès");
define("_INSIDE","Intérieur");
define("_INTROS_LIST","Liste d'étiquettes d'introduction");
define("_INT_BANC","Intérêts bancaires");
define("_INT_CAPACITY","Nbre de pers.");
define("_INT_PERS","TO_TRANSLATE");
define("_INT_SUPERFICIE","Terrain M2");
define("_INT_SUPERFICIE_CONST","Surface M2");
define("_INT_TERRACE","Terrasse M2");
define("_IN_NAME_ACCOUNT","Le nom du client est obligatoire");
define("_IN_NAME_GAL","Le nom de galerie est obligatoire");
define("_IN_NAME_IMMO","La référence est obligatoire");
define("_IN_NAME_ORG","TO_TRANSLATE");
define("_IN_NOT_RESUM","Le sommaire est obligatoire");
define("_IN_NOT_TITLE","Le titre est obligatoire");
define("_IN_POB_IMMO","Vous devez choisir une ville. Si n'est pas contacter l'administrateur");
define("_IN_POB_ORG","Vous devez choisir une ville");
define("_IN_SUBJECT","Indiquer un sujet");
define("_JANUARY","Janvier");
define("_JULY","Juillet");
define("_JUNE","Juin");
define("_KEYWORDS_ADM","TO_TRANSLATE");
define("_LABELS_LIST","Liste d'étiquettes du logicielle");
define("_LANGS","Langues");
define("_LANGUAGE","Langue");
define("_LATTITUD","TO_TRANSLATE");
define("_LBL_SEASONS","Saison");
define("_LOGIN_FAILED","Nom d'utilisateur ou mot de passe incorrects !");
define("_LOGIN_NOW","Entrer");
define("_LOGOUT","Se déconnecter");
define("_LONGITUD","TO_TRANSLATE");
define("_LOVS","TO_TRANSLATE");
define("_LSTMAILING","Mailing Listes");
define("_LSTUSER","Liste d'utilisateurs");
define("_M2","M2");
define("_M2_TERRACE","M2 de terrasse");
define("_M2_TERRENO","M2 de Terrain");
define("_MAILING","Campagnes de Mailing");
define("_MAIL_BKVALID","TO_TRANSLATE");
define("_MAIL_BKVALID_TXT","Cher M. 

Pour valider votre réserve vous devez vous rendre au lien suivant :");
define("_MAIL_CONFIRM","Votre demande d'enregistrement a été correctement transmise, vous recevrez très bientôt un e-mail de validation de votre enregistrement.");
define("_MAIL_FORMAT","Le format de l'e-mail est incorrect");
define("_MAIL_HRECEV","Nous avons reçu votre demande");
define("_MAIL_NMSG","Nous vous répondrons dans les plus brefs délais");
define("_MAIL_NOTI","Avis de réception");
define("_MAIL_REM","Données d'accès");
define("_MAIL_REM_TXT","Cher M. 

Votre données d'accès sont :");
define("_MAIL_SUBS","Confirmation d'enregistrement");
define("_MAIL_SUBS_TXT","Cher M. 

 Pour valider votre enregistrement  vous devez vous rendre au lien suivant : 

");
define("_MAIN_IMG","Image Principale");
define("_MANDATORY","TO_TRANSLATE");
define("_MAPINIT","TO_TRANSLATE");
define("_MARCH","Mars");
define("_MAY","Mai");
define("_MDAY","Lu");
define("_MKT","Mailings");
define("_MNU_ADM","Menu");
define("_MONDAY","Lundi");
define("_MONTH","Mois");
define("_MSG","Message");
define("_MY_ACCOUNTS","Mes Clients");
define("_MY_IMMOS","Mes Propriétés");
define("_MY_NEWS","Mes Nouvelles");
define("_MY_PROFILE","Mon Profil");
define("_MY_TICKETS","TO_TRANSLATE");
define("_MY_TK_STATS","TO_TRANSLATE");
define("_NAME","TO_TRANSLATE");
define("_NAME_ACCOUNT","Nom de Client");
define("_NAME_CATEGORY","Catégorie");
define("_NAME_GAL","Nom Galerie");
define("_NAME_MAILING","Nom Mailing");
define("_NAME_ORG","Bureau");
define("_NAME_POB","Ville");
define("_NAME_POSITION","Position");
define("_NAME_PRICE_LST","Nom List");
define("_NAME_PRODUCT","Nom Produit");
define("_NAME_SEASONS","Nom de Saison");
define("_NAME_USER","Employé / Utilizateur");
define("_NESPECIAL","Nos Promotions Spéciales");
define("_NEW","Nouvelle");
define("_NEWS","Dernières nouveautés");
define("_NEWSLST","Liste de Nouvelles");
define("_NEWS_EVENTS","Nouveautés et événements");
define("_NEWUSER","Nouvel Utilisateur");
define("_NEW_PASSWORD","Nouveau Mot de passe");
define("_NEW_POS","En première page");
define("_NEW_PROP","Logement Neuf");
define("_NEW_RESUM","Résumé");
define("_NEW_TITLE","Titre");
define("_NEW_TXT","Texte");
define("_NEXT","Suivant");
define("_NM_CONTACT","TO_TRANSLATE");
define("_NM_PROFILE","TO_TRANSLATE");
define("_NM_SCREEN","TO_TRANSLATE");
define("_NM_TK_CTG","TO_TRANSLATE");
define("_NM_VIEW","TO_TRANSLATE");
define("_NOREGUSERS","Il n'y a aucun client enregistré à le mailing");
define("_NOSELECTED","Non sélectionné");
define("_NOTFOUND","TO_TRANSLATE");
define("_NOTI","Nouvelle");
define("_NOTICIA","Voir Dernière nouvelle");
define("_NOVED","Nouveautés");
define("_NOVED_TXT","Derniers bien immobiliers disponibles");
define("_NOVEMBER","Novembre");
define("_NO_ACCOUNT","Clients non trouvés");
define("_NO_AV_LG","Cette information n'est pas disponible dans cette langue.");
define("_NO_COD","Code est obligatoire");
define("_NO_CONTACT","TO_TRANSLATE");
define("_NO_CTG","Catégories non trouvées");
define("_NO_EMPL","Employés non trouvés");
define("_NO_GALS","Galeries non trouvées");
define("_NO_IMG_FRONT","La galerie n'a pas une image principale. Pour éditer des offres vous devez choisir une image principale.");
define("_NO_IMG_INT_1","Il n'y pas image intérieure 1");
define("_NO_IMG_INT_2","Il n'y pas image intérieure 2");
define("_NO_IMG_INT_3","Il n'y pas image intérieure 3");
define("_NO_IMG_PORT","Il n'y pas frontpage image");
define("_NO_IMMO","Il n'existe aucun bien immobilier");
define("_NO_MAILING","Mailing non trouvée");
define("_NO_MEMBERS","Vous n'avez pas des membres dans votre équipe");
define("_NO_NOTS","Nouvelles non trouvées");
define("_NO_ORGS","Organization non trouvées");
define("_NO_PRICE_LST","Il n'y a pas listes de prix");
define("_NO_PROD","Produit non trouvées");
define("_NO_PSTS","No positions");
define("_NO_SEASONS","il n'y a pas de saisons");
define("_NO_TICKET","TO_TRANSLATE");
define("_NUMORDER","TO_TRANSLATE");
define("_NUM_DORMITORIO","chambre");
define("_NUM_DORMITORIOS","chambres");
define("_NUM_HITS","Pages Vu");
define("_NUM_ORDER","Ordre");
define("_NUM_PARKING","Place de parking");
define("_NUM_PARKINGS","places de parking");
define("_NUM_ROBOTS","Moteurs de Recherche");
define("_NUM_SENT","Nombre des livraisons");
define("_NUM_VISITS","Visites");
define("_NUM_WC","salle de bains");
define("_NUM_WCS","Salles de bains");
define("_OBSERV_LIST","Liste d'étiquettes de remarques dans des locations de vacances");
define("_OCTOBER","Octobre");
define("_OF","de");
define("_OFICINAS","Bureaux");
define("_ONLOAD","TO_TRANSLATE");
define("_OPINION","You view about this web");
define("_OPTIONAL","(En option)");
define("_ORDER","Ordre");
define("_ORDERBY","Classer par");
define("_ORG","Organization");
define("_ORG_HAS_SUBORG","Le département a des secondaire-départements, effacer secondaire-départements avant.");
define("_ORG_LST","Organization Structure");
define("_OUTAPP","APPLICATION OUTPUT");
define("_PAGE","Page");
define("_PAGO_MEN","Remboursement mensuel de l'emprunt immobilier");
define("_PAGS","Pages");
define("_PARAMS","TO_TRANSLATE");
define("_PARENTCTG_DCHILDREN","La catégorie a des sous-catégories, effacer sous-catégories avant");
define("_PASSWORD","Mot de passe");
define("_PATH_IMAGE","Image");
define("_PERMS","Rôle");
define("_PERMS_HAS_SCR","TO_TRANSLATE");
define("_PICTURES","Photos");
define("_PIEPAGINA","Powered by <a href=\"http://reos.elazos.com\">ReOS "._VERSION."</a> and released under the <a href=\"http://www.fsf.org/licensing/licenses/agpl-3.0.html\">GNU/AGPLv3 License.</a>");
define("_PLEASE_LOGIN","Merci d'indiquer votre nom d'utilisateur et votre mot de passe");
define("_POBLACIONES","Activer Villes");
define("_POBS","Recherche par villes");
define("_POPHOST","TO_TRANSLATE");
define("_POPPASS","TO_TRANSLATE");
define("_POPUSER","TO_TRANSLATE");
define("_POSITION","Position");
define("_POS_IMG_PORT","Frontpage Position");
define("_PRECIO","Prix");
define("_PRECIO_ALQUILER","Prix de Location "._CURRENCY."");
define("_PRECIO_COMPRA","Prix d'Achat "._CURRENCY."");
define("_PREFERE","Preferences");
define("_PREF_POBS","Villes Préférées");
define("_PREVIOUS","Précédent");
define("_PRE_VIVIE","Prix du logement");
define("_PRICE_FROM","Prix depuis");
define("_PRICE_MAX","Prix Maxi "._CURRENCY."");
define("_PRICE_MIN","Prix Mini "._CURRENCY."");
define("_PRIORITY","TO_TRANSLATE");
define("_PROCESS_OK","Le processus s'est exécuté avec succès");
define("_PRODS","Produits");
define("_PROFS","TO_TRANSLATE");
define("_PROP_ACCOUNT","Biens immobiliers du Client");
define("_PROV_NAME","Province");
define("_PRT_LAYOUT","PRINTING LAYOUT PAGES");
define("_PST_ELEMTS","Position a des éléments assigné. Veuillez supprimer les éléments avant");
define("_PUBLI_YOUR","Publi votre propieté");
define("_READMORE","Lire plus de détails...");
define("_RECOM","Nous vous conseillons");
define("_REFERERS","Expéditeurs");
define("_REF_IMMO","Référence");
define("_REF_TICKET","TO_TRANSLATE");
define("_REGS_TXT","Pour éviter que d'autres utilisateurs puissent l'enregistrer, vous recevrez un e-mail de confirmation avec les instructions pour valider votre enregistrement.Par l'envoi de ce formulaire, vous vous enregistrez au zone clients. Votre adresse e-mail sera votre identification d'utilisateur.");
define("_REGUSERS","Clients enregistrés à le mailing");
define("_REM_CONFIRM","Vérifies ton email.");
define("_REM_TXT","Entrez votre adresse email et nous t'enverrons tes données d'accès.");
define("_REM_USR","Vous avez perdu votre mot de passe ?");
define("_RESERVATION","TO_TRANSLATE");
define("_RESERV_CONFIRM","TO_TRANSLATE");
define("_RESTORE","Restore Backup");
define("_RESULTS","Résultat de la recherche");
define("_RE_NEW_PASS","Confirmer le nouveau Mot de passe");
define("_RE_PASSWORD","Confirmer le Mot de passe");
define("_ROOT_DEPT","Département Initial");
define("_ROWS","Enregistrements");
define("_SADAY","Sa");
define("_SATURDAY","Samedi");
define("_SAT_DEPT","Service clients");
define("_SAVE","Enregistrer");
define("_SCREEN","TO_TRANSLATE");
define("_SCREENS","TO_TRANSLATE");
define("_SCREEN_HAS_VIEW","TO_TRANSLATE");
define("_SDAY","Di");
define("_SEARCH_TITLE","Recherche");
define("_SEASONS","Saisons pour des locations de vacances");
define("_SEE2PRINT","Voir pour imprimer");
define("_SEE_CYRILIC","Montrez Les Langues Cyrilic");
define("_SEE_LATIN1","Montrez Les Langues Occidentales");
define("_SEGUROS","Assurances");
define("_SELECT","Sélectionner");
define("_SELECTED","sélectionnés");
define("_SELECTLANGUAGE","Changer de Langue !");
define("_SEND_OUTLOOK","Envoyez à Outlook");
define("_SEPTEMBER","Septembre");
define("_SERVICES_LIST","Liste d'étiquettes de Services");
define("_SET_ACTIVITIES","Activités");
define("_SET_EQUIP","Équipement");
define("_SET_IMG_FRONT","Choisissez principale");
define("_SET_INTRO","Introduction");
define("_SET_OBSERV","Remarques");
define("_SET_PROPERTIES","Caractéristiques");
define("_SET_SERVICES","Services");
define("_SHOW_GAL","Montrer Galerie");
define("_SINFO","Demande d'informations");
define("_SINFO_ADVERT","Par la page web nous ne collectons aucune information personnelle à votre insu, et aucune information n'est transmise à un tiers.");
define("_SINFO_CONFIRM","Formulaire de contact envoyé correctement.");
define("_SINFO_TXT","Envoyez-nous vos coordonnées et nous prendrons contact avec vous");
define("_SLOGAN","Gestion immobilière");
define("_START","Accueil");
define("_STATE","État");
define("_STATISTICS","Statistiques Web");
define("_SUBJECT","TO_TRANSLATE");
define("_SUBS","Enregistrez-vous");
define("_SUBS_PHRASE","Recevez notre bulletin d'informations");
define("_SUBS_TXT","Pour éviter que d'autres utilisateurs puissent l'enregistrer, vous recevrez un e-mail de confirmation avec les instructions pour valider votre enregistrement.Par l'envoi de ce formulaire, vous vous enregistrez au service de bulletin d'informations.");
define("_SUNDAY","Dimanche");
define("_SUPPORT","TO_TRANSLATE");
define("_TDAY","Ma");
define("_TEAM_ACCOUNTS","Les Clients de mon équipe");
define("_TEAM_IMMOS","Les propriété de mon équipe");
define("_TEAM_TICKETS","TO_TRANSLATE");
define("_THDAY","Je");
define("_THEMES","TO_TRANSLATE");
define("_THOUSANDS_SEP",".");
define("_THUMB","Photos");
define("_THURSDAY","Jeudi");
define("_TICKETS","TO_TRANSLATE");
define("_TITLE_LOGIN","Zone d'Administration");
define("_TK_CTG_LST","TO_TRANSLATE");
define("_TOCLOSE","TO_TRANSLATE");
define("_TODO","Action");
define("_TOEND","Finir");
define("_TOTAL","Total");
define("_TOT_GST","Total des frais :");
define("_TOY_INTERES","Contacter pour ce bien immobilier");
define("_TP_PRICE","Type Prix");
define("_TP_PROPIEDAD","Type de propriété");
define("_TP_SDAYS","Type");
define("_TP_SEND","Type d'envoyement");
define("_TP_SEND_TO","Envoyer à");
define("_TP_SERVICIO","Opération");
define("_TP_STATE","État");
define("_TP_VAT","TVA %");
define("_TUESDAY","Mardi");
define("_TXT_ADDRESS1","Adresse");
define("_TXT_AGE","TO_TRANSLATE");
define("_TXT_ASUNT","Objet");
define("_TXT_COMMENT","Commentaires");
define("_TXT_COMO","TO_TRANSLATE");
define("_TXT_CONTENT","Contenu");
define("_TXT_COUNTRY","TO_TRANSLATE");
define("_TXT_CP","Code postal");
define("_TXT_DESC","Description");
define("_TXT_EMAIL","eMail");
define("_TXT_EMAIL1","Courrier");
define("_TXT_ES","Valeurs");
define("_TXT_FAX","Fax");
define("_TXT_MAILING","Dans les campagnes de mailing vous pouvez envoyer massivement à vos clients");
define("_TXT_OBSRV","TO_TRANSLATE");
define("_TXT_POBLACION","Ville");
define("_TXT_SEARCH","Textes de recherche");
define("_TXT_SIGN","TO_TRANSLATE");
define("_TXT_SUBJECT","Sujet");
define("_TXT_TELF1","Téléphone");
define("_TXT_TELF2","Téléphone 2");
define("_TXT_TITLE","Titre");
define("_TXT_UNREG","Vous avez reçu ce courrier suite à votre enregistrement dans notre liste de distribution. Si vous ne souhaitez pas recevoir d'autres e-mails, cliquez sur :");
define("_TXT_URL","Url");
define("_TXT_WEB","Web");
define("_TXT_ZONA","Zone");
define("_UMONTH","Mois");
define("_UNREG","Annuler son inscription.");
define("_UNTITLED","Non défini");
define("_UPDATE","Mettre à jour");
define("_UPDATED","Mis à jour avec succès");
define("_USED_PROP","Logement d'Occasion");
define("_USER","Utilizateur");
define("_USERNAME","Utilisateur");
define("_USER_DELETED","Utilisateur supprimé avec succès");
define("_USER_HAS_PST","L'utilisateur a une position assigner. Effacer la Position avant");
define("_USER_INSERTED","Utilisateur ajouté avec succès");
define("_USER_TYPE","Type");
define("_USR_BOOK_NOVALID","TO_TRANSLATE");
define("_USR_CONFIRM","Votre enregistrement est confirmé.");
define("_USR_NOCONFIRM","Nous avons détecté une erreur dans votre confirmation d'enregistrement.");
define("_USR_NOUNREG","Votre inscription n'a pu être validée pour élimination. Veuillez prendre contact avec le Service Client si vous recevez d'autres e-mails.");
define("_USR_UNREG","Votre inscription à la liste de distribution de courrier a été annulée");
define("_VALUE","TO_TRANSLATE");
define("_VERACCS","Recherche de Clients");
define("_VERBOOKINGS","Availability Search");
define("_VERCONFIG","Template Configuration");
define("_VERCOUNTRIES","TO_TRANSLATE");
define("_VERGAL","Galerie d'Image");
define("_VERHTML","Voir pages");
define("_VERIMMO","Recherche de Biens immobiliers");
define("_VERINTROS","Étiquette de l'introduction d'offre");
define("_VERLABELS","TO_TRANSLATE");
define("_VERMAILINGS","Campagnes de mailing");
define("_VERNOT","Nouvelles et Événements");
define("_VERORGS","Organization");
define("_VERPERMS","TO_TRANSLATE");
define("_VERPOBS","Activer des Villes");
define("_VERPRD","Produits");
define("_VERPREFS","TO_TRANSLATE");
define("_VERPRICELST","Listes de Prix");
define("_VERPRICEPRD","Produits et Prix");
define("_VERPROPER","Étiquettes des propriétés d'offre");
define("_VERSCR","TO_TRANSLATE");
define("_VERSEASONS","Liste de Saisons");
define("_VERTICKETS","TO_TRANSLATE");
define("_VERTKCTGS","TO_TRANSLATE");
define("_VERTKEMAILS","TO_TRANSLATE");
define("_VERUSERS","Liste d'utilisateurs");
define("_VERVIEWS","TO_TRANSLATE");
define("_VER_PERFIL","Profil d'Achat");
define("_VIEW","View");
define("_VIEWED","Visualisés");
define("_VIEWS","TO_TRANSLATE");
define("_VIEWS_LST","TO_TRANSLATE");
define("_VIEW_FRONT_IN","Nouvelle");
define("_WANT_SELL","Je veux Vendre");
define("_WANT_SELL_TXT","Acheter votre logement à son prix réel !");
define("_WDAY","Mi");
define("_WEDNESDAY","Mercredi");
define("_WORDS_TO_FIND","Rechercher par mots");
define("_XMLNAV","XML Layout File");
define("_XMLOUTPUT","XML Output File");
define("_XMLPRT","XML Printing Layout File");
define("_XSLFILE","XSL Transformation File");
define("_XSLPRT","XSL Printing Transformation File");
define("_YEAR","Année");
define("_YEARS","Années");
define("_YOUR_LOAN","Calculez votre emprunt immobilier");
define("_ZIP_FILE","ZIP File");
?>